Repository OpenSlides/openslides-client, pull requests merged in 2022-04, with the labels that each got.

#999 Fixes updating of new groups (#985)
  client/src/app/core/repositories/users/group-repository.service.ts
Labels: critical, backend ready

#986 Implemented a create wizard to add participants to a meeting (#667)
  client/src/app/core/core-services/presenters/get-user-scope-presenter.service.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/core/ui-services/user.service.ts
  client/src/app/shared/components/user-detail-view/user-detail-view.component.html
  client/src/app/shared/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/users/components/user-create-wizard/user-create-wizard.component.html
  client/src/app/site/users/components/user-create-wizard/user-create-wizard.component.scss
  client/src/app/site/users/components/user-create-wizard/user-create-wizard.component.spec.ts
  client/src/app/site/users/components/user-create-wizard/user-create-wizard.component.ts
  client/src/app/site/users/components/user-detail/user-detail.component.ts
  client/src/app/site/users/components/user-list/user-list.component.html
  client/src/app/site/users/components/user-list/user-list.component.ts
  client/src/app/site/users/users-routing.module.ts
  client/src/app/site/users/users.module.ts
Labels: needs discussion

#1005 Add flow text option to PDF export
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/motions/motions.constants.ts
  client/src/app/site/motions/services/motion-pdf-catalog.service.ts
  client/src/app/site/motions/services/motion-pdf-export.service.ts
  client/src/app/site/motions/services/motion-pdf.service.ts
Labels: feature

#1009 Pdf export revise
  client/src/app/core/pdf-services/html-to-pdf.service.ts
  client/src/app/core/pdf-services/pdf-document.service.ts
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/motions/motions.constants.ts
  client/src/app/site/motions/services/motion-pdf-catalog.service.ts
Labels: feature

#1006 Bugfix: line number inconsistency when creating change recommendations
  client/src/app/core/repositories/motions/motion-change-recommendation-repository.service.ts
  client/src/app/core/repositories/motions/motion-line-numbering.service.ts
  client/src/app/core/ui-services/linenumbering.service.ts
  client/src/app/shared/models/motions/motion.ts
  client/src/app/site/motions/models/view-motion-change-recommendation.ts
  client/src/app/site/motions/modules/motion-detail/components/base/base-change-recommendation-dialog.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-change-recommendation-dialog/motion-change-recommendation-dialog.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-highlight-form/motion-highlight-form.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-highlight-form/motion-highlight-form.component.scss
  client/src/app/site/motions/modules/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
  client/src/app/site/motions/services/motion-format.service.ts
  client/src/app/site/motions/services/motion-pdf.service.ts
  client/src/app/slides/motion/motion-slide-data.ts
  client/src/app/slides/motion/motion-slide.component.ts
Labels: high

#992 Some enhancements for committees and meetings
  client/cli/generate-permissions.ts
  client/src/app/core/actions/meeting-action.ts
  client/src/app/core/core-services/action.service.ts
  client/src/app/core/core-services/permission-children.ts
  client/src/app/core/core-services/permission.config.ts
  client/src/app/core/core-services/permission.ts
  client/src/app/core/core-services/sequential-number-mapping.service.ts
  client/src/app/core/repositories/management/committee-repository.service.ts
  client/src/app/core/repositories/management/meeting-repository.service.ts
  client/src/app/core/repositories/management/organization-repository.service.ts
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/core/repositories/motions/motion.service.ts
  client/src/app/core/repositories/relations.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/core/ui-services/base-import.service.ts
  client/src/app/core/ui-services/user-search.service.spec.ts
  client/src/app/core/ui-services/user-search.service.ts
  client/src/app/management/components/committee-import-list/committee-import-list.component.html
  client/src/app/management/components/committee-import-list/committee-import-list.component.ts
  client/src/app/management/components/meeting-edit/meeting-edit.component.html
  client/src/app/management/components/meeting-edit/meeting-edit.component.ts
  client/src/app/management/components/meeting-preview/meeting-preview.component.html
  client/src/app/management/components/meeting-preview/meeting-preview.component.ts
  client/src/app/management/export/committee-csv-export-example.ts
  client/src/app/management/models/view-committee.ts
  client/src/app/management/models/view-meeting.ts
  client/src/app/management/models/view-organization.ts
  client/src/app/management/services/committee-import.service.ts
  client/src/app/shared/components/base-form-control.ts
  client/src/app/shared/components/detail-view/detail-view.component.ts
  client/src/app/shared/components/search-selector/base-search-value-selector/base-search-value-selector.component.html
  client/src/app/shared/components/search-selector/base-search-value-selector/base-search-value-selector.component.ts
  client/src/app/shared/components/search-selector/search-value-selector/search-value-selector.component.ts
  client/src/app/shared/components/selectable.ts
  client/src/app/shared/models/event-management/committee.constants.ts
  client/src/app/shared/models/event-management/committee.ts
  client/src/app/shared/models/event-management/meeting.ts
  client/src/app/shared/models/event-management/organization.ts
  client/src/app/shared/utils/import/base-before-import-handler.ts
  client/src/app/shared/utils/import/base-import-handler.ts
  client/src/app/shared/utils/import/base-side-import-handler.ts
  client/src/app/shared/utils/import/import-step.ts
  client/src/app/shared/utils/import/import-utils.ts
  client/src/app/site/interaction/components/call/call.component.html
  client/src/app/site/interaction/components/stream/stream.component.html
  client/src/app/site/interaction/services/stream.service.ts
  client/src/app/site/motions/import/category-import-helper.ts
  client/src/app/site/motions/import/motion-block-import-helper.ts
  client/src/app/site/motions/import/tag-import-helper.ts
  client/src/app/site/motions/import/user-import-helper.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/users/components/group-list/group-list.component.ts
  client/src/app/site/users/components/user-create-wizard/user-create-wizard.component.ts
  client/src/app/site/users/services/user-import.service.ts
Labels: high

#1018 Fixed custom font url
  client/src/app/core/pdf-services/pdf-document.service.ts
Labels: bug, high

#1020 Remove category_id from payload for non-admins
  client/src/app/site/motions/modules/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: bug

#1022 Fix chat group deletion error
  client/src/app/site/chat/components/chat-group-detail/chat-group-detail.component.html
  client/src/app/site/chat/components/chat-group-detail/chat-group-detail.component.ts
Labels: bug
