Repository OpenSlides/openslides-client, pull requests merged in 2022-09, with the labels that each got.

#1550 Fixed ballot printing
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
Labels: high, affected view: polls

#1501 move meeting template toggle to menu and add confirmation
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.scss
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
Labels: feature, affected view: committee

#1541 1190 fix font deselection
  client/src/app/domain/models/base/base-model.ts
  client/src/app/domain/models/mediafiles/mediafile.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
Labels: bug, high

#1491 Worked old 'sorting view for motion states' changes into current client
  client/src/app/gateways/repositories/motions/motion-state-repository.service/motion-state-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-state-repository.service/motion-state.action.ts
  client/src/app/gateways/repositories/motions/motion-workflow-repository.service/motion-workflow-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/states/services/motion-state-controller.service/motion-state-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/workflows/services/motion-workflow-controller.service/motion-workflow-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/workflows-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/workflows.module.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/ui/modules/choice-dialog/components/choice-dialog/choice-dialog.component.html
  client/src/app/ui/modules/choice-dialog/definitions/index.ts
  client/src/app/ui/modules/choice-dialog/services/choice.service.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.html
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.scss
Labels: feature, affected view: motion, need test instance

#1468 fix disappearing lines due to new amendment
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
Labels: bug, high

#1521 cleanup diff service
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/testing/models/test-change-recommendation.ts
Labels: clean up

#1540 Changed import list to show checkboxes for boolean entries
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
Labels: high

#1551 Meeting upload UI bugs
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.html
  client/src/app/ui/modules/file-upload/components/file-upload/file-upload.component.html
Labels: bug, high

#1544 Fix ICC by bypassing the ngsw
  client/ngsw-config.json
  client/src/app/gateways/http-stream/http-stream-endpoint.service.ts
  client/src/app/gateways/http.service.ts
Labels: bug, high

#1563 Fix workflow import
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-import/workflow-import.component.html
Labels: bug, high

#1564 Fix PDF export
  client/src/app/gateways/http.service.ts
Labels: bug, high

#1548 Stopped client from sending null values in analog poll creation
  client/src/app/gateways/repositories/polls/poll-repository.service/poll-repository.service.ts
  client/src/app/infrastructure/utils/functions.ts
Labels: high, affected view: polls

#1565 Fix participant creation wizard
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug, high

#1567 Fixed list view sorting.
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug, high

#1560 Added new filters and sorting options to the account list
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: high, affected view: account

#1572 fix participant list autoupdate
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: high

#1429 Update history to new format
  client/src/app/gateways/presenter/history-presenter.service.ts
  client/src/app/site/modules/translations/marked-translations.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/assets/i18n/de.json
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: feature, high

#1579 Readd datagroup in ngsw-config and cleanup code
  client/ngsw-config.json
  client/src/app/gateways/http.service.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: bug, critical, affected view: mediafile

#1581 keep selection in scroll tables if data filtered
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#1583 Added CML-filter to, and rearranged account list filters
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: affected view: account

#1593 Fixed mobile view for motion edit
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
Labels: affected view: motion

#1601 Cleaned up forwarding filter
  client/src/app/site/pages/meetings/pages/motions/config/model-subscription.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: clean up

#1603 PDF export, Let texts have multiple decoration
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#1605 Hide decision checkboxes when the motion is in the last state
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: feature

#1608 Fix motion block slide style
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.scss
Labels: bug

#1610 fix projector poll service used before set
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
Labels: bug

#1611 fix projectors overview polls not displayed
  client/src/app/site/pages/meetings/modules/projector/projector.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/projector-detail.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/projector-list.module.ts
Labels: bug

#1617 hide speaker amount if zero
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.html
Labels: bug

#1616 add autopilot projector border
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
Labels: bug

#1618 fix wrong poll percent no general options
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll.service.ts
Labels: bug, high

#1602 fix BaseModelRequestHandlerComponent onParamsChanged not called
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-main/history-main.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-main/meeting-settings-group-detail-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail/participant-detail.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/fullscreen-projector/components/fullscreen-projector-main/fullscreen-projector-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail-main/account-detail-main.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/components/committee-detail/committee-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/committee-detail-meeting-main/committee-detail-meeting-main.component.ts
Labels: bug, high

#1620 fix first login takes too long
  client/src/app/site/services/operator.service.ts
Labels: bug

#1606 Restyled account list and reworked account search
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-search/account-list-search.service.spec.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-search/account-list-search.service.ts
Labels: affected view: account, test instance active

#1596 Improve Layout of committee detail view
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.scss
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
Labels: feature, high

#1621 improve cypress tests
  .github/workflows/build.yml
  client/tests/integration/Dockerfile.test
  client/tests/integration/cypress-docker.json
  client/tests/integration/cypress.config.js
  client/tests/integration/cypress.json
  client/tests/integration/cypress/integration/client-load.spec.ts
  client/tests/integration/cypress/integration/committee.spec.ts
  client/tests/integration/cypress/integration/login.spec.ts
  client/tests/integration/cypress/plugins/index.js
  client/tests/integration/cypress/support/commands.ts
  client/tests/integration/cypress/support/index.ts
  client/tests/integration/cypress/tsconfig.json
  client/tests/integration/docker-compose.test.yml
  client/tests/integration/package-lock.json
  client/tests/integration/package.json
  client/tests/integration/resource-config-docker.js
Labels: feature

#1626 hide motion forward button after forward and move it to menu
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: feature, high

#1634 Fix counting of users
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.ts
Labels: bug

#1627 Restyled 'Add to Meeting'
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.scss
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: high

#1635 Implemented account detail committee-meeting table
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail-main/account-detail-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
Labels: feature, high, affected view: account

#1639 Restyled motion forward dialog
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
Labels: feature, high

#1556 handle autoupdate via shared worker
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/openslides-main-module/services/default-shared-worker.worker.ts
  client/src/app/openslides-main-module/services/shared-worker.service.ts
  client/src/app/site/pages/meetings/services/sequential-number-mapping.service.ts
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/model-request.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/autoupdate-subscription.ts
  client/src/app/worker/interfaces-autoupdate.ts
  client/src/app/worker/interfaces.ts
  client/src/app/worker/sw-autoupdate.ts
  client/tests/integration/cypress/integration/committee.spec.ts
  client/tests/integration/cypress/support/index.ts
  client/tests/integration/cypress/support/setup.ts
Labels: feature, high
