Repository OpenSlides/openslides-client, pull requests merged in 2022-03, with the labels that each got.

#897 Date number (#808)
  client/src/app/shared/models/mediafiles/mediafile.ts
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/mediafiles/models/view-mediafile.ts
Labels: bug, good first issue

#925 Some fixes for assignments
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/shared/models/poll/poll-constants.ts
  client/src/app/site/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/cinema/components/cinema/cinema.component.ts
  client/src/app/site/projector/services/current-list-of-speakers.service.ts
Labels: high

#930 A better motion handling for delegates
  client/src/app/core/actions/motion-action.ts
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-content/motion-content.component.ts
Labels: critical

#947 Fixes attaching of files to motions
  client/src/app/core/core-services/key-transforms.ts
  client/src/app/shared/components/attachment-control/attachment-control.component.scss
  client/src/app/site/motions/modules/motion-detail/components/motion-content/motion-content.component.ts
Labels: critical

#961 Hotfix: reduce computation times of affected lines for amendments
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/shared/components/list-view-table/list-view-table.component.ts
  client/src/app/site/motions/models/view-motion.ts
  client/src/app/site/motions/modules/amendment-list/amendment-list.component.html
  client/src/app/site/motions/modules/amendment-list/amendment-list.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/motions/modules/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.html
  client/src/app/site/motions/modules/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.ts
  client/src/app/site/motions/services/amendment-list-pdf.service.ts
Labels: high

#972 Fixes some bugs
  client/src/app/core/ui-services/voting.service.ts
  client/src/app/shared/components/search-selector/base-search-value-selector/base-search-value-selector.component.ts
  client/src/app/site/assignments/components/assignment-list/assignment-list.component.ts
  client/src/app/site/motions/modules/motion-detail/components/manage-submitters/manage-submitters.component.ts
  client/src/app/site/motions/modules/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/slides/base-slide-component.ts
  client/src/app/slides/motion/motion-slide.component.ts
Labels: high
