Repository OpenSlides/openslides-client, pull requests merged in 2022-05, with the labels that each got.

#1030 Remove category_id from payload for non-admins for amendments
  client/src/app/site/motions/modules/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
Labels: high

#1066 Remove collection from motion_state creation
  client/src/app/site/motions/modules/motion-workflow/components/workflow-detail/workflow-detail.component.ts
Labels: bug

#1049 Fix relative links in TinyMCE
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
Labels: bug, high

#1051 Restructure cloning repository methods
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/meetings/services/meeting-controller.service.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
Labels: bug, high

#1086 Adjust mediafiles to handle owner_id
  client/src/app/domain/models/mediafiles/mediafile.ts
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-mediafile.ts
Labels: bug, high, affected view: mediafile

#1048 Always use global login & add success message for password change
  client/src/app/site/services/openslides-router.service.ts
  client/src/app/ui/modules/global-headbar/modules/account/components/account-dialog/account-dialog.component.html
  client/src/app/ui/modules/global-headbar/modules/account/components/account-dialog/account-dialog.component.ts
  client/src/app/ui/modules/password-form/components/password-form/password-form.component.html
  client/src/app/ui/modules/password-form/components/password-form/password-form.component.scss
  client/src/app/ui/modules/password-form/components/password-form/password-form.component.spec.ts
  client/src/app/ui/modules/password-form/components/password-form/password-form.component.ts
  client/src/app/ui/modules/password-form/definitions/index.ts
  client/src/app/ui/modules/password-form/index.ts
  client/src/app/ui/modules/password-form/password-form.module.ts
  client/src/app/ui/modules/password-form/validators/index.ts
  client/src/app/ui/modules/password-form/validators/password-validator.ts
  client/src/app/ui/modules/user-components/components/password-form/password-form.component.html
  client/src/app/ui/modules/user-components/components/password-form/password-form.component.ts
  client/src/app/ui/modules/user-components/components/user-password-form/user-password-form.component.ts
Labels: bug, high

#1052 Include the motion attachment in the PDF export
  client/src/app/domain/models/motions/motions.constants.ts
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-images.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
Labels: feature, high

#1125 Fixes the import of participants (#1124)
  client/src/app/infrastructure/utils/import/static-before-import-config.ts
  client/src/app/infrastructure/utils/import/static-before-import-handler.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/participant-import-routing.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/participant-import.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import-service.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/participants-routing.module.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
Labels: blocker

#1131 Fixed hidden link to extend comment field content (fixed #1130)
  client/src/app/ui/modules/action-card/components/action-card/action-card.component.scss
Labels: high

#1132 Fixes filtering through lists (#1129)
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/categories/services/motion-category-controller.service/motion-category-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/tags/services/tag-controller.service/tag-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/workflows/services/motion-workflow-controller.service/motion-workflow-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/services/motion-block-detail-filter-list.service/motion-block-detail-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/amendment-list-filter.service/amendment-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/polls/modules/poll-list/services/poll-list-filter.service/poll-list-filter.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-filter.service/committee-filter.service.ts
Labels: critical

#1133 Fixes creating of category tiles (#1127)
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.scss
  client/src/app/ui/modules/grid/grid/grid.component.html
  client/src/app/ui/modules/grid/grid/grid.component.ts
Labels: critical

#1136 Fix pdf export comment
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
Labels: critical

#1147 Some Fixes
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/infrastructure/utils/import/static-before-import-handler.ts
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/modules/site-wrapper/services/update.service.ts
  client/src/app/site/modules/site-wrapper/site-wrapper.module.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.scss
  client/src/app/site/pages/meetings/pages/agenda/components/agenda-main/agenda-main.component.ts
  client/src/app/site/pages/meetings/pages/assignments/components/assignment-main/assignment-main.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-main/history-main.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/components/mediafile-main/mediafile-main.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-main/meeting-settings-group-detail-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-main/motion-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/categories/services/motion-category-controller.service/motion-category-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-final-version/motion-final-version.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
  client/src/app/site/pages/meetings/pages/participants/components/participant-main/participant-main.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-main/projector-main.component.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/services/model-request.service.ts
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
  client/src/app/ui/modules/import-list/directives/import-list-status-template.directive.ts
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
Labels: critical

#1153 Fixes missing service worker support
  client/angular.json
  client/ngsw-config.json
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/index.html
  client/src/manifest.json
  client/src/manifest.webmanifest
Labels: high

#1179 Several fixes
  client/src/app/gateways/notify.service.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/modules/site-wrapper/site-wrapper.module.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/motion-multiselect.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect-service.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/comments.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-extension-field/motion-extension-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
Labels: high

#1012 Bugfix/diff line numbers should refer to whole lines
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-change-recommendation-controller.service/motion-change-recommendation-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/motion-change-recommendation-dialog/components/motion-content-change-recommendation-dialog/motion-content-change-recommendation-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
Labels: high

#1189 Several fixes (4.)
  client/src/app/gateways/repositories/agenda/agenda-item-repository.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message/chat-group-detail-message.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/services/meeting-controller.service.ts
  client/src/app/site/pages/organization/config/model-subscription.ts
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list-main/account-list-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/committee-detail-routing.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/components/committee-detail/committee-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/committee-detail-meeting-routing.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/committee-detail-meeting.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.scss
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.spec.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-main/components/dashboard-main/dashboard-main.component.ts
Labels: high

#1196 Fixed non-loading committee managers
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
Labels: high
