Repository OpenSlides/openslides-client, pull requests merged in 2022-01, with the labels that each got.

#711 Add Statistics for organizations
  client/src/app/core/core-services/member.service.ts
  client/src/app/core/core-services/organization.service.ts
  client/src/app/core/core-services/presenter.service.ts
  client/src/app/site/common/components/info/info.component.html
  client/src/app/site/common/components/info/info.component.ts
  client/src/app/site/common/components/organization-statistics/organization-statistics.component.html
  client/src/app/site/common/components/organization-statistics/organization-statistics.component.scss
  client/src/app/site/common/components/organization-statistics/organization-statistics.component.spec.ts
  client/src/app/site/common/components/organization-statistics/organization-statistics.component.ts
  client/src/app/site/common/os-common.module.ts
Labels: feature

#709 Automatically forward users to a unique meeting
  client/src/app/core/core-services/auth-guard.service.ts
  client/src/app/core/core-services/operator.service.ts
  client/src/app/core/definitions/base-menu-entry.ts
  client/src/app/core/repositories/relations.ts
  client/src/app/shared/models/users/user.ts
  client/src/app/site/common/common.config.ts
  client/src/app/site/site.component.html
  client/src/app/site/site.component.ts
  client/src/app/site/users/models/view-user.ts
Labels: feature

#725 Added LABEL to production Dockerfile
  Dockerfile
Labels: documentation

#740 Show recommendation on projector
  client/package.json
  client/src/app/slides/motion/motion-slide.component.html
  client/src/app/slides/motion/motion-slide.component.ts
Labels: bug

#718 Update jitsi iframe api
  client/src/app/site/interaction/services/rtc.service.ts
  client/src/assets/jitsi/external_api.js
Labels: dependencies

#731 Resort settings, set presence update gen scripts
  client/cli/generate-permissions.ts
  client/cli/generate-settings-defaults.ts
  client/src/app/core/core-services/permission-children.ts
  client/src/app/core/core-services/permission.ts
  client/src/app/core/ui-services/user.service.ts
  client/src/app/shared/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/polls/components/base-poll-detail.component.ts
  client/src/app/site/users/components/user-detail/user-detail.component.html
  client/src/app/site/users/components/user-list/user-list.component.html
  client/src/app/site/users/components/user-list/user-list.component.ts
Labels: feature, clean up

#743 Use moment to format PDF start time
  client/src/app/core/pdf-services/pdf-document.service.ts
  client/src/app/management/components/committee-list/committee-list.component.ts
  client/src/app/shared/components/change-password/change-password.component.ts
  client/src/app/shared/components/ee/ee.component.html
  client/src/app/shared/components/ee/ee.component.scss
  client/src/app/shared/components/ee/ee.component.ts
  client/src/app/shared/components/not-found/not-found.component.html
  client/src/app/shared/shared.module.ts
Labels: bug

#745 Adjust height of motion comments in detail view
  client/src/app/shared/components/meta-text-block/meta-text-block.component.scss
  client/src/app/shared/components/meta-text-block/meta-text-block.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-comment/motion-comment.component.scss
  client/src/app/site/motions/modules/motion-detail/components/motion-comment/motion-comment.component.ts
Labels: bug

#746 Show start and end time in pdf doc header
  client/src/app/core/pdf-services/pdf-document.service.spec.ts
  client/src/app/core/pdf-services/pdf-document.service.ts
  client/src/app/core/repositories/base-repository.ts
Labels: bug

#747 Add close LOS to multi select in agenda and motions
  client/src/app/core/repositories/agenda/list-of-speakers-repository.service.ts
  client/src/app/site/agenda/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/agenda/components/agenda-item-list/agenda-item-list.component.ts
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/cinema/components/cinema/cinema.component.ts
  client/src/app/site/motions/modules/shared-motion/motion-multiselect-actions/motion-multiselect-actions.component.html
  client/src/app/site/motions/services/motion-multiselect.service.ts
Labels: feature

#762 Fix: Permissions of groups
  client/src/app/site/users/models/view-group.ts
Labels: bug, high

#761 Fixes: polls... (#754)
  client/src/app/site/polls/components/base-poll-meta-information.component.ts
  client/src/app/site/polls/components/poll-form/poll-form.component.html
  client/src/app/site/polls/components/poll-form/poll-form.component.ts
  client/src/app/site/polls/services/poll.service.ts
Labels: high

#714 Improves importing of accounts
  client/src/app/core/core-services/key-transforms.ts
  client/src/app/core/core-services/model-request-builder.service.ts
  client/src/app/core/core-services/operator.service.ts
  client/src/app/core/core-services/presenter.service.ts
  client/src/app/core/core-services/presenters/search-users-by-name-or-email-presenter.service.ts
  client/src/app/core/repositories/users/group-repository.service.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/core/ui-services/base-import.service.ts
  client/src/app/management/components/committee-import-list/committee-import-list.component.html
  client/src/app/management/components/member-import-list/member-import-list.component.html
  client/src/app/management/components/member-import-list/member-import-list.component.ts
  client/src/app/management/components/member-list/member-list.component.ts
  client/src/app/management/services/committee-import.service.ts
  client/src/app/management/services/member-import.service.ts
  client/src/app/shared/components/import-list-view/import-list-first-tab.directive.ts
  client/src/app/shared/components/import-list-view/import-list-last-tab.directive.ts
  client/src/app/shared/components/import-list-view/import-list-view-first-tab.directive.ts
  client/src/app/shared/components/import-list-view/import-list-view-last-tab.directive.ts
  client/src/app/shared/components/import-list-view/import-list-view-status-template.directive.ts
  client/src/app/shared/components/import-list-view/import-list-view.component.html
  client/src/app/shared/components/import-list-view/import-list-view.component.scss
  client/src/app/shared/components/import-list-view/import-list-view.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/utils/import/base-import-handler.ts
  client/src/app/shared/utils/import/base-main-import-handler.ts
  client/src/app/shared/utils/import/import-handler-config.ts
  client/src/app/shared/utils/import/import-model.ts
  client/src/app/shared/utils/import/import-step-descriptor.ts
  client/src/app/shared/utils/import/static-before-import-handler.ts
  client/src/app/shared/utils/import/static-main-import-handler.ts
  client/src/app/site/base/components/base-import-list.component.ts
  client/src/app/site/login/components/login-mask/login-mask.component.html
  client/src/app/site/login/components/login-mask/login-mask.component.ts
  client/src/app/site/motions/modules/motion-import/motion-import-list.component.html
  client/src/app/site/motions/modules/statute-paragraph/components/statute-paragraph-import-list/statute-paragraph-import-list.component.html
  client/src/app/site/motions/services/motion-import.service.ts
  client/src/app/site/motions/services/statute-import.service.ts
  client/src/app/site/topics/components/topic-detail/topic-detail.component.html
  client/src/app/site/topics/components/topic-import-list/topic-import-list.component.html
  client/src/app/site/topics/services/topic-import.service.ts
  client/src/app/site/users/base/base-user-import-list.component.ts
  client/src/app/site/users/base/base-user.constants.ts
  client/src/app/site/users/components/user-import/user-import-list.component.html
  client/src/app/site/users/components/user-import/user-import-list.component.ts
  client/src/app/site/users/import/group-import-helper.ts
  client/src/app/site/users/services/user-import.service.ts
  client/src/app/site/users/users.constants.ts
Labels: feature, high
