Repository OpenSlides/openslides-client, pull requests merged in 2022-12, with the labels that each got.

#1840 Fix pdf export Header text.
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: bug

#1824 Fix extension field handling
  client/package.json
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/base/base-motion-slide.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
Labels: bug, high

#1834 handle meeting not found error
  client/src/app/site/modules/global-spinner/services/spinner.service.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
  client/src/app/site/services/model-request.service.ts
  client/src/app/site/services/operator.service.ts
Labels: bug

#1809 dont display "no meetings available" before first autoupdate
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/dashboard-detail.module.ts
  client/src/app/site/services/model-request.service.ts
Labels: needs discussion, optimization

#1542 Removed settings entry for anonymous guest user.
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: bug

#1703 Extend history to users and assignments
  client/src/app/gateways/presenter/presenter.ts
  client/src/app/gateways/presenter/search-deleted-models-presenter.service.spec.ts
  client/src/app/gateways/presenter/search-deleted-models-presenter.service.ts
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.scss
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/history/history.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/participant-detail.module.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: feature, needs discussion

#1857 Add parameter to exclude ids from search in base search selector.
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#1761 Use playwright instead of cypress
  .github/workflows/build.yml
  Makefile
  client/src/app/gateways/http-stream/http-stream.service.ts
  client/src/app/gateways/http-stream/http-stream.ts
  client/tests/.gitignore
  client/tests/Dockerfile.test
  client/tests/docker-compose.test.yml
  client/tests/integration/Dockerfile.test
  client/tests/integration/Readme.md
  client/tests/integration/client-load.spec.ts
  client/tests/integration/cypress.config.js
  client/tests/integration/cypress/fixtures/example.json
  client/tests/integration/cypress/integration/client-load.spec.ts
  client/tests/integration/cypress/integration/guards.spec.ts
  client/tests/integration/cypress/integration/login.spec.ts
  client/tests/integration/cypress/integration/meeting/agenda.spec.ts
  client/tests/integration/cypress/integration/meeting/home.spec.ts
  client/tests/integration/cypress/integration/meeting/motion/history.spec.ts
  client/tests/integration/cypress/integration/organization/account.spec.ts
  client/tests/integration/cypress/integration/organization/committee.spec.ts
  client/tests/integration/cypress/support/commands.ts
  client/tests/integration/cypress/support/index.ts
  client/tests/integration/cypress/support/setup.ts
  client/tests/integration/cypress/tsconfig.json
  client/tests/integration/docker-compose.test.yml
  client/tests/integration/guards.spec.ts
  client/tests/integration/helpers/auth.ts
  client/tests/integration/helpers/request.ts
  client/tests/integration/login.spec.ts
  client/tests/integration/meeting/agenda.spec.ts
  client/tests/integration/meeting/home.spec.ts
  client/tests/integration/meeting/motion/history.spec.ts
  client/tests/integration/organization/account.spec.ts
  client/tests/integration/organization/committee.spec.ts
  client/tests/integration/package-lock.json
  client/tests/integration/package.json
  client/tests/integration/page-objects/components/list-component.ts
  client/tests/integration/page-objects/meeting/home/detail.ts
  client/tests/integration/page-objects/meeting/home/edit.ts
  client/tests/integration/page-objects/meeting/motion/detail.ts
  client/tests/integration/resource-config.js
  client/tests/package-lock.json
  client/tests/package.json
  client/tests/playwright.config.ts
Labels: tests

#1825 sequential number service performance
  client/src/app/gateways/repositories/assignments/assignment-repository.service/assignment-repository.service.ts
  client/src/app/gateways/repositories/list-of-speakers/list-of-speakers-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-workflow-repository.service/motion-workflow-repository.service.ts
  client/src/app/gateways/repositories/polls/poll-repository.service/poll-repository.service.ts
  client/src/app/gateways/repositories/projectors/projector-repository.service.ts
  client/src/app/gateways/repositories/topics/topic-repository.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/detail-view/detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/pages/meetings/services/sequential-number-mapping.service.ts
Labels: needs discussion

#1845 fix autoupdate fallback when logged in
  client/src/app/openslides-main-module/services/shared-worker.service.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: bug

#1836 fix stored filters overwritten in BaseFilterListService
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: bug, delete test instance

#1875 add tests to prettify-check
  client/package.json
  client/tests/integration/client-load.spec.ts
  client/tests/integration/guards.spec.ts
  client/tests/integration/login.spec.ts
  client/tests/integration/meeting/agenda.spec.ts
  client/tests/integration/meeting/motion/history.spec.ts
  client/tests/integration/page-objects/meeting/motion/detail.ts
  client/tests/playwright.config.ts
Labels: clean up
