Repository OpenSlides/openslides-client, pull requests merged in 2022-07, with the labels that each got.

#1358 Only call forwarding presenter with the right permissions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, high, affected view: motion

#1356 Fix multiple errors with the mediafile list
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/pages/meetings/services/meeting-collection-mapper.service.ts
Labels: bug, high, affected view: mediafile

#1351 Extracted new translations
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/assets/i18n/de.json
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: translation

#1349 Fixed agenda open items filter
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
Labels: affected view: agenda item list

#1361 Fix logout on auth error
  client/src/app/gateways/http-stream/http-stream.service.ts
Labels: bug, high

#1357 Fix mediafile upload form
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/components/attachment-control/attachment-control.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.ts
  client/src/app/ui/modules/media-upload-content/components/media-upload-content/media-upload-content.component.html
  client/src/app/ui/modules/media-upload-content/components/media-upload-content/media-upload-content.component.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug, high, affected view: mediafile

#1367 Fix participants can not enter Jitsi
  client/angular.json
  client/src/app/site/pages/meetings/pages/interaction/modules/action-bar/action-bar.module.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/interaction-container.module.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug

#1369 Implemented AddToMeetingsComponent
  client/src/app/gateways/repositories/users/user-action.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail-routing.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.spec.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/services/user-controller.service.ts
  client/src/app/ui/modules/choice-dialog/components/choice-dialog/choice-dialog.component.html
  client/src/app/ui/modules/choice-dialog/components/choice-dialog/choice-dialog.component.scss
Labels: feature, affected view: account

#1294 Fix style of recommendation in the projector of the motion block
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.scss
Labels: bug

#1405 fix high cpu usage caused by search selectors
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, high, needs investigation, difficulty: hard

#1393 Fix counting of users (again)
  client/src/app/gateways/notify.service.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.ts
Labels: bug, high

#1416 implement base list currentOffset and scrollTo
  client/src/app/ui/modules/list/base/base-list.component.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug, high

#1395 Fix & beautify workflow detail view
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/assets/styles/tables.scss
Labels: bug, affected view: motion

#1445 Fix workflow state restriction selection and make run-cleanup
  Makefile
  README.md
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
Labels: bug, high, affected view: motion

#1451 Don't try to warn others users via ICC when creating a new motion
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/directives/listen-editing/listen-editing.directive.ts
Labels: bug
