Repository OpenSlides/openslides-client, pull requests merged in 2022-06, with the labels that each got.

#1202 Participant import now writes into meeting-specific fields
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-csv-export.service/participant-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/services/account-import.service/account-import.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/account-export.service/account-export.service.ts
Labels: high

#1205 Some fixes
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/committee-import.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/components/committee-import-list/committee-import-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/services/committee-import.service/committee-import.service.ts
  client/src/app/site/services/import-service-collector.service.ts
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/pipes/pipes.module.ts
  client/src/app/ui/pipes/to-array/to-array.pipe.spec.ts
  client/src/app/ui/pipes/to-array/to-array.pipe.ts
Labels: high

#1211 Fix in pdf export logo in header and footer
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: bug

#1220 Fix overflow of diffs in the amendment list
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.scss
Labels: bug

#1228 Signs out after cookies are removed (#1223)
  client/src/app/gateways/http-stream/http-stream.service.ts
  client/src/app/gateways/http-stream/http-stream.ts
Labels: critical

#1230 Re-enables a pre-filtered motion-/amendment-list (#956)
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/amendment-controller.service/amendment-controller.service.ts
Labels: critical

#1235 Fixes the merging of amendments into a lead motion (#1222)
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
Labels: critical

#1250 Fixes for projections
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/services/projector-edit-dialog.service.ts
Labels: high

#1248 Some fixes
  client/src/app/gateways/repositories/motions/personal-note-repository.service/personal-note-repository.service.ts
  client/src/app/site/base/base-list-view.component.ts
  client/src/app/site/base/base.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/personal-notes/services/personal-note-controller.service/personal-note-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/personal-notes/view-models/has-personal-note.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/base/base-motion-detail-meta.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-comment/motion-comment.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-comment/motion-comment.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-personal-note/motion-personal-note.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-personal-note/motion-personal-note.component.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/app/ui/modules/list/services/list-search.service.ts
Labels: high

#1265 Fixed a few urgent voting bugs
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.scss
Labels: high

#1263 Fixed user creation and superadmins calendar
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
  client/src/app/ui/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: high

#1286 Optimized projector list subscription
  client/src/app/gateways/repositories/projections/projection-repository.service.ts
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/meetings/pages/projectors/config/model-subscription.ts
Labels: high

#1280 Removed TypeError and created ErrorMapService
  client/src/app/gateways/error-map.service.spec.ts
  client/src/app/gateways/error-map.service.ts
  client/src/app/gateways/http.service.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/services/auth.service.ts
Labels: high

#1282 Changed PollSlideComponent to show topic polls
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/poll-slide.module.ts
Labels: high

#1291 Optimized setup model autoupdate subscription
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
Labels: high

#1277 Implemented default projector selection
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/services/projector-controller.service.ts
Labels: high

#1298 Fix strange numbers in the assignment poll detail view
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
Labels: bug, help wanted

#1317 Repaired category detail sort
  client/src/app/site/pages/meetings/pages/motions/modules/categories/view-models/view-motion-category.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.ts
Labels: high

#1338 Made move file dialog function correctly
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
Labels: high, affected view: mediafile

#1324 Fixed import of meeting admins for committee import
  client/src/app/infrastructure/utils/import/base-main-import-handler.ts
  client/src/app/infrastructure/utils/import/static-main-import-handler.ts
  client/src/app/infrastructure/utils/import/users/user-import-helper.ts
Labels: bug, high, affected view: committee

#1347 Fixed bug with linenumbering in the motion final version
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: high
