Repository OpenSlides/openslides-client, pull requests merged in 2022-08, with the labels that each got.

#1440 Fix the pdf export from the motion Diff version
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug, delete test instance

#1463 Various UI fixes
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.scss
Labels: bug

#1453 fix scroll position restore if scrollViewport not available yet
  client/src/app/site/base/base-list-view.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.ts
  client/src/app/ui/modules/list/base/base-list.component.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#1455 Different problems with projector
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
Labels: bug, high

#1460 fix motion hyperlink not clickable
  client/src/app/site/pages/meetings/pages/motions/styles/motion-common-styles.scss
Labels: bug, affected view: motion

#1448 Add 'reset cache' and 'check database' buttons
  client/src/app/gateways/presenter/check-database-presenter.service.spec.ts
  client/src/app/gateways/presenter/check-database-presenter.service.ts
  client/src/app/gateways/presenter/presenter.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.html
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.scss
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.ts
  client/src/app/site/services/lifecycle.service.ts
Labels: feature, waiting for backend, test instance active

#1471 display snackbar warning if motion is already edited by someone else
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/directives/listen-editing/listen-editing.directive.ts
Labels: bug

#1456 fix lang from local storage sometimes not set
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
Labels: bug

#883 Can set voteweight to null
  client/src/app/domain/models/users/user.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
Labels: bug, affected view: polls, delete test instance

#1435 Made BaseFilterListService parse loaded filters into new ones
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: delete test instance

#1466 fix agenda tags not loaded
  client/src/app/site/pages/meetings/pages/agenda/config/model-subscription.ts
Labels: bug, affected view: agenda item list, test instance active, delete test instance

#1461 replace deprecated apis from SlideManagerService
  client/src/app/site/pages/meetings/modules/projector/components/slide-container/slide-container.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/services/slide-manager.service.ts
Labels: bug, clean up, difficulty: normal

#1515 Hotfix: Account list subscribes to first 10000 users
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
Labels: high, affected view: account

#1475 Fix sorting by calllist
  client/src/app/domain/models/motions/motion.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
Labels: bug, high, affected view: motion

#1508 Add support for nanocosmos streams from os3
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.scss
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
Labels: bug, need test instance

#1507 Trim `{first_,last_,user}name` before import
  client/src/app/site/base/base-user-import.service.ts
Labels: bug, good first issue, difficulty: easy

#1517 update dates after language change
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/ui/pipes/localized-date/localized-date.pipe.ts
  client/src/app/ui/pipes/time/time.pipe.ts
Labels: bug, low

#1516 agenda items multiselect tag edit
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/agenda-item-list.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-multiselect.service/agenda-item-multiselect.service.spec.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-multiselect.service/agenda-item-multiselect.service.ts
Labels: feature, affected view: agenda item list

#1511 Changed set state to now open snackbar instead of throwing different …
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug, affected view: motion

#1505 fix agenda tags back button
  client/src/app/site/pages/meetings/pages/motions/pages/tags/components/tag-list/tag-list.component.html
Labels: bug

#1503 display error if min votes is larger than amount candidates
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-dialog.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-dialog/assignment-poll-dialog.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-dialog/assignment-poll-dialog.component.ts
Labels: bug

#1485 fix amendment changes not displayed in parent motion diff view
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
Labels: bug, high

#1486 Fixed that vote delegations couldn't be undone through the proxy field
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
Labels: test instance active, delete test instance

#1518 beautify vote entitled users
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
Labels: feature

#1490 hide file list indicator and info column on mobile
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
Labels: bug, high

#1494 Fix disabling of buttons in motion export
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
Labels: bug

#1489 Now shows meeting time in forwarding dialog
  client/src/app/gateways/presenter/get-forwarding-meetings-presenter.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/motion-forward-dialog.module.ts
Labels: feature, need test instance

#1499 fix ammendment text import
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/services/motion-import.service.ts
Labels: bug, test instance active, delete test instance

#1496 bullet point ammendment fix
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
Labels: bug, high, test instance active, delete test instance

#1477 General bug fixes and improvements for user imports
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/domain/models/users/user.export.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/base/base-user-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-csv-export.service/participant-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participants-export-example.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug, high

#1497 Validation of meeting time
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/committee-detail-meeting.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: needs discussion

#1364 Filtered empty users out of account list
  client/src/app/domain/models/users/user.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/account-common.service/account-common.service.spec.ts
  client/src/app/site/pages/organization/pages/accounts/services/account-common.service/account-common.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/account-common.service/index.ts
  client/src/app/site/services/user-controller.service.ts
  client/src/app/site/services/view-model-store-update.service.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: high, test instance active, delete test instance
