Repository OpenSlides/openslides-client, pull requests merged in 2022-11, with the labels that each got.

#1766 fix election export with deleted candidate
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-pdf.service.ts
Labels: bug, need test instance

#1764 remove participant default group when adding groups via multiselect
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug, affected view: participant

#1772 fix filter menu change detection on filter update
  client/src/app/ui/modules/list/components/filter-menu/filter-menu.component.ts
Labels: bug, high

#1780 Clean up the getVotingPermissionError function
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/voting.service/voting.service.ts
Labels: clean up

#1783 Motion detail: add summary of changes outline
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/assets/styles/global-components-style.scss
Labels: low, affected view: motion

#1782 move motion poll add button below status
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-add-poll-button/motion-add-poll-button.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-add-poll-button/motion-add-poll-button.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-add-poll-button/motion-add-poll-button.component.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-add-poll-button/motion-add-poll-button.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-polls/motion-manage-polls.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-polls/motion-manage-polls.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
Labels: affected view: motion

#1751 meeting edit bugs
  client/src/app/site/pages/organization/modules/account-search-selector/components/account-search-selector/account-search-selector.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/components/committee-detail/committee-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#1781 fix mediafile scrolling table after hide
  client/src/app/ui/modules/file-upload/components/file-upload/file-upload.component.html
  client/src/app/ui/modules/file-upload/components/file-upload/file-upload.component.ts
Labels: bug, high

#1770 add participant form hints
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-password-form/user-password-form.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/participant-detail-manage.module.ts
Labels: feature

#1720 recheck current route guards on permission change
  client/src/app/site/guards/auth.guard.ts
  client/src/app/site/guards/permission.guard.ts
  client/src/app/site/pages/error/components/error-main/error-main.component.ts
  client/src/app/site/pages/meetings/meetings-routing.module.ts
  client/src/app/site/services/openslides-router.service.ts
  client/src/app/site/services/reroute.service.ts
Labels: bug, high, delete test instance

#1423 Implemented client-side action worker logic
  client/src/app/domain/models/action-worker/action-worker.ts
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.spec.ts
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.ts
  client/src/app/gateways/http.service.ts
  client/src/app/gateways/repositories/action-worker/action-worker-repository.service.spec.ts
  client/src/app/gateways/repositories/action-worker/action-worker-repository.service.ts
  client/src/app/gateways/repositories/action-worker/action-worker.config.ts
  client/src/app/gateways/repositories/action-worker/view-action-worker.ts
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/openslides-main-module/services/app-load.service.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/index.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.html
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.scss
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.spec.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.ts
  client/src/app/site/modules/wait-for-action-dialog/definitions/index.ts
  client/src/app/site/modules/wait-for-action-dialog/index.ts
  client/src/app/site/modules/wait-for-action-dialog/services/index.ts
  client/src/app/site/modules/wait-for-action-dialog/services/wait-for-action-dialog.service.spec.ts
  client/src/app/site/modules/wait-for-action-dialog/services/wait-for-action-dialog.service.ts
  client/src/app/site/modules/wait-for-action-dialog/wait-for-action-dialog.module.ts
Labels: feature

#1785 Projector can now show pdfs again
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/assets/pdfworker/pdf.worker.min.js
Labels: bug, high, affected view: projector, test instance active

#1790 fix broken meeting after resignin with different permissions
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-stream.ts
Labels: bug

#1787 Motion workflow allow motion submitter to set the status "withdrawn"
  client/src/app/domain/models/motions/motion-state.ts
  client/src/app/gateways/repositories/motions/motion-state-repository.service/motion-state-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/pages/motions/modules/states/view-models/view-motion-state.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
Labels: feature, high

#1797 Pdf projection: Can now switch pages and scroll again
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/presentation-controls/presentation-controls.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: bug, affected view: projector

#1800 reset collections on logout
  client/src/app/site/pages/meetings/pages/mediafiles/services/mediafile-controller.service.ts
  client/src/app/site/services/auth.service.ts
Labels: bug

#1805 hide list of speakers overlay if empty
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.html
Labels: bug

#1807 fix filter menu entries collapsing on autoupdate
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: bug, high

#1793 display organization description on calendar
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
Labels: feature

#1798 Stopped client from completely blocking user deletion for meeting admins
  client/src/app/gateways/presenter/get-user-related-models-presenter.service.ts
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.html
  client/src/app/site/modules/user-components/services/user-delete-dialog.service.ts
Labels: bug, affected view: participant

#1817 enable history permission edit
  client/src/app/domain/definitions/permission.config.ts
Labels: bug

#1812 fix accountmanager cannot access organization
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.ts
  client/src/app/site/services/auth-check.service.ts
  client/src/app/site/services/operator.service.ts
Labels: bug, high

#1820 fix referenced motions on projector
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/base/base-motion-slide.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
Labels: bug, high

#1828 check cdk viewport size on scrolling table refresh
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug, high

#1835 fix can not save participant about me
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug

#1814 fix motion agenda assignment via multiselect
  client/src/app/gateways/repositories/agenda/agenda-item-repository.service.ts
Labels: bug, high
