Repository OpenSlides/openslides-client, pull requests merged in 2022-02, with the labels that each got.

#795 Maps the ids of a stream to the ids of a stream-handler
  client/src/app/core/core-services/autoupdate.service.ts
  client/src/app/core/core-services/communication-manager.service.ts
  client/src/app/core/core-services/http-stream.ts
  client/src/app/core/core-services/notify.service.ts
Labels: clean up, client

#806 Limit size of error messages in snackBar (#805)
  client/src/app/core/ui-services/error.service.ts
  client/src/app/shared/utils/previewStrings.ts
Labels: client

#828 Some improvements
  client/src/app/core/actions/user-action.ts
  client/src/app/core/repositories/agenda/speaker-repository.service.ts
  client/src/app/core/repositories/polls/poll-repository.service.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/core/ui-services/user.service.ts
  client/src/app/core/ui-services/voting.service.ts
  client/src/app/management/components/member-edit/member-edit.component.html
  client/src/app/management/components/member-list/member-list.component.html
  client/src/app/shared/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/shared/components/user-detail-view/user-detail-view.component.html
  client/src/app/shared/components/user-detail-view/user-detail-view.component.scss
  client/src/app/shared/components/user-detail-view/user-detail-view.component.ts
  client/src/app/shared/models/poll/view-poll.ts
  client/src/app/shared/models/users/user.ts
  client/src/app/site/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/cinema/components/cinema/cinema.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-vote/motion-poll-vote.component.html
  client/src/app/site/polls/components/base-poll-vote.component.ts
  client/src/app/site/users/components/user-detail/user-detail.component.html
  client/src/app/site/users/components/user-list/user-list.component.html
  client/src/assets/styles/default-classes.scss
Labels: high

#819 Spaces group views
  client/src/app/site/users/components/user-detail/user-detail.component.html
  client/src/app/site/users/components/user-list/user-list.component.html
  client/src/assets/styles/global-components-style.scss
Labels: bug

#842 Some improvements to archived meetings and other
  client/src/app/core/core-services/active-meeting-id.service.ts
  client/src/app/core/core-services/autoupdate.service.ts
  client/src/app/core/core-services/operator.service.ts
  client/src/app/core/repositories/assignments/assignment-candidate-repository.service.ts
  client/src/app/core/repositories/management/meeting-repository.service.ts
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/core/repositories/relations.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/core/ui-services/amendment.service.ts
  client/src/app/core/ui-services/voting.service.ts
  client/src/app/management/components/meeting-edit/meeting-edit.component.ts
  client/src/app/management/components/meeting-preview/meeting-preview.component.html
  client/src/app/management/components/meeting-preview/meeting-preview.component.ts
  client/src/app/management/models/view-meeting.ts
  client/src/app/management/models/view-organization.ts
  client/src/app/shared/components/search-selector/base-search-value-selector/base-search-value-selector.component.ts
  client/src/app/shared/models/event-management/meeting.ts
  client/src/app/shared/models/event-management/organization.ts
  client/src/app/site/users/components/user-detail/user-detail.component.ts
Labels: high

#871 Quickfix: Get updates for motion only once
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/site/cinema/components/cinema/cinema.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/projector/services/current-list-of-speakers.service.ts
Labels: high

#887 date (#808)
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
Labels: bug, good first issue
