Repository OpenSlides/openslides-client, pull requests merged in 2023-04, with the labels that each got.

#2158 Fixed motion list default sorting
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
Labels: bug, high

#2168 Fixed LoS presence restriction
  client/src/app/gateways/repositories/users/user-repository.service.ts
Labels: bug, high

#2169 fix vote delegations not working
  client/src/app/site/services/operator.service.ts
Labels: bug, critical

#2170 Fixed broken chip deselection in search selectors
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug, high

#2172 fix poll tabledata read from method
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.ts
Labels: bug, high

#2174 fix single votes and entitled users tables
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.ts
  client/src/app/ui/modules/list/components/list/list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.html
Labels: bug, high

#2176 fix topic numbers not displayed in list
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
Labels: bug

#2180 fix orga account detail missing field
  client/src/app/site/pages/organization/pages/accounts/accounts.subscription.ts
Labels: bug

#2191 Restricted links from history list
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.scss
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
Labels: high, clean up

#2188 Stopped global headbar from being scrolled away
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.scss
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.html
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.scss
  client/src/app/site/pages/organization/modules/navigation/organization-navigation-wrapper/organization-navigation-wrapper.component.html
  client/src/app/site/pages/organization/modules/navigation/organization-navigation-wrapper/organization-navigation-wrapper.component.scss
  client/src/styles.scss
Labels: bug

#2184 disable tinymce blockquoute
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/detail-view/detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/definitions/tinymce-config.ts
Labels: bug

#2175 Fixed multiple scrolling- and overflow-related UI bugs
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.scss
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.scss
Labels: bug, ui

#2162 Implement custom global colors
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/poll/poll-constants.ts
  client/src/app/domain/models/theme/theme.ts
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.html
  client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
  client/src/app/site/pages/organization/pages/designs/modules/theme-builder-dialog/components/theme-builder-dialog.component.html
  client/src/app/site/pages/organization/pages/designs/modules/theme-builder-dialog/components/theme-builder-dialog.component.ts
  client/src/app/site/services/color.service.ts
  client/src/app/site/services/theme.service.ts
  client/src/app/ui/modules/color-form-field/components/color-form-field/color-form-field.component.ts
  client/src/assets/styles/global-components-style.scss
  client/src/assets/styles/poll-colors.scss
Labels: feature

#2194 fix mediafiles not displayed in autopilot
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
Labels: bug, high

#2186 Hotfix for participant import
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
Labels: bug

#2177 Fixed vote delegation removal
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug

#2199 Added saving hint dialog for group-list
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/agenda-sort-routing.module.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list-sort/category-list-sort.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/motion-call-list-routing.module.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/groups-routing.module.ts
  client/src/app/ui/base/base-sort-tree-view-component.ts
Labels: enhancement

#2187 Added functionality for clear motion block choice
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#2181 Default group ids are now loaded for topic polls
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature

#2200 fix participant export default password not loaded
  client/src/app/gateways/repositories/users/user-repository.service.ts
Labels: bug

#2197 Fixed remaining poll bugs
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.html
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.ts
Labels: bug, ui

#2202 Made motion detail recognize if the text is loaded
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-paragraphbased-amendment/motion-paragraphbased-amendment.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
Labels: bug, enhancement

#2163 moved and added dialog for "is active" button
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.ts
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/theme-list.module.ts
  client/src/app/ui/modules/prompt-checkbox/components/index.ts
  client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.html
  client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.scss
  client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.spec.ts
  client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.ts
  client/src/app/ui/modules/prompt-checkbox/index.ts
  client/src/app/ui/modules/prompt-checkbox/prompt-checkbox.module.ts
  client/src/styles.scss
Labels: good first issue, enhancement

#2215 Amendment list uses amendment workflow stati in filter
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
Labels: bug, high

#2192 fix livestream sometimes not displayed
  client/src/app/site/pages/meetings/pages/interaction/services/stream.service.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
Labels: bug

#2223 Fixed projection dialog bug
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/services/projection-dialog.service.ts
Labels: bug, high

#2195 Fixed meeting create button in safari
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, high, Safari/iOS

#2201 Invite to call now only invites selected user
  client/src/app/gateways/notify.service.ts
  client/src/app/site/pages/meetings/pages/interaction/services/interaction-receive.service.ts
  client/src/app/site/pages/meetings/pages/interaction/services/interaction.service.ts
Labels: bug, high

#2229 Fixed bug where amendment loading bar wouldn't vanish
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/model-request.service.ts
Labels: bug

#2230 Fixed voting banner scrolling bug
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.scss
  client/src/app/site/pages/organization/modules/navigation/organization-navigation-wrapper/organization-navigation-wrapper.component.scss
Labels: bug, ui

#2205 autopilot subscribe polls only if neccessary
  client/src/app/domain/models/topics/topic.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-main/autopilot-main.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
Labels: bug

#2211 Removed unnecessary sort functions
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list/category-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: clean up

#2072 Remove translation of user-filled data
  client/cli/get-available-languages.ts
  client/package.json
  client/src/app/domain/definitions/languages.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/repositories/groups/group-repository.service.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/modules/motion-list-info-dialog/components/motion-list-info-dialog/motion-list-info-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/services/workflow-export.service/workflow-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/amendment-list-pdf.service/amendment-list-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-export.service/motion-pdf-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-pdf.service/participant-pdf.service.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/services/group-controller.service.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/countdown-controls/countdown-controls.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/committee-detail-meeting.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/settings-detail.module.ts
  client/src/assets/i18n/cs.po
  client/src/assets/i18n/de.po
  client/src/assets/i18n/es.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/ru.po
  client/src/assets/i18n/template-en.pot
Labels: feature, high, translation
