Repository OpenSlides/openslides-client, pull requests merged in 2023-12, with the labels that each got.

#2976 Align Multiselect Text centered
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/components/assignment-list/assignment-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-list/workflow-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/organization-tags/pages/organization-tag-list/components/organization-tag-list/organization-tag-list.component.html
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.html
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.scss
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.ts
  client/src/styles.scss
Labels: bug

#3069 Make router service consider ongoing navigation before login navigation
  client/src/app/site/services/openslides-router.service.ts
Labels: bug, high

#3065 Activate Angular accessibility guidelines
  client/.eslintrc.js
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/ui/modules/input/components/rounded-input/rounded-input.component.html
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.html
Labels: enhancement

#3010 Allow more refined Re-add button behaviour
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug

#3072 Fix autoupdate handleError error type check
  client/src/app/gateways/http-stream/http-stream.service.ts
  client/src/app/gateways/http-stream/http-stream.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/worker/autoupdate/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate/autoupdate-subscription.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: bug

#3063 Fix background for archived meetings
  client/src/assets/styles/utils.scss
Labels: bug

#3044 Implement participant import via backend
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/gateways/repositories/users/user-action.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/base/base-user-import-list.component.ts
  client/src/app/site/base/base-user-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-csv-export.service/participant-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
Labels: feature

#3089 Fix start line number label
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.html
Labels: translation

#3092 Add translation maker for Errormsgs
  client/src/app/gateways/error-mapping/error-map.service.ts
  client/src/app/site/base/base.component.ts
  client/src/assets/i18n/template-en.pot
Labels: translation

#3060 Disable save button and change warning for too small vote_weight
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
Labels: bug

#3082 Fix amendment list title if no parent motion
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
Labels: bug

#3078 Add tests to the view model store service
  client/src/app/site/services/view-model-store.service.spec.ts
Labels: tests

#3064 Global search improvements
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.ts
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/services/global-search/definitions.ts
  client/src/app/site/services/global-search/global-search.service.ts
  client/src/app/ui/modules/input/components/rounded-input/rounded-input.component.html
  client/src/app/ui/modules/input/components/rounded-input/rounded-input.component.ts
Labels: enhancement

#3096 Disable save button with space in username
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
Labels: bug

#3095 Logout after password change
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-password/account-password.component.ts
  client/src/app/site/services/auth.service.ts
Labels: bug

#3094 Fix import error handling and cleanup participant import icons
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/definitions/backend-import-preview.ts
Labels: bug, ui

#3102 Imports: Make sure file can be re-added after import fails with error
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
Labels: bug

#3075 Add tests to lifecycle service
  client/src/app/site/services/lifecycle.service.spec.ts
Labels: tests

#3011 Add a structure level list component and basic stuff for structure level
  client/cli/generate-models.ts
  client/src/app/domain/fieldsets/user.ts
  client/src/app/domain/models/agenda/agenda-item.ts
  client/src/app/domain/models/list-of-speakers/list-of-speakers.ts
  client/src/app/domain/models/meeting-users/meeting-user.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/speakers/speaker.ts
  client/src/app/domain/models/structure-levels/index.ts
  client/src/app/domain/models/structure-levels/structure-level-list-of-speakers.ts
  client/src/app/domain/models/structure-levels/structure-level.ts
  client/src/app/domain/models/users/user.export.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/gateways/repositories/structure-levels/index.ts
  client/src/app/gateways/repositories/structure-levels/structure-level-repository.service.spec.ts
  client/src/app/gateways/repositories/structure-levels/structure-level-repository.service.ts
  client/src/app/gateways/repositories/structure-levels/structure-level.action.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-list-of-speakers.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-base-sort.service/motion-list-base-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/components/participant-main/participant-main.component.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-pdf.service/participant-pdf.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.spec.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/services/structure-level-controller.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/services/structure-level-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/structure-level-routing.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/structure-level.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/index.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level-list-of-speakers.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level.ts
  client/src/app/site/pages/meetings/pages/participants/participants-routing.module.ts
  client/src/app/site/pages/meetings/pages/participants/participants.config.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/site/pages/meetings/view-models/view-meeting-user.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/export/csv-export-example.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/services/user-controller.service.ts
Labels: feature

#3066 Add speakers timemanagement
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/services/duration.service.spec.ts
  client/src/app/site/services/duration.service.ts
Labels: feature

#3107 Add structure levels to participant list form
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/modules/participant-list-info-dialog/components/participant-list-info-dialog/participant-list-info-dialog.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/modules/participant-list-info-dialog/components/participant-list-info-dialog/participant-list-info-dialog.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/modules/participant-list-info-dialog/services/participant-list-info-dialog.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: feature

#3108 Add CI to feature branches
  .github/workflows/build.yml
Labels: enhancement

#3111 Add structure levels to participants
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: feature

#3114 Fix CI on feature branches
  .github/workflows/build.yml
Labels: enhancement

#3117 Implement autopilot speaking times
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.spec.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.ts
Labels: feature
