Repository OpenSlides/openslides-client, pull requests merged in 2023-09, with the labels that each got.

#2737 Fix foreign groups in meeting after account add
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug, high

#2740 Allow mediafile access if projected
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-mediafile.ts
Labels: bug, high

#2735 Fix various date input bugs
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/ui/modules/datepicker/components/datepicker/datepicker.component.ts
  client/src/app/ui/modules/openslides-date-adapter/openslides-date-adapter.module.ts
Labels: bug, high

#2690 Fix topic title
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-pdf.service/topic-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/view-models/view-topic.ts
  client/src/app/site/pages/meetings/pages/projectors/projectors.subscription.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
Labels: bug, high

#2726 Improve shared worker reliability
  Makefile
  client/karma.conf.js
  client/package-lock.json
  client/package.json
  client/src/app/openslides-main-module/services/default-shared-worker.worker.ts
  client/src/app/openslides-main-module/services/shared-worker.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/worker/autoupdate/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate/autoupdate-stream.ts
  client/src/app/worker/autoupdate/autoupdate-subscription.ts
  client/src/app/worker/autoupdate/interfaces-autoupdate.ts
  client/src/app/worker/default-shared-worker.worker.ts
  client/src/app/worker/interfaces.ts
  client/src/app/worker/sw-autoupdate.ts
  client/src/app/worker/sw-control.ts
Labels: feature, high, enhancement

#2711 Build in warning dialogs for actions that change a users own groups
  client/src/app/gateways/repositories/participants/participant-repository.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
  client/src/app/ui/modules/choice-dialog/components/choice-dialog/choice-dialog.component.html
Labels: bug

#2745 Make pdf and csv export respect the meetings export settings
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-common-service.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-export.service/agenda-item-export.service.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-list-service.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-service.module.ts
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-export-service.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-service.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/statute-paragraphs/services/statute-paragraph-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motions-export.module.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-csv-export.service/participant-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-export.module.ts
  client/src/app/site/pages/meetings/services/export/index.ts
  client/src/app/site/pages/meetings/services/export/meeting-csv-export-for-backend.service.spec.ts
  client/src/app/site/pages/meetings/services/export/meeting-csv-export-for-backend.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-csv-export.service.spec.ts
  client/src/app/site/pages/meetings/services/export/meeting-csv-export.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-export.module.ts
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
Labels: bug, high

#2749 Fix repo filters flickering on autoupdate
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: bug, high

#2723 Improve user deletion dialog
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.html
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.scss
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.ts
Labels: enhancement

#2757 Use sendActionFn of Action concatinated to
  client/src/app/gateways/actions/action.ts
Labels: bug, high

#2756 Fix missing label in participant import
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/participant-import.module.ts
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
Labels: bug

#2763 Fix account import NullInjectorError
  client/src/app/site/pages/organization/pages/accounts/services/common/account-common-service.module.ts
Labels: bug, high

#2767 Fix list of speakers first contribution
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.subscription.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-list-of-speakers.ts
Labels: bug, high

#2375 Make list of speakers rearrangeable on mobile
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.html
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.ts
Labels: bug, need test instance, ui

#2395 Change hyperlink style
  client/src/app/site/modules/info/components/legal-notice-content/legal-notice-content.component.html
  client/src/app/site/modules/info/components/privacy-policy-content/privacy-policy-content.component.html
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/projector-message-slide/components/projector-message-slide/projector-message-slide.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.html
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/styles/motion-common-styles.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/assets/styles/global-components-style.scss
Labels: enhancement

#2771 Error handling of service worker apply update
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/modules/site-wrapper/services/update.service.ts
Labels: bug, need test instance

#2769 Test action worker watch
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.spec.ts
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.ts
  client/src/app/gateways/repositories/action-worker/view-action-worker.ts
  client/src/app/site/modules/wait-for-action-dialog/services/wait-for-action-dialog.service.ts
Labels: tests

#2773 Update build-and-test-dev-image to use localprod
  .github/workflows/build.yml
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/tests/Dockerfile.test
  client/tests/package-lock.json
  client/tests/package.json
  client/tests/playwright.config.ts
Labels: enhancement

#2774 Fix single option chart table style
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
Labels: high, enhancement, ui

#2776 Hide change password button if the operator has no right
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
Labels: bug

#2781 Use BroadcastChannel in shared worker for broadcasting
  client/src/app/openslides-main-module/services/shared-worker.service.ts
  client/src/app/worker/default-shared-worker.worker.ts
  client/src/app/worker/interfaces.ts
Labels: clean up

#2784 Add 'No changes at the text' description for amendments without changes
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
Labels: bug, high

#2783 Make motion multiselect csv/pdf export sort by current sorting
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/components/motion-multiselect-actions/motion-multiselect-actions.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/services/list/amendment-list-sort.service/amendment-list-sort.service.ts
Labels: feature

#2788 Fix vote delegation
  client/src/app/site/services/operator.service.ts
Labels: bug

#2790 Fix supporter edit in motion edit
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
Labels: bug, high

#2777 Fix projector preview
  client/src/app/site/pages/meetings/modules/projector/components/slide-container/slide-container.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
Labels: bug

#2796 Fix speaker column in XLSX export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug, high

#2786 Client performance improvements
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.html
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/site/pages/meetings/services/media-manage.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/modules/account-search-selector/components/account-search-selector/account-search-selector.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.ts
  client/src/app/site/services/data-store-update-manager.service.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.scss
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
  client/src/app/ui/modules/search-selector/components/repo-search-selector/repo-search-selector.component.ts
Labels: performance

#2794 Re-add speaker even if PoO
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: feature, high

#2801 Fix scrolling to change recommandation
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.ts
Labels: bug, high

#2807 Fix hidden agenda projection in autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-main/autopilot-main.component.ts
Labels: bug, critical

#2804 changed all instances of factory defaults to default settings
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.ts
  client/src/assets/i18n/cs.po
  client/src/assets/i18n/de.po
  client/src/assets/i18n/es.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/ru.po
  client/src/assets/i18n/template-en.pot
Labels: translation

#2805 Calculate sorted motion supporter list
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/site/base/base-controller.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, high

#2808 Fix force reload not working
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
Labels: bug, critical

#2803 Fix mediafile directory create cancel error
  client/src/app/site/pages/meetings/pages/mediafiles/services/mediafile-common.service.ts
Labels: bug

#2811 Fix committee meeting list user count
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/meetings/base/base-has-meeting-user-view-model.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/pages/committees/modules/services/meeting.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug

#2819 Fix amendment display
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/base/base-motion-detail-child.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
Labels: bug, high

#2822 Replace notify `to_all` with `to_meeting`
  client/src/app/gateways/notify.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/directives/listen-editing/listen-editing.directive.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/c4-dialog/components/c4-dialog/c4-dialog.component.ts
Labels: bug

#2824 Minor cleanup
  client/.eslintrc.js
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/assignment-detail.module.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/components/base-game-dialog/base-game-dialog.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/components/easter-egg-content-platform-dialog/easter-egg-content-platform-dialog.component.scss
  client/src/app/ui/modules/sidenav/modules/easter-egg/components/easter-egg-content-platform-dialog/easter-egg-content-platform-dialog.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/c4-dialog/components/c4-dialog/c4-dialog.component.html
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/c4-dialog/components/c4-dialog/c4-dialog.component.scss
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/c4-dialog/components/c4-dialog/c4-dialog.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/chess-dialog.module.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.html
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.scss
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.spec.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/index.ts
Labels: clean up

#2817 Fix search for category in motion edit
  client/src/app/infrastructure/definitions/tree.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
Labels: bug

#2795 Testing meeting settings definition service
  client/cli/generate-settings-defaults.ts
  client/src/app/gateways/autoupdate-adapter.service.spec.ts
  client/src/app/gateways/autoupdate-adapter.service.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/applause-bar-display.service.spec.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/applause-bar-display.service.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definition.service.spec.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definition.service.ts
Labels: tests

#2830 Add tests for main menu service
  client/src/app/site/pages/meetings/services/main-menu.service.spec.ts
Labels: tests

#2831 Add tests for duration service
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/committee-detail.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/services/committee-detail-service.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/services/committee-detail-shared-context.service/committee-detail-shared-context.service.spec.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/services/committee-detail-shared-context.service/committee-detail-shared-context.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/services/committee-detail-shared-context.service/index.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/services/index.ts
  client/src/app/site/services/duration.service.spec.ts
  client/src/app/site/services/duration.service.ts
Labels: tests

#2833 Add tests for RepositoryServiceCollectorServices
  client/src/app/gateways/repositories/repository-meeting-service-collector.service.spec.ts
  client/src/app/gateways/repositories/repository-service-collector.service.spec.ts
Labels: tests

#2832 Add tests for HttpStreamEndpointService
  client/src/app/gateways/http-stream/http-stream-endpoint.service.spec.ts
Labels: tests

#2411 Livestream window should not overlap other elements
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.html
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.ts
  client/src/app/site/modules/site-wrapper/site-wrapper.module.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.html
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.scss
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list-sort/category-list-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-sort/comment-section-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/tags/components/tag-list/tag-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/tags/components/tag-list/tag-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/components/projector-list/projector-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.scss
  client/src/app/ui/modules/list/components/filter-menu/filter-menu.component.html
  client/src/app/ui/modules/list/components/filter-menu/filter-menu.component.ts
  client/src/app/ui/modules/list/components/list/list.component.html
  client/src/app/ui/modules/list/components/list/list.component.ts
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
  client/src/styles.scss
Labels: bug, ui

#2826 Fix pdf export decoration formatting
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.spec.ts
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
Labels: bug, high

#2812 Fix scrolling table viewport resizing
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#2835 Minor cleanup #2
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/components/base-game-dialog/base-game-dialog.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/chess-dialog.module.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.html
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/services/chess-challenge.service.ts
Labels: clean up

#2840 Fix problem bulk set Personal note
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#2839 Fix problem with three picture menu
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
Labels: bug, low

#2842 Fix search selection option focus
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#2815 Fix participant-create-wizard
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/site/services/user.service.ts
Labels: bug

#2674 Switch account import to backend
  client/src/app/gateways/export/csv-export.service/csv-export-for-backend.service.ts
  client/src/app/gateways/export/csv-export.service/csv-export-utils.ts
  client/src/app/gateways/repositories/users/user-action.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
  client/src/app/site/base/base-via-backend-import-list.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import/topic-import.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/services/account-import.service/account-import.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/account-export.service/account-export.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/definitions/backend-import-preview.ts
Labels: feature

#2837 Fix request-to-speak count
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.html
Labels: bug

#2838 Fix set submitter containing non meeting users
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/motions/motions.module.ts
Labels: bug

#2828 Fix motion list structure level
  client/src/app/domain/fieldsets/user.ts
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
Labels: bug, high
