Repository OpenSlides/openslides-client, pull requests merged in 2023-02, with the labels that each got.

#1975 fix set presence via participant number status
  client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts
Labels: bug, high

#2000 Fix pdf ballot logo.
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-pdf.service/assignment-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-pdf.service/motion-poll-pdf.service.ts
Labels: bug, high

#1994 Made amendment list mobile menu slimmer
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
Labels: bug

#2005 Fixed pdf page number position
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
Labels: bug, high

#1976 add validator for organization reply address
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/meeting-settings-group-detail.module.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
  client/src/app/ui/directives/directives.module.ts
  client/src/app/ui/directives/trim-on-paste/trim-on-paste.directive.ts
Labels: bug, high

#1988 fix mass deletion selection reset
  client/src/app/ui/modules/list/components/view-list/view-list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#1964 Repaired getUploadFileJson function error catching
  client/src/app/infrastructure/utils/import/json-import-file-utils.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-import/workflow-import.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.ts
Labels: bug

#1860 Rework of action worker handling
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.ts
  client/src/app/gateways/repositories/action-worker/view-action-worker.ts
  client/src/app/site/modules/wait-for-action-dialog/components/stopped-waiting-for-action-dialog/index.ts
  client/src/app/site/modules/wait-for-action-dialog/components/stopped-waiting-for-action-dialog/stopped-waiting-for-action-dialog.component.html
  client/src/app/site/modules/wait-for-action-dialog/components/stopped-waiting-for-action-dialog/stopped-waiting-for-action-dialog.component.scss
  client/src/app/site/modules/wait-for-action-dialog/components/stopped-waiting-for-action-dialog/stopped-waiting-for-action-dialog.component.spec.ts
  client/src/app/site/modules/wait-for-action-dialog/components/stopped-waiting-for-action-dialog/stopped-waiting-for-action-dialog.component.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.html
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.scss
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.spec.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/index.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.html
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.scss
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-dialog/wait-for-action-dialog.component.spec.ts
  client/src/app/site/modules/wait-for-action-dialog/definitions/index.ts
  client/src/app/site/modules/wait-for-action-dialog/services/wait-for-action-dialog.service.ts
  client/src/app/site/modules/wait-for-action-dialog/wait-for-action-dialog.module.ts
Labels: feature

#1989 fix first speech always visible
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-list-of-speakers.ts
Labels: bug

#1957 chip select component
  client/src/app/site/modules/chip-select/chip-select.module.ts
  client/src/app/site/modules/chip-select/components/chip-select-chip/chip-select-chip.component.html
  client/src/app/site/modules/chip-select/components/chip-select-chip/chip-select-chip.component.scss
  client/src/app/site/modules/chip-select/components/chip-select-chip/chip-select-chip.component.spec.ts
  client/src/app/site/modules/chip-select/components/chip-select-chip/chip-select-chip.component.ts
  client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.html
  client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.scss
  client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.spec.ts
  client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/assignment-detail.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
Labels: feature

#2011 fix logo deselect
  client/src/app/domain/models/mediafiles/mediafile.ts
  client/src/app/site/pages/meetings/services/media-manage.service.ts
Labels: bug

#2014 Moved fullscreen editor in front of sidebar
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.ts
Labels: bug

#2017 sync package-lock.json
  client/package-lock.json
Labels: dependencies

#2009 refactored html-to-pdf services
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/amendment-list-pdf.service/amendment-list-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: clean up

#2021 remove projector detail subscription
  client/src/app/site/pages/meetings/pages/projectors/modules/fullscreen-projector/components/fullscreen-projector-main/fullscreen-projector-main.component.ts
  client/src/app/site/pages/meetings/pages/projectors/view-models/view-projector.ts
Labels: bug, performance

#2034 check export info for supporters on pdf export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#2006 allow svg images as logo
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/gateways/http.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/definitions/index.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-export.service/mediafile-list-export.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
  client/src/app/ui/modules/sidenav/components/logo/logo.component.scss
Labels: feature

#2015 fix BaseMotionDetailActionCardComponent motion ref update
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/base/base-motion-detail-action-card.component.ts
Labels: bug

#2018 Convert default projectors to list
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/config/model-subscription.ts
  client/src/app/site/pages/meetings/pages/projectors/services/projector-controller.service.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
Labels: feature

#1993 Implemented isUniqueAmong validator for motion numbers and category…
  client/src/app/infrastructure/utils/validators/is-unique-among.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list/category-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list/category-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
Labels: feature, high

#2033 make list of speaker overlay fixed
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.scss
Labels: bug, high

#1985 Rework permission matrix
  client/cli/generate-permissions.ts
  client/cli/tsconfig.json
  client/src/app/domain/definitions/permission-children.ts
  client/src/app/domain/definitions/permission-relations.ts
  client/src/app/domain/definitions/permission.ts
  client/src/app/gateways/repositories/groups/group-repository.service.ts
  client/src/app/gateways/repositories/groups/group.action.ts
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/site/base/base.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/groups.module.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/services/group-controller.service.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/view-models/view-group.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/services/committee-import.service/committee-import.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/ui/modules/prompt-dialog/services/prompt.service.ts
Labels: feature

#2025 fix some pdf issues and add tests
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.spec.ts
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#1832 Fix extension fields after migration
  client/src/app/domain/models/motions/motion.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/base/base-motion-slide.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: bug, high

#2035 Update jitsi API and config
  client/src/app/site/pages/meetings/pages/interaction/services/rtc.service.ts
  client/src/assets/jitsi/external_api.js
Labels: bug

#2019 improve autoupdate existing subscription handling
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: enhancement

#2041 Fix projection title of current LOS
  client/src/app/gateways/repositories/meeting-repository.service.ts
Labels: bug

#2042 Fix the sorting of the subcategories in the toc in the pdf export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-catalog.service/motion-pdf-catalog.service.ts
Labels: bug

#2046 fix can not create motion if motion without number exists
  client/src/app/infrastructure/utils/validators/is-unique-among.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
Labels: bug, high

#2045 disable parallel mediafile upload by default
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-upload/components/organization-mediafile-upload/organization-mediafile-upload.component.ts
  client/src/app/ui/modules/media-upload-content/components/media-upload-content/media-upload-content.component.ts
Labels: bug, high

#2049 fix motion category tiles not working
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
Labels: bug, high

#2047 disable presenter call for archived meetings
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: bug

#2053 fix point of order submitet on cancel
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/components/point-of-order-dialog/point-of-order-dialog.component.html
Labels: bug, critical

#2062 prevent duplicate pdf retrieval on projector
  client/src/app/gateways/export/file-export.service/file-export.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/services/slide-mediafile.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-export.service/mediafile-list-export.service.ts
Labels: feature

#2064 Filtered titleless motions out of motion lists
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug
