Repository OpenSlides/openslides-client, pull requests merged in 2023-08, with the labels that each got.

#2514 Global search improve filtering
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
Labels: enhancement

#2606 Fix motion multiselect add submitters
  client/src/app/gateways/repositories/motions/motion-submitter-repository.service/motion-submitter-repository.service.ts
Labels: bug

#2607 Fix motion pdf export supporters not displayed
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#2613 Fix motion block follow recommendation
  client/src/app/site/pages/meetings/pages/motions/modules/motion-blocks/services/motion-block-controller.service/motion-block-controller.service.ts
Labels: bug, high

#2611 Fix participant detail edit vote delegation to
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug, high

#2614 Fix orga settings for orga admins
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: bug, high

#2544 Add tag_ids and agenda_type to agenda item duplication
  client/src/app/domain/models/topics/topic.ts
  client/src/app/gateways/repositories/agenda/functions.ts
  client/src/app/gateways/repositories/topics/topic-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/view-models/view-topic.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.ts
Labels: bug

#2244 Implement backend topic import
  client/src/app/domain/models/agenda/agenda-item.ts
  client/src/app/gateways/export/csv-export.service/csv-export-for-backend.service.spec.ts
  client/src/app/gateways/export/csv-export.service/csv-export-for-backend.service.ts
  client/src/app/gateways/repositories/topics/topic-repository.service.ts
  client/src/app/gateways/repositories/topics/topic.action.ts
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
  client/src/app/site/base/base-via-backend-import-list.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/definitions/topics.constants.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import/topic-import.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import/topic-import.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/services/topic-export.service/topic-export.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/services/topic-import.service/topic-import.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/topic-import.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-export.service/agenda-item-export.service.ts
  client/src/app/ui/base/import-service.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.scss
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.spec.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/definitions/backend-import-preview.ts
  client/src/app/ui/modules/import-list/definitions/import-list-header-definition.ts
  client/src/app/ui/modules/import-list/import-list.module.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
Labels: feature

#2633 Fix user create
  client/src/app/gateways/repositories/users/user-repository.service.ts
Labels: bug

#2638 Fix rtf tests
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.spec.ts
Labels: bug, tests

#2632 Committee detail performance
  client/src/app/domain/models/base/base-model.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/organization.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/accounts.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/components/committee-detail/committee-detail.component.ts
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
  client/src/app/site/services/operator.service.ts
Labels: enhancement

#2472 Make sort lists update only when relevant data is changed
  client/src/app/infrastructure/definitions/tree.ts
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
Labels: bug

#2603 Created CommaSeparatedListingComponent for enumerations in html template
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/motion-slide.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-meta-info/topic-poll-meta-info.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/topic-poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/agenda-item-list.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/assignment-poll.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-meta-info/assignment-poll-meta-info.component.html
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/chat-group-list.module.ts
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail/chat-group-detail.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/mediafile-list.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-meta-information/motion-poll-meta-information.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/motion-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/comments.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/motion-list.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/workflows.module.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/participant-detail.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/committee-detail-view.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/ui/modules/comma-separated-listing/comma-separated-listing.module.ts
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.scss
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.spec.ts
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.ts
  client/src/app/ui/modules/comma-separated-listing/index.ts
Labels: bug, high, ui

#2617 [RTF] Fix speaker creation with newly created user
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/speaker-controller.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug, high

#2444 Implement WiFi access data slide
  client/package-lock.json
  client/package.json
  client/src/app/domain/definitions/meeting-settings-defaults.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/infrastructure/utils/formatting-functions.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.spec.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/wifi-access-data-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/wifi-access-data-slide.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/definitions/slides.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-pdf-export.service/participant-pdf-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/export/participant-pdf.service/participant-pdf.service.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/message-controls/message-controls.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/message-controls/message-controls.component.scss
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.scss
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/ui/modules/qr-code/components/qr-code/qr-code.component.html
  client/src/app/ui/modules/qr-code/components/qr-code/qr-code.component.scss
  client/src/app/ui/modules/qr-code/components/qr-code/qr-code.component.spec.ts
  client/src/app/ui/modules/qr-code/components/qr-code/qr-code.component.ts
  client/src/app/ui/modules/qr-code/index.ts
  client/src/app/ui/modules/qr-code/qr-code.module.ts
Labels: feature

#2645 Testing action service
  client/src/app/gateways/actions/action-utils.ts
  client/src/app/gateways/actions/action.service.spec.ts
  client/src/app/gateways/actions/action.service.ts
Labels: tests

#2647 Add referring motions to pdf export
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: feature, high

#2649 Expand cross reference links in motions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: feature, high

#2652 Fix meeting list after account detail request
  client/src/app/infrastructure/definitions/relations/relations.ts
Labels: bug, high

#2660 Fix user creation for new assignment_candidate
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
Labels: bug, high

#2657 Fix qrcode generation without password
  client/src/app/infrastructure/utils/formatting-functions.ts
Labels: bug

#2663 Adjust example file topic import
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/services/topic-export.service/topic-export.service.ts
Labels: bug

#2665 Fix poll title in autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
Labels: bug

#2662 Fix projection dialog projection default editing
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
Labels: bug

#2675 Show general abstain button for Y/N elections
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
Labels: bug

#2672 Ensure integer entries are displayed in backend-import preview list
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
Labels: bug

#2681 Add missing translations for date-time-picker
  client/src/app/ui/modules/datepicker/components/daterangepicker/daterangepicker.component.html
Labels: bug

#2686 Fix add-to-meetings autoupdates
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
Labels: bug

#2689 Fix personal note UI
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-personal-note/motion-personal-note.component.html
Labels: bug

#2693 Write tests for action class and MeetingMediaAdapterService
  client/src/app/gateways/actions/action.service.spec.ts
  client/src/app/gateways/actions/action.service.ts
  client/src/app/gateways/actions/action.ts
  client/src/app/gateways/meeting-media-adapter.service.spec.ts
  client/src/app/gateways/meeting-media-adapter.service.ts
  client/src/app/gateways/repositories/agenda/agenda-item-repository.service.ts
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-comments/motion-comment-section-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-state-repository.service/motion-state-repository.service.ts
Labels: tests

#2696 Improve test coverage
  client/src/app/gateways/error-mapping/error-map.service.spec.ts
  client/src/app/infrastructure/utils/subscription-map.spec.ts
  client/src/app/infrastructure/utils/transform-functions.spec.ts
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-percent-base/poll-percent-base.pipe.spec.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.spec.ts
Labels: tests

#2697 Exit view list filter/search/sort observables on destroy
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/list/definitions/filter-service.ts
  client/src/app/ui/modules/list/definitions/search-service.ts
  client/src/app/ui/modules/list/definitions/sort-service.ts
  client/src/app/ui/modules/list/services/list-search.service.ts
Labels: high, performance

#2698 Build in referring motions sorting in pdf
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug, high

#2701 Fix entitled-users-table delegation information
  client/src/app/domain/models/poll/poll-constants.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
Labels: bug

#2517 Save sort order only on change
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/services/assignment-sort-list.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-sort.service/mediafile-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/services/motion-block-sort.service/motion-block-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/amendment-list-sort.service/amendment-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-sort.service/committee-sort.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-sort/meeting-list-sort.service.ts
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.ts
  client/src/app/ui/modules/list/definitions/sort-service.ts
Labels: enhancement

#2712 Fix list of speakers first contribution subscription
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.subscription.ts
Labels: bug

#2718 Cleanup worker cache on delete
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/view-model-store-update.service.ts
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/interfaces-autoupdate.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: bug, high

#2704 Check for app updates on load
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/modules/site-wrapper/services/update.service.ts
Labels: bug, high

#2713 Enable user count for meeting admins
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.ts
Labels: feature, high
