Repository OpenSlides/openslides-client, pull requests merged in 2023-01, with the labels that each got.

#1889 Fix forwarding filtering in search selector
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#1899 add motion sequential number to export meta info
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
Labels: feature

#1901 Hid menu motion forward button for un-forwardable motions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
Labels: bug

#1886 Use `recommendation_label` for recommendation history entry
  client/src/app/site/modules/translations/marked-translations.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
Labels: bug

#1893 Created exception that allows superadmin to edit meeting meta data in…
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: affected view: committee

#1885 Automatic filling in of default type for meeting settings that lack a…
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: clean up

#1880 Fixed amendment list component multiselect
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
Labels: bug, low

#1878 add livestream panel up down arrow
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/interaction-container/interaction-container.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/interaction-container/interaction-container.component.scss
Labels: feature, low

#1868 projector pdf page scrolling
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
Labels: feature

#1864 display error message on spinner when there is no connection
  client/src/app/site/modules/global-spinner/components/global-spinner/global-spinner.component.html
  client/src/app/site/modules/global-spinner/components/global-spinner/global-spinner.component.scss
  client/src/app/site/modules/global-spinner/components/global-spinner/global-spinner.component.spec.ts
  client/src/app/site/modules/global-spinner/components/global-spinner/global-spinner.component.ts
  client/src/app/site/modules/global-spinner/global-spinner.module.ts
  client/src/app/site/modules/global-spinner/services/spinner.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/connection-status.service.ts
  client/src/app/site/services/openslides.service.ts
  client/src/app/ui/modules/spinner/components/spinner/spinner.component.scss
Labels: feature

#1904 Split multi motion forwarding into separate actions
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: bug, high

#1882 Add last_login field and fix sorting
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/base/base-sort.service/base-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/participant-detail.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/account-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/services/user-controller.service.ts
Labels: bug, feature, high

#1907 use projector zoom controls for mediafiles
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/presentation-controls/presentation-controls.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/presentation-controls/presentation-controls.component.ts
Labels: feature

#1897 participant import - use only username for duplicate check if given
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
Labels: bug, high, affected view: participant

#1906 Motion exports should now be using sequential numbers
  client/src/app/gateways/export/csv-export.service/csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug, high

#1910 fix autoupdate query params overwritten after single request
  client/src/app/site/services/autoupdate/autoupdate.service.ts
Labels: bug, high

#1911 make own user gender editable
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#1928 Fixed participant create wizard stepper
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug

#1895 Built projection hint into detail views
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.scss
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.spec.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/detail-view.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.ts
Labels: feature, low

#1876 improve client offline handling
  client/src/app/gateways/http.service.ts
Labels: bug, low

#1877 add buttons to delete prevoius and next speakers
  client/src/app/gateways/repositories/list-of-speakers/list-of-speakers-repository.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
Labels: feature

#1879 Made flex-vertical-center style's alignment safe
  client/src/styles.scss
Labels: bug, low

#1883 Motion list displays last_modified instead of created timestamp if th…
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
Labels: feature, waiting

#1887 Add consecutive selections to committee recommendation selection
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-extension-field/motion-extension-field.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-extension-field/motion-extension-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.scss
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: feature

#1922 Add workflow to automatically set project
  .github/workflows/set-project.yml
Labels: enhancement

#1939 Fix CI after restructure of the main repo
  .github/workflows/build.yml
Labels: bug, high

#1942 Fixed referring motions list
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
Labels: bug, high

#1908 fix meeting list getting cleared
  client/src/app/site/pages/organization/config/model-subscription.ts
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
Labels: bug, high

#1945 Reverse f589978 Export also under points in the nested-lists (#1757)
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: high

#1952 PDF export: New implementation of nested lists
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#1931 fix os-banner causing extra scroll bar
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.html
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.scss
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.html
  client/src/app/ui/modules/file-upload/components/file-upload/file-upload.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/modules/list/components/list/list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug, high

#1948 fix calendar meetings not deleted
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/infrastructure/definitions/relations/utils.ts
  client/src/app/site/pages/organization/config/model-subscription.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
  client/src/app/site/services/model-request-builder/model-request-object.ts
  client/src/app/site/services/view-model-store-update.service.ts
Labels: bug, high

#1963 Participant detail edit now only uses standard group if necessary
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
Labels: bug

#1949 Removed client user projection default
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#1946 Added unsafe versions of flex center and flex-vertical-center styles
  client/src/app/ui/modules/openslides-overlay/components/overlay/overlay.component.html
  client/src/styles.scss
Labels: bug

#1955 move autoupdate received data management to stream
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/autoupdate-subscription.ts
Labels: performance

#1956 Implemented account list active meeting filter + Orga statistics rework
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/organization-info/components/organization-statistics/organization-statistics.component.html
Labels: feature

#1921 Cleanup
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/base/base.component.ts
  client/src/app/site/modules/user-components/components/password-form/password-form.component.ts
  client/src/app/site/modules/user-components/components/user-multiselect-actions/user-multiselect-actions.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/history/definitions/position.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/directives/listen-editing/listen-editing.directive.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-multiselect-actions/participant-multiselect-actions.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-password/account-password.component.ts
  client/src/app/site/pages/organization/pages/organization-info/components/organization-statistics/organization-statistics.component.ts
  client/src/app/site/pages/organization/services/organization.service.ts
  client/src/app/site/pages/organization/view-models/view-organization.ts
  client/src/app/ui/base/base-ui-component.ts
  client/src/app/ui/modules/spinner/components/spinner/spinner.component.ts
Labels: bug, clean up

#1981 Display global option in single votes table
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-form/motion-poll-form.component.ts
Labels: bug

#1980 Clean up translations & introduce ngx-translate-extract fork
  Dockerfile.dev
  client/cli/generate-settings-defaults.ts
  client/package-lock.json
  client/package.json
  client/sed_replacements
  client/src/app/domain/definitions/permission-children.ts
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/domain/definitions/permission.ts
  client/src/app/domain/models/agenda/agenda-item.ts
  client/src/app/domain/models/mediafiles/mediafile.constants.ts
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/gateways/repositories/participants/participant-repository.service.ts
  client/src/app/site/modules/translations/marked-translations.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/definitions/slides.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-dialog/topic-poll-dialog.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/services/topic-import.service/topic-import.service.ts
  client/src/app/site/pages/meetings/pages/assignments/definitions/index.ts
  client/src/app/site/pages/meetings/pages/assignments/view-models/view-assignment.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meta-info/committee-meta-info.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-sort.service/committee-sort.service.ts
  client/src/assets/i18n/template-en.pot
Labels: bug, clean up, translation

#1977 fix empty scrolling tables and scrolling tables with a lot of data
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#1933 Export poll results as pdf
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-pdf.service/assignment-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-service.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/assignment-polls.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-pdf.service/motion-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-service.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.ts
Labels: feature

#1991 Remove tag_ids from payload for amendments.
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
Labels: bug, critical
