Repository OpenSlides/openslides-client, pull requests merged in 2023-10, with the labels that each got.

#2849 Add lines between class members eslint rule
  client/.eslintrc.js
  client/src/app/domain/models/projector/projection.ts
  client/src/app/gateways/action-worker-watch/action-worker-watch.service.spec.ts
  client/src/app/gateways/http-stream/http-stream-endpoint.service.spec.ts
  client/src/app/gateways/repositories/base-agenda-item-and-list-of-speakers-content-object-repository.ts
  client/src/app/gateways/repositories/point-of-order-category/point-of-order-category-repository.service.ts
  client/src/app/gateways/repositories/projector-messages/projector-message-repository.service.ts
  client/src/app/gateways/repositories/themes/theme-repository.service.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/base/base-view-model.ts
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/pages/meetings/base/base-has-meeting-user-view-model.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/components/attachment-control/attachment-control.component.ts
  client/src/app/site/pages/meetings/modules/projector/components/slide-container/slide-container.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/change-recommendation-unified-change.ts
  client/src/app/site/pages/meetings/pages/interaction/services/call-restriction.service.ts
  client/src/app/site/pages/meetings/pages/interaction/services/interaction-receive.service.ts
  client/src/app/site/pages/meetings/pages/interaction/services/interaction.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll-candidate-list.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll-candidate.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
  client/src/app/site/pages/meetings/services/meeting-component-service-collector.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-export.service/committee-export.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/ui/base/base-form-control.ts
  client/src/app/ui/base/base-form-field-control.ts
  client/src/app/ui/modules/choice-dialog/services/choice.service.ts
  client/src/app/ui/modules/color-form-field/components/color-form-field/color-form-field.component.ts
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree-sort.service.spec.ts
Labels: clean up

#2856 Fix double click needed to remove filter
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
Labels: bug

#2863 Add test for CsvExportForBackendService
  client/src/app/gateways/export/csv-export.service/csv-export-for-backend.service.spec.ts
  client/src/app/gateways/export/csv-export.service/csv-export-for-backend.service.ts
Labels: tests

#2846 Fix bulk change Submitters
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#2844 Fix search service issues
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/services/global-search/global-search.service.ts
Labels: bug, enhancement

#2847 Improve shared worker restart after reload process
  client/src/app/openslides-main-module/services/shared-worker.service.ts
Labels: bug

#2851 Pause autoupdate connection on inactivitiy
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/window-visibility.service.ts
Labels: feature, performance

#2874 Add tests for list-search.service
  client/src/app/ui/modules/list/services/list-search.service.spec.ts
Labels: tests

#2888 Fix participant history error
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
Labels: bug

#2848 Fix monospace font wrong weight specified
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.scss
  client/src/assets/styles/font-variables.scss
Labels: bug, Safari/iOS

#2854 Add info message to list of speakers content, if present is needed
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
Labels: enhancement

#2857 Block motions/tags page, if missing permission
  client/src/app/site/pages/meetings/pages/motions/motions-routing.module.ts
Labels: bug

#2859 Add ability to go back to lead motion after amendment create
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/ui/modules/head-bar/services/routing-state.service.ts
Labels: bug

#2861 Fix move in call list functionality
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
Labels: bug, low

#2901 Fix meeting admin update as committee admin
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, critical

#2905 Fix route state undefined
  client/src/app/ui/modules/head-bar/services/routing-state.service.ts
Labels: bug

#2909 PDF: Do not show referring motions when it is turned off in the motions settings
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#2928 Add tests for the color service
  client/src/app/site/services/color.service.spec.ts
Labels: tests

#2907 Fix autoupdate request flooding after logout
  client/src/app/site/services/view-model-store-update.service.ts
  client/src/app/worker/autoupdate/autoupdate-stream.ts
Labels: bug, high

#2873 Prevent add ballot if deleted users
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
Labels: bug

#2879 Update global search to show marks bolder
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
  client/src/app/site/services/global-search/global-search.service.ts
Labels: feature, ui

#2881 Change shown sequential number and add a space
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
Labels: bug, high

#2883 Add perm check to remove from motion block
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
Labels: bug, high, tablet, phone

#2887 Fix conflicting amendment projection
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: bug, high

#2889 Fix meeting history using wrong user repo
  client/src/app/site/base/base-controller.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/history/history.module.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#2891 Possible fix for the projection edit dialog
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
Labels: bug, high

#2915 Add missing number to history subscription
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
Labels: bug

#2884 Global search improvements
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/services/global-search/definitions.ts
  client/src/app/site/services/global-search/global-search.service.ts
Labels: bug, enhancement

#2932 Add test for relogging in
  client/src/app/worker/autoupdate/autoupdate-stream.ts
  client/tests/integration/login.spec.ts
Labels: clean up, tests

#2882 Remove paginator from history page
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/history/history.module.ts
Labels: enhancement

#2868 Fix icc connections not reopened on resolve
  client/src/app/gateways/base-icc-gateway.service.ts
  client/src/app/gateways/http-stream/http-stream.ts
Labels: bug

#2853 Fix countdowns over an hour
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/projector-countdown-slide/components/projector-countdown-slide.component.scss
Labels: bug

#2937 Add missing subscription for meeting create
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/organization.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/committee-detail-meeting-main/committee-detail-meeting-main.component.ts
Labels: bug

#2952 Fix missing star icon in motion-block
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
Labels: bug

#2947 Update sort and filter at meeting switch
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/services/active-filters.service.ts
Labels: bug
