Repository OpenSlides/openslides-client, pull requests merged in 2023-11, with the labels that each got.

#2948 Change duration of request of speakers to hours:mins
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.html
  client/src/app/site/services/duration.service.spec.ts
  client/src/app/site/services/duration.service.ts
Labels: enhancement

#2964 Update agenda projection
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/agenda-item-list-slide/components/agenda-item-list-slide/agenda-item-list-slide.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug, high

#2954 Use gramatically correct email snackbar messages
  client/src/app/site/pages/login/pages/reset-password-confirm/components/reset-password-confirm/reset-password-confirm.component.ts
  client/src/app/site/pages/login/pages/reset-password/components/reset-password/reset-password.component.ts
Labels: enhancement

#2965 Update way to check for agenda-item-list
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug

#2953 Add missing sorting for filter properies in filter list
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: bug

#2967 Fix version history-link
  client/src/app/site/modules/info/components/legal-notice-content/legal-notice-content.component.html
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.html
Labels: bug, high

#2963 Fix a problem in the poll service
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
Labels: bug, high

#2911 Add validators to email and default_vote_weight in some dialog
  client/src/app/infrastructure/utils/validators/email.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/login/pages/reset-password/components/reset-password/reset-password.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: enhancement

#2866 Mediafile support recursive folder download
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-export.service/mediafile-list-export.service.ts
Labels: bug

#2968 Update los contribution count
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug

#2980 Correcting translations
  client/src/app/infrastructure/utils/validators/email.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
Labels: translation

#2960 Add tests to openslides-status service
  client/src/app/site/services/openslides-status.service.spec.ts
  client/src/app/site/services/openslides-status.service.ts
Labels: tests

#2977 Clean up search-service
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
Labels: clean up

#2979 Move motion block recommendation text after icon
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
Labels: enhancement

#2990 Fix safari chyron font
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.scss
  client/src/app/site/pages/meetings/services/load-font.service.ts
Labels: bug, Safari/iOS

#2995 Make user option title load - alternative
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-option.ts
  client/src/app/site/services/relation-manager.service.ts
Labels: bug, high

#2993 Change string in settings > motions
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: enhancement

#2998 Update material tabs and slider to mdc
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/assignment-polls.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/motion-polls.module.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/projector-edit-dialog.module.ts
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/import-list.module.ts
  client/src/app/ui/modules/vertical-tab-group/components/vertical-tab-group/vertical-tab-group.component.ts
  client/src/app/ui/modules/vertical-tab-group/vertical-tab-group.module.ts
  client/src/assets/styles/tables.scss
  client/src/assets/styles/theme-styles.scss
  client/src/styles.scss
Labels: dependencies, clean up

#2989 Motion block update place of recommender
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
Labels: enhancement, ui

#2919 Account import improvements
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/services/account-import.service/account-import.service.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.scss
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/definitions/import-list-header-definition.ts
Labels: bug

#3009 Fix analog default election mode
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
  client/src/assets/styles/theme-styles.scss
Labels: bug, critical

#3012 Synchronize commitUpdate
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/site/services/data-store-update-manager.service.ts
  client/src/app/site/services/view-model-store-update.service.ts
Labels: bug

#3018 Fix amendment slide line numbering
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/motion-slide-data.ts
Labels: bug, high

#3020 Fix cr projection with start_line_number set
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
Labels: bug, high

#3022 Add tests to fallback-routes service
  client/src/app/site/services/fallback-routes.service.spec.ts
Labels: tests

#3027 Add tests to auth-token service
  client/src/app/site/services/auth-token.service.spec.ts
Labels: tests

#2999 Migrate mdc tooltips
  client/src/app/gateways/export/progress-snack-bar/progress-snack-bar.module.ts
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/modules/info/info.module.ts
  client/src/app/site/modules/user-components/user-components.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/detail-view.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/projectable-list.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/projection-dialog.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/speaker-button/speaker-button.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/list-of-speakers.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/topic-poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/topic-import.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/agenda-sort.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/assignment-detail.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/assignment-list.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.module.ts
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/chat-group-list.module.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/action-bar/action-bar.module.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/interaction-container.module.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/mediafile-list.module.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/meeting-settings-group-detail.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/motion-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/categories.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/motion-blocks.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/motion-list.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/workflows.module.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/groups.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/participant-detail-manage.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/participant-detail.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/participant-import.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/meetings/pages/polls/modules/poll-list/poll-list.module.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/projector-edit-dialog.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/projector-detail.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/projector-list.module.ts
  client/src/app/site/pages/organization/modules/account-search-selector/account-search-selector.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/account-list.module.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-components.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/committee-import.module.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/dashboard-detail.module.ts
  client/src/app/site/pages/organization/pages/designs/designs.module.ts
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/theme-list.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/meeting-list.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/modules/organization-tag-dialog/organization-tag-dialog.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/organization-tags.module.ts
  client/src/app/ui/modules/color-form-field/color-form-field.module.ts
  client/src/app/ui/modules/file-list/file-list.module.ts
  client/src/app/ui/modules/file-upload/file-upload.module.ts
  client/src/app/ui/modules/head-bar/head-bar.module.ts
  client/src/app/ui/modules/icon-container/components/icon-container/icon-container.component.ts
  client/src/app/ui/modules/icon-container/icon-container.module.ts
  client/src/app/ui/modules/import-list/import-list.module.ts
  client/src/app/ui/modules/list/list.module.ts
  client/src/app/ui/modules/search-selector/search-selector.module.ts
Labels: dependencies

#3003 Add tests to connection-status service
  client/src/app/site/services/connection-status.service.spec.ts
  client/src/app/site/services/connection-status.service.ts
Labels: tests

#3026 Fix topic poll create after meeting create
  client/src/app/domain/models/users/group.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/view-models/view-group.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
Labels: bug

#2895 Update getTitle of speaker with deleted user
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
Labels: bug

#3000 Motion detail run change reco on motion id change
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
Labels: clean up

#3034 Fix vote weight 0 not displayed
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#3013 Global search improvements
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/services/global-search/definitions.ts
  client/src/app/site/services/global-search/global-search.service.ts
Labels: feature

#3031 Add height to title container
  client/src/app/ui/modules/action-card/components/action-card/action-card.component.scss
Labels: ui

#3036 Fix multiselect motion move in agenda
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#3001 Update material radio-buttons
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/projection-dialog.module.ts
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/motion-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/motion-change-recommendation-dialog/motion-change-recommendation-dialog.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/projector-edit-dialog.module.ts
  client/src/styles.scss
Labels: dependencies

#3041 Update nanocosmos url
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
Labels: feature

#3043 Remove unused scss classes in global search
  client/src/assets/styles/global-components-style.scss
Labels: clean up

#3035 Fix linter warnings
  client/.eslintrc.js
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/gateways/actions/action-utils.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/infrastructure/utils/import/import-context.ts
  client/src/app/infrastructure/utils/overload-js-functions.ts
  client/src/app/openslides-main-module/services/dom.service.ts
  client/src/app/site/modules/translations/openslides-translation.service.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/votes-table/votes-table.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/interaction/services/rtc.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail-sort/workflow-detail-sort.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/ui/modules/grid/tile/tile.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/components/base-game-dialog/base-game-dialog.ts
  client/src/app/ui/modules/spinner/components/spinner/spinner.component.ts
  client/src/app/worker/autoupdate/autoupdate-subscription.ts
  client/src/testing/models/test-change-recommendation.ts
Labels: clean up

#3049 Fix os-list filter bar slot
  client/src/app/ui/modules/list/components/list/list.component.html
Labels: bug

#2862 Update motion workflow export
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/services/workflow-export.service/workflow-export.service.ts
Labels: bug

#2407 Add tooltips
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-list/chat-group-list.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/components/projector-list/projector-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/organization-mediafile-list.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/pages/organization-tag-list/components/organization-tag-list/organization-tag-list.component.html
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.html
  client/src/app/ui/modules/sidenav/sidenav.module.ts
Labels: feature
