Repository OpenSlides/openslides-client, pull requests merged in 2023-03, with the labels that each got.

#1890 Implement global webinterface logo
  client/src/app/domain/models/mediafiles/mediafile.constants.ts
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/error/components/error-main/error-main.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-mediafile.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
  client/src/app/site/pages/meetings/services/media-manage.service.ts
  client/src/app/site/pages/meetings/services/meeting-collection-mapper.service.ts
  client/src/app/site/pages/organization/modules/navigation/organization-navigation/organization-navigation.component.ts
  client/src/app/site/pages/organization/organization-routing.module.ts
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.ts
  client/src/app/site/pages/organization/services/organization.service.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
Labels: feature

#2038 agenda item poll PDF export
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll/topic-poll.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll/topic-poll.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll-pdf.service/topic-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-common-service.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-pdf.service/topic-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-pdf.service/assignment-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-pdf.service.ts
Labels: feature

#2054 fix console error in common list of speaker slide
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.ts
Labels: bug, low

#2070 Fixed meeting-side logo and font selection
  client/src/app/domain/models/mediafiles/mediafile.ts
Labels: bug, high

#2023 Added meeting admin tests to guard tests
  client/tests/integration/guards.spec.ts
Labels: tests

#2051 update node version in Dockerfiles
  Dockerfile
  Dockerfile.dev
Labels: dependencies

#2058 Fix sorting by category
  client/src/app/site/pages/meetings/pages/motions/modules/categories/view-models/view-motion-category.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
Labels: bug

#2077 run prettier within eslint
  client/.eslintrc.js
  client/cli/cleanup.ts
  client/package-lock.json
  client/package.json
  client/src/e2e-imports.module.ts
  client/src/polyfills.ts
  client/src/test.ts
  client/src/testing/models/test-change-recommendation.ts
Labels: clean up

#2088 Introduce `RawImportModel` with id
  client/src/app/infrastructure/utils/import/import-model.ts
  client/src/app/infrastructure/utils/import/import-utils.ts
  client/src/app/infrastructure/utils/import/static-main-import-handler.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/services/committee-import.service/committee-import.service.ts
Labels: enhancement

#2099 autoupdate fulfillment check
  client/src/app/domain/interfaces/model-request.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
  client/src/app/site/services/model-request-builder/model-request-object.ts
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-subscription.ts
Labels: feature

#2098 Added duplicates account filter
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/pages/meetings/services/meeting-active-filters.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/services/active-filters.service.ts
  client/src/app/ui/modules/list/components/filter-menu/filter-menu.component.ts
  client/src/app/ui/modules/list/definitions/filter-service.ts
Labels: feature

#2095 Realigned meeting settings titles vertically
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.scss
Labels: ui

#1974 Implemented Orga level meeting list prototype
  client/src/app/gateways/repositories/committee-repository.service.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/base/base-menu-entry.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.html
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/config/model-subscription.ts
  client/src/app/site/pages/organization/modules/navigation/organization-navigation/organization-navigation.component.html
  client/src/app/site/pages/organization/modules/navigation/organization-navigation/organization-navigation.component.ts
  client/src/app/site/pages/organization/organization-routing.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/committees/modules/committee-components.module.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/index.ts
  client/src/app/site/pages/organization/pages/orga-meetings/orga-meetings-routing.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/orga-meetings.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.scss
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.spec.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/meeting-list-routing.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/meeting-list.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-filter/meeting-list-filter.service.spec.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-filter/meeting-list-filter.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-service.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-sort/meeting-list-sort.service.spec.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-sort/meeting-list-sort.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/orga-meetings-main/components/orga-meetings-main/orga-meetings-main.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/orga-meetings-main/components/orga-meetings-main/orga-meetings-main.component.scss
  client/src/app/site/pages/organization/pages/orga-meetings/pages/orga-meetings-main/components/orga-meetings-main/orga-meetings-main.component.spec.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/orga-meetings-main/components/orga-meetings-main/orga-meetings-main.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/orga-meetings-main/orga-meetings-main.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/modules/organization-tag-dialog/components/organization-tag-dialog.component.html
  client/src/app/ui/modules/head-bar/services/routing-state.service.ts
  client/src/app/ui/modules/meeting-time/components/meeting-time/meeting-time.component.html
  client/src/app/ui/modules/meeting-time/components/meeting-time/meeting-time.component.scss
  client/src/app/ui/modules/meeting-time/components/meeting-time/meeting-time.component.ts
Labels: feature

#2102 Sorted and indented entries in category chip select
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug

#2105 check au worker queue for fulfilling subscriptions
  client/src/app/worker/autoupdate-subscription.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: enhancement

#2050 add ability to disable autoupdate compression
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: feature

#2109 add development docs for shared worker
  DEVELOPMENT.md
  README.md
Labels: documentation

#1891 Fixed problems where template meetings were unwantedly included in l…
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.ts
Labels: low, clean up

#2113 do not display h1 warning if protocol emtpy
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
Labels: bug

#2103 Fixed meeting settings change recognition
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
Labels: bug

#2123 hide created/modified date in motion list if not filtered by it
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
Labels: feature

#2115 Update translation loader
  client/package-lock.json
  client/package.json
  client/src/app/site/modules/translations/translation-pruning-loader.ts
  client/src/assets/i18n/cs.json
  client/src/assets/i18n/de.json
  client/src/assets/i18n/en.json
  client/src/assets/i18n/es.json
  client/src/assets/i18n/fr.json
  client/src/assets/i18n/it.json
  client/src/assets/i18n/ru.json
  client/src/polyfills.ts
  client/tsconfig.json
Labels: bug, translation

#2065 request has voted state for started polls only
  client/src/app/gateways/repositories/polls/poll-repository.service/poll-repository.service.ts
  client/src/app/gateways/repositories/polls/vote-repository.service/vote-repository.service.ts
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll-controller.service/poll-controller.service.ts
  client/src/app/site/pages/meetings/modules/poll/services/vote-controller.service/vote-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
Labels: high, enhancement, performance

#2134 fix dashboard subscription committee link
  client/src/app/site/pages/organization/pages/dashboard/dashboard.subscription.ts
Labels: bug

#2136 restart autoupdate connections on reload
  client/src/app/openslides-main-module/services/app-load.service.spec.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-multiselect.service/agenda-item-multiselect.service.spec.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/worker/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate-stream.ts
  client/src/app/worker/interfaces-autoupdate.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: high, enhancement

#2141 Analog list elections can now be created again
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-dialog/assignment-poll-dialog.component.html
Labels: bug, high

#2137 fix autoupdate issues
  client/src/app/site/pages/meetings/modules/meetings-component-collector/agenda-content-object-form/components/agenda-content-object-form/agenda-content-object-form.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-main/assignment-poll-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/amendments-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/amendments.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list-main/amendment-list-main.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list-main/amendment-list-main.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list-main/amendment-list-main.component.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list-main/amendment-list-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-main/motion-poll-main.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail/participant-detail.component.ts
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
Labels: bug

#2148 fix supporter list names not displayed
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
Labels: bug

#2149 fix chip multi deselection not working
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug, high

#2156 Can now search motions by extension fields
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
Labels: bug, high
