Repository OpenSlides/openslides-client, pull requests merged in 2023-07, with the labels that each got.

#2485 Add motion workflow timestamp
  client/src/app/domain/models/motions/motion-state.ts
  client/src/app/domain/models/motions/motion.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
Labels: feature

#2477 In organization settings edit only send values that have been changed
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: bug

#2481 Put unique validator on group edit
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
Labels: bug, high

#2475 Remove assigned accounts (2456)
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
Labels: enhancement

#2480 Fix reappearing autoupdate error message
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
  client/src/app/site/services/model-request.service.ts
Labels: bug, high

#2479 fix display for new side-nav-width
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.scss
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.ts
  client/src/assets/styles/media-queries.scss
  client/src/styles.scss
Labels: bug

#2486 Remove motion PDF line number breaks if disabled
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#2483 Fix chat user names not displayed
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message/chat-group-detail-message.component.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
Labels: bug

#2489 Unit tests
  .gitignore
  client/.eslintrc.js
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/infrastructure/utils/promises/deferred.spec.ts
  client/src/app/infrastructure/utils/promises/mutex.spec.ts
Labels: tests

#2399 Remove spaces in poll entitled groups
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-meta-info/topic-poll-meta-info.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-meta-info/assignment-poll-meta-info.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-meta-information/motion-poll-meta-information.component.html
Labels: bug, ui

#2491 Unit-Tests 2023 07 04
  client/src/app/infrastructure/utils/subscription-map.spec.ts
Labels: tests

#2492 Testing: Add util tests
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/infrastructure/utils/transform-functions.spec.ts
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/infrastructure/utils/validators/is-number-range.ts
  client/src/app/infrastructure/utils/validators/validators.spec.ts
  client/src/app/ui/directives/autofocus/autofocus.directive.spec.ts
Labels: tests

#2471 Motion block detail and projector detail UI fixes
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.scss
Labels: bug

#2370 Add workflow and group settings help texts
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/workflows.module.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.scss
  client/src/app/site/pages/meetings/pages/participants/modules/groups/groups.module.ts
  client/src/styles.scss
Labels: feature

#2470 Separate motion block filter storage from motion filter storage
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/services/motion-block-detail-filter-list.service/motion-block-detail-filter-list.service.ts
Labels: bug, high

#2510 Update custom translations to work without PO file
  client/src/app/site/modules/translations/translation-parser.ts
Labels: translation, enhancement

#2520 Add ErrorMapService tests
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/gateways/error-mapping/error-map.service.spec.ts
  client/src/app/gateways/error-mapping/error-map.service.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-parse-number/poll-parse-number.pipe.spec.ts
  client/src/app/ui/pipes/time/time.pipe.spec.ts
Labels: tests

#2522 Prevent deletion of participants which are part of archived meetings
  client/src/app/gateways/presenter/get-user-related-models-presenter.service.ts
  client/src/app/gateways/presenter/get-user-scope-presenter.service.ts
  client/src/app/site/modules/user-components/services/user-delete-dialog.service.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug, high

#2523 Add storage service test
  client/src/app/gateways/storage.service.spec.ts
  client/src/app/gateways/storage.service.ts
Labels: tests

#2525 Improve test coverage
  client/src/app/gateways/error-mapping/error-map.service.spec.ts
  client/src/app/gateways/storage.service.spec.ts
Labels: tests

#2537 Add tests for presenter services
  client/karma.conf.js
  client/src/app/gateways/presenter/check-database-presenter.service.spec.ts
  client/src/app/gateways/presenter/export-meeting-presenter.service.spec.ts
  client/src/app/gateways/presenter/export-meeting-presenter.service.ts
  client/src/app/gateways/presenter/get-active-users-amount-presenter.service.spec.ts
  client/src/app/gateways/presenter/get-forwarding-meetings-presenter.service.spec.ts
  client/src/app/gateways/presenter/get-user-related-models-presenter.service.spec.ts
  client/src/app/gateways/presenter/get-user-related-models-presenter.service.ts
  client/src/app/gateways/presenter/get-user-scope-presenter.service.spec.ts
  client/src/app/gateways/presenter/get-user-scope-presenter.service.ts
  client/src/app/gateways/presenter/get-users-presenter.service.spec.ts
  client/src/app/gateways/presenter/get-users-presenter.service.ts
  client/src/app/gateways/presenter/presenter.service.spec.ts
  client/src/app/gateways/presenter/search-deleted-models-presenter.service.spec.ts
  client/src/app/gateways/presenter/search-users-presenter.service.spec.ts
  client/src/app/gateways/presenter/search-users-presenter.service.ts
  client/src/app/gateways/presenter/server-time-presenter.service.spec.ts
Labels: tests

#2539 Sort point of order categories in dialog by alphabetical order
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/components/point-of-order-dialog/point-of-order-dialog.component.ts
Labels: enhancement

#2557 Testing services history presenter
  client/src/app/gateways/presenter/get-users-presenter.service.spec.ts
  client/src/app/gateways/presenter/history-presenter.service.spec.ts
  client/src/app/gateways/presenter/history-presenter.service.ts
Labels: tests

#2553 Build in point of order restriction on closed
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature

#2545 Make deselect all also deselect filtered list items
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
Labels: bug

#2563 Fix agenda show deleted items
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
Labels: bug

#2542 Fix poll pdf exports
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll-pdf.service/topic-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-pdf.service/assignment-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-pdf.service/motion-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
Labels: bug, high

#2541 Fix motion submitter bugs
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-submitters/motion-manage-submitters.component.ts
  client/src/app/ui/modules/search-selector/components/list-search-selector/list-search-selector.component.ts
Labels: bug, high

#2535 Fix voting banner style
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.scss
  client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.scss
  client/src/app/site/services/theme.service.ts
  client/src/assets/styles/global-components-style.scss
Labels: bug, high

#2534 Fix default daterange value for meeting create
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, high

#2543 Fix motion list multiselect tag dialog
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#2570 Fix motion info dialog
  client/src/app/gateways/actions/action.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
Labels: bug, high

#2571 Fix motion multiselect unset category
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
Labels: bug

#2581 Apply 7d490224b for conflict-free merging
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: clean up
