Repository OpenSlides/openslides-client, pull requests merged in 2023-05, with the labels that each got.

#2242 integration test add language to meeting create request
  client/tests/Dockerfile.test
  client/tests/integration/helpers/request.ts
  client/tests/package-lock.json
  client/tests/package.json
Labels: bug

#2249 improve agenda sort filter
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/agenda-sort.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.scss
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.ts
Labels: bug

#2256 fix missing autoupdate for amendment change recommendations
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
Labels: bug, high

#2245 Rename fields
  client/src/app/domain/definitions/meeting-settings-defaults.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: clean up

#2264 apply change recommendations to motion title on forward
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: bug, high

#2268 Remove commit message guide from README
  README.md
Labels: documentation

#2269 amendment list pdf export with nested lists fix
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
Labels: bug, high

#2273 fix amendment change recos missing in pdf export
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/services/motion-export-dialog.service.ts
Labels: bug

#2275 Add maxLength 32 to pronoun inputs
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: feature

#2237 set autopilot min height
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.html
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.ts
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/modules/global-headbar/global-headbar.service.ts
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.scss
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
  client/src/app/site/pages/organization/modules/navigation/organization-navigation-wrapper/organization-navigation-wrapper.component.scss
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.html
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.ts
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.html
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.ts
Labels: bug

#2284 Fixed darkmode sidebar background
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.html
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
  client/src/assets/styles/global-components-style.scss
Labels: bug, high, ui

#2280 Added non-binary gender options
  client/src/app/domain/models/users/user.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: feature

#2293 fix directly opening motion from another meeting
  client/src/app/site/pages/meetings/pages/motions/components/motion-main/motion-main.component.ts
Labels: bug, high

#2291 fix pdf amendment export change recos not displayed
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
Labels: bug

#2258 Made amendment free text show on projection
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
Labels: bug, high

#2262 use nanocosmos player insted of iframe
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
Labels: bug, high

#2302 Made assignment subscription load the users behind the candidates
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
Labels: bug

#2299 Made pronoun field validation error update correctly
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: enhancement

#2297 Added sequential number filter
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-sort.service/motion-list-sort.service.ts
Labels: enhancement

#2294 fix change reco delete
  client/src/app/infrastructure/definitions/relations/relations.ts
Labels: bug

#2292 fix editorial version closed on motion update
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/base/base-motion-detail-child.component.ts
Labels: bug, high

#2305 Fixed wrong vote delegation updates
  client/src/app/domain/models/users/user.ts
  client/src/app/site/services/relation-manager.service.ts
Labels: bug, high

#2301 Made motion title update
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.ts
Labels: bug

#2154 global search
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.ts
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/services/global-search.service.ts
Labels: waiting

#2320 fix overflow problems
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.scss
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
Labels: bug, critical

#2337 Implement create child item button on agenda
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.ts
Labels: feature, low
