Repository OpenSlides/openslides-client, pull requests merged in 2023-06, with the labels that each got.

#2342 improve search selector
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#2349 Fixed motion block views
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-list/motion-block-list.component.ts
Labels: bug, ui

#2314 fix missing motion numbers
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
Labels: bug

#2317 Made autopilot title link point to new tab with mediafiles
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
Labels: bug, low

#2318 Made user scope requesting method filter for the operator
  client/src/app/site/services/user.service.ts
Labels: bug

#2319 Rewrote star icon setting title
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: low, enhancement

#2325 Remove unnecessary spaces from entitled groups information
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-meta-information/motion-poll-meta-information.component.html
Labels: bug, ui

#2328 Make LOS content component use speakerToDelete consistently
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug

#2329 make mediafile folders accessable via url
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.ts
Labels: bug

#2356 Limit width of slide meeting title
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.html
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.scss
Labels: bug, low, ui

#2331 fix sidenav viewport breakpoints
  client/src/app/site/services/view-port.service.ts
Labels: bug

#2355 Rearrange tooltip positions so that they dont overlap
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/info/components/info-actions/info-actions.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-dialog/topic-poll-dialog.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/custom-translation/custom-translation.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list/category-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-list/motion-block-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/message-controls/message-controls.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/ui/modules/icon-container/components/icon-container/icon-container.component.html
  client/src/app/ui/modules/icon-container/components/icon-container/icon-container.component.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
Labels: enhancement

#2341 Make motion forward dialog load necessary information
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
Labels: bug, high

#2344 do not search for id fields in list search service
  client/src/app/ui/modules/list/services/list-search.service.ts
Labels: bug

#2346 package updates and replace momentjs with date-fns
  client/package-lock.json
  client/package.json
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/infrastructure/utils/lang-to-locale.ts
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/ui/modules/meeting-time/components/meeting-time/meeting-time.component.html
  client/src/app/ui/modules/openslides-date-adapter/openslides-date-adapter.module.ts
  client/src/app/ui/modules/openslides-date-adapter/openslides-date-adapter.ts
  client/src/app/ui/pipes/localized-date/localized-date.pipe.ts
Labels: low, clean up

#2364 fix scrollbar toggle in chromium
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
Labels: bug

#2359 Hotfix: Make category detail sort show sequential number instead of id
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.html
Labels: bug

#2372 fix meeting clone
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, critical

#2203 Expanded motion list filter props
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: clean up

#2334 Fix ellipses in list title columns
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.scss
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/components/assignment-list/assignment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-list/motion-block-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.scss
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.scss
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.scss
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/assets/styles/tables.scss
  client/src/styles.scss
Labels: bug, ui

#2374 Improve pdf header meeting date
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: high, enhancement, ui

#2379 Fix cancel theme change
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.ts
Labels: bug

#2385 Improve internal projectors
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/components/projector-list-entry/projector-list-entry.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/components/projector-list/projector-list.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/components/projector-list/projector-list.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/projector-list.module.ts
Labels: enhancement

#2388 Fix meeting settings one-letter abbreviation bug
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
Labels: bug, critical

#2390 Fix TypeError in list of speakers
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-list-of-speakers.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
Labels: bug

#2392 Fix topic poll creation dialog
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-dialog/topic-poll-dialog.component.html
Labels: bug, critical

#2396 Ensure that LOS is always accessible via the list…
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/components/assignment-list/assignment-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-list/motion-block-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-list/workflow-list.component.html
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-permission.service/motion-permission.service.ts
  client/src/app/site/pages/meetings/pages/polls/modules/poll-list/components/poll-list/poll-list.component.html
Labels: bug

#2296 client sso implementation
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/gateways/auth-adapter.service.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.scss
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
  client/src/app/site/services/auth.service.ts
Labels: feature

#2417 Add new SAML settings and allow users to be filtered by presence of saml_id
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: feature, high

#2421 Format SAML config textfield content
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: high, enhancement

#2427 Hotfix: Stop motion edit from resetting upon window resize
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
Labels: bug, critical

#2431 Hotfix: Properly display Organization mediafiles
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.ts
Labels: bug, high

#2400 Fix calender bug that displays timeless meetings as ended
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
Labels: bug

#2404 Remove participant project option from list view
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug

#2405 Fix participants list mobile present checkbox
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug

#2408 Stop long titles from displacing icon suffixes
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.scss
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.scss
Labels: bug, low, ui

#2338 Make participant create wizard update user correctly
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug, low

#2452 Fix nominal poll result table
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
Labels: bug, critical

#2450 Fix broken participant creation if vote_weight enabled
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug, critical

#2454 Fix vote dialog vote count
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
Labels: bug, high

#2295 Improve email not sent error messages
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/services/user-controller.service.ts
Labels: bug

#2434 Polish SSO-SAML
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/modules/user-components/components/user-multiselect-actions/user-multiselect-actions.component.html
  client/src/app/site/modules/user-components/components/user-multiselect-actions/user-multiselect-actions.component.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.scss
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/pages/login/pages/login-mask/login-mask.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-multiselect-actions/participant-multiselect-actions.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-multiselect-actions/participant-multiselect-actions.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-multiselect-actions/participant-multiselect-actions.component.spec.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-multiselect-actions/participant-multiselect-actions.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-search/account-list-search.service.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
  client/src/app/site/pages/organization/services/organization-settings.service.ts
  client/tests/integration/helpers/request.ts
  client/tests/integration/login.spec.ts
Labels: high, enhancement

#2440 Add unit tests
  .github/workflows/build.yml
  Dockerfile.dev
  client/karma.conf.js
  client/package-lock.json
  client/package.json
  client/src/app/site/services/active-filters.service.spec.ts
  client/src/app/ui/directives/autofocus/autofocus.directive.spec.ts
  client/src/app/ui/modules/chip/components/chip/chip.component.spec.ts
  client/src/app/ui/modules/chip/components/chip/chip.component.ts
  client/src/app/ui/pipes/time/time.pipe.spec.ts
Labels: tests

#2465 Add unit tests and remove unneccessary pipes
  client/package.json
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/ui/pipes/async/openslides-async.pipe.spec.ts
  client/src/app/ui/pipes/async/openslides-async.pipe.ts
  client/src/app/ui/pipes/entries/entries.pipe.spec.ts
  client/src/app/ui/pipes/pipes.module.ts
  client/src/app/ui/pipes/reverse/reverse.pipe.spec.ts
  client/src/app/ui/pipes/slice/openslides-slice.pipe.spec.ts
  client/src/app/ui/pipes/slice/openslides-slice.pipe.ts
  client/src/app/ui/pipes/trust/trust.pipe.spec.ts
Labels: tests

#2468 New unit tests for pipes
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-key-verbose/poll-key-verbose.pipe.spec.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-parse-number/poll-parse-number.pipe.spec.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-percent-base/poll-percent-base.pipe.spec.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll.service.ts
  client/src/app/ui/pipes/localized-date-range/localized-date-range.pipe.spec.ts
  client/src/app/ui/pipes/localized-date-range/localized-date-range.pipe.ts
  client/src/app/ui/pipes/localized-date/localized-date.pipe.spec.ts
  client/src/app/ui/pipes/localized-date/localized-date.pipe.ts
Labels: tests

#2432 Multiple bug fixes for template field removal
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/motions/motion.ts
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.scss
  client/src/app/site/pages/meetings/modules/poll/services/vote-controller.service/vote-controller.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/motion-slide-data.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.scss
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-paragraphbased-amendment/motion-paragraphbased-amendment.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
Labels: bug
