Repository OpenSlides/openslides-client, pull requests merged in 2024-11, with the labels that each got.

#4308 Update permission for use of get-forwarding-meetings
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: bug, high

#4307 Create two new participant filters
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/base/base-view-model.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: enhancement, Schrödinger

#4287 Delgations and vote weigh optimizations
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/participant-detail.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.html
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.scss
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.ts
Labels: enhancement, Schrödinger

#4324 Fix bug: layout error in mobile view for election polls
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
Labels: bug, high, good first issue

#4334 Fix bug: second scrollbar appears in chat
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-list/chat-group-list.component.scss
Labels: bug, good first issue

#4333 Sort structure levels by name in participant-list
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#4329 Use isUserPresent to include votingArea template
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
Labels: bug, high

#4336 Fix participant detail view without delegation
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
Labels: bug, high

#4222 Fix breadcrumb in global search
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
Labels: bug

#4341 Motion create save button not active
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
Labels: bug, high

#4347 Improve meeting mediafile `can_access` check performance
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/gateways/repositories/meeting-mediafile/meeting-mediafile-repository.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-mediafile.ts
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-meeting-mediafile.ts
Labels: performance, staging

#4355 Update translations
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: translation, staging

#4352 Cleanup subscriptions : move idField and fieldset next to each other
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/mediafiles/mediafiles.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/site/pages/meetings/pages/projectors/projectors.subscription.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
  client/src/app/site/pages/organization/organization.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/accounts.subscription.ts
  client/src/app/site/pages/organization/pages/organization-tags/organization-tags.subscription.ts
Labels: clean up

#4351 Fix projection flicker on data change
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.html
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.ts
Labels: bug

#4353 Fix motion favorite icon for public access users
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.html
Labels: good first issue, enhancement

#4354 Add showReason method and handle p tags in reason
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.ts
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
Labels: bug

#4350 Add warning text for public access setting
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: good first issue, enhancement, Lorentz

#4125 Fix time menu click area
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
Labels: bug, ui

#4312 Fix display of amendment from amendment
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/amendment-create-wizard/amendment-create-wizard.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/amendment-create-wizard/amendment-create-wizard.component.ts
Labels: bug

#4357 Fix login buttons positioning for public access and SSO
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
Labels: bug, good first issue, Lorentz

#4365 Allow to add agenda item if perm agenda can manage
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
Labels: bug, high

#4369 Dependabot ignore angular major updates
  .github/dependabot.yml
Labels: dependencies

#4343 Add line numbers to empty paragraphs
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/assets/styles/tiptap.scss
Labels: bug, high

#4377 Remove motion-import, BaseImportService, BaseImportListComponent
  client/src/app/site/base/base-import-list.component.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/pages/meetings/pages/motions/motions-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/components/motion-import-list/motion-import-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/components/motion-import-list/motion-import-list.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/components/motion-import-list/motion-import-list.component.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/components/motion-import-list/motion-import-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/import/category-import-helper.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/import/motion-block-import-helper.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/import/tag-import-helper.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/motion-import-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/motion-import.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/services/motion-import.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/services/motion-import.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/services/motions-import-service.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
Labels: clean up

#4383 Update saml attr setting formatting function
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
Labels: bug

#4205 Allow to edit certain users with two meetings
  client/src/app/gateways/presenter/get-user-editable-presenter.service.ts
  client/src/app/gateways/presenter/index.ts
  client/src/app/gateways/presenter/presenter.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/services/user.service.ts
Labels: feature, Schrödinger

#4420 Small layout fixes to meeting setting: public access
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: bug, staging
