Repository OpenSlides/openslides-client, pull requests merged in 2024-07, with the labels that each got.

#3808 Fix motion polls
  client/angular.json
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.scss
Labels: bug, critical, ui

#3688 Prevent the error (in console) from forwarded motions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug

#3799 Fix autopilot assignment poll missing user info
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
Labels: bug

#3790 Fix poll display on delegation settings change
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/poll-cannot-vote-message/poll-cannot-vote-message.component.ts
Labels: bug

#3796 Fix vote components using wrong change detection strategy
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
Labels: performance

#3813 Fix several Layout issues
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.scss
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug, staging

#3819 Fix resubscribe to poll detail subscription
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-meta-info/assignment-poll-meta-info.component.ts
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
Labels: bug, staging

#3832 Update translations
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-merge-dialog/account-merge-dialog.component.html
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#3824 Cleanup of linter warnings
  client/.eslintrc.js
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/gateways/repositories/chat/chat-group-repository.service/chat-group-repository.service.ts
  client/src/app/gateways/repositories/chat/chat-message-repository.service/chat-message-repository.service.ts
  client/src/app/gateways/repositories/committee-repository.service.ts
  client/src/app/gateways/repositories/groups/group-repository.service.ts
  client/src/app/gateways/repositories/list-of-speakers/list-of-speakers-repository.service.ts
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-block-repository.service/motion-block-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-category-repository.service/motion-category-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-change-recommendation-repository.service/motion-change-recommendation-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-comments/motion-comment-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-comments/motion-comment-section-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-editor-repository/motion-editor-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-state-repository.service/motion-state-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-submitter-repository.service/motion-submitter-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-workflow-repository.service/motion-workflow-repository.service.ts
  client/src/app/gateways/repositories/motions/motion-working-group-speaker-repository/motion-working-group-speaker-repository.service.ts
  client/src/app/gateways/repositories/motions/personal-note-repository.service/personal-note-repository.service.ts
  client/src/app/gateways/repositories/motions/util.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/gateways/repositories/polls/option-repository.service/option-repository.service.ts
  client/src/app/gateways/repositories/polls/vote-repository.service/vote-repository.service.ts
  client/src/app/gateways/repositories/projections/projection-repository.service.ts
  client/src/app/gateways/repositories/projector-countdowns/projector-countdown-repository.service.ts
  client/src/app/gateways/repositories/projector-messages/projector-message-repository.service.ts
  client/src/app/gateways/repositories/projectors/projector-repository.service.ts
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/gateways/repositories/tags/tag-repository.service.ts
  client/src/app/gateways/repositories/topics/topic-repository.service.ts
  client/src/app/infrastructure/annotations/data-transaction.ts
  client/src/app/infrastructure/errors/process.error.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/infrastructure/utils/import/base-import-handler.ts
  client/src/app/infrastructure/utils/import/base-main-import-handler.ts
  client/src/app/infrastructure/utils/import/base-side-import-handler.ts
  client/src/app/infrastructure/utils/import/import-step.ts
  client/src/app/infrastructure/utils/import/static-additional-import-handler.ts
  client/src/app/infrastructure/utils/import/static-main-import-handler.ts
  client/src/app/infrastructure/utils/import/users/user-import-helper.ts
  client/src/app/infrastructure/utils/validators/is-unique-among.ts
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/base/base-list-view.component.ts
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/modules/global-headbar/global-headbar.service.ts
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.ts
  client/src/app/site/modules/wait-for-action-dialog/services/wait-for-action-dialog.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/poll-cannot-vote-message/poll-cannot-vote-message.component.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
Labels: clean up

#3821 New design for motion polls
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.scss
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll/motion-poll.component.html
Labels: enhancement

#2890 Replace tinymce with tiptap
  README.md
  client/README.md
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/base/base.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/start.module.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/definitions/tinymce-config.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/motion-change-recommendation-dialog/components/motion-content-change-recommendation-dialog/motion-content-change-recommendation-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/motion-change-recommendation-dialog/components/motion-content-change-recommendation-dialog/motion-content-change-recommendation-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/modules/motion-change-recommendation-dialog/motion-change-recommendation-dialog.module.ts
  client/src/app/site/pages/meetings/pages/motions/styles/motion-common-styles.scss
  client/src/app/ui/base/base-form-control.ts
  client/src/app/ui/modules/editor/components/editor-embed-dialog/editor-embed-dialog.component.html
  client/src/app/ui/modules/editor/components/editor-embed-dialog/editor-embed-dialog.component.scss
  client/src/app/ui/modules/editor/components/editor-embed-dialog/editor-embed-dialog.component.ts
  client/src/app/ui/modules/editor/components/editor-html-dialog/editor-html-dialog.component.html
  client/src/app/ui/modules/editor/components/editor-html-dialog/editor-html-dialog.component.scss
  client/src/app/ui/modules/editor/components/editor-html-dialog/editor-html-dialog.component.ts
  client/src/app/ui/modules/editor/components/editor-image-dialog/editor-image-dialog.component.html
  client/src/app/ui/modules/editor/components/editor-image-dialog/editor-image-dialog.component.scss
  client/src/app/ui/modules/editor/components/editor-image-dialog/editor-image-dialog.component.ts
  client/src/app/ui/modules/editor/components/editor-link-dialog/editor-link-dialog.component.html
  client/src/app/ui/modules/editor/components/editor-link-dialog/editor-link-dialog.component.scss
  client/src/app/ui/modules/editor/components/editor-link-dialog/editor-link-dialog.component.ts
  client/src/app/ui/modules/editor/components/editor/editor.component.html
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
  client/src/app/ui/modules/editor/components/editor/extensions/clear-textcolor.ts
  client/src/app/ui/modules/editor/components/editor/extensions/highlight.ts
  client/src/app/ui/modules/editor/components/editor/extensions/iframe.ts
  client/src/app/ui/modules/editor/components/editor/extensions/image-resize.ts
  client/src/app/ui/modules/editor/components/editor/extensions/office.ts
  client/src/app/ui/modules/editor/components/editor/extensions/ordered-list.ts
  client/src/app/ui/modules/editor/editor.module.ts
  client/src/assets/styles/tiptap.scss
  client/src/assets/tinymce/langs/cs.js
  client/src/assets/tinymce/langs/de.js
  client/src/assets/tinymce/langs/en.js
  client/src/assets/tinymce/langs/ru.js
  client/src/styles.scss
  client/tests/integration/page-objects/meeting/home/edit.ts
Labels: feature, high, Röntgen

#3853 Fix tiptap html list cleanup
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
Labels: bug, staging

#3864 Fix amendment create checkboxes
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
Labels: bug, staging

#3865 Fix amendment edit editors not displayed
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.ts
Labels: bug, staging

#3863 Support `{background-}color: inherit` in htmltopdf
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
Labels: bug, staging

#3868 Normalize editor colors on cleanup
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
Labels: bug, staging

#3876 Change orga level media files relation to exclusive list
  client/src/app/infrastructure/definitions/relations/relations.ts
Labels: bug, staging

#3839 Update angular to v18
  .github/dependabot.yml
  Dockerfile
  Dockerfile.dev
  client/.eslintrc.js
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/gateways/export/file-export.service/file-export.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/infrastructure/utils/lang-to-locale.ts
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.spec.ts
  client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.spec.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/applause-particle-display/applause-particle-display.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/applause-particle-display/applause-particle-display.component.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/applause-particle-display/particle-options.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/interaction-container.module.ts
  client/src/app/site/pages/meetings/pages/interaction/services/broadcast.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-export.service/mediafile-list-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/site/services/color.service.ts
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.ts
  client/src/app/ui/pipes/localized-date-range/localized-date-range.pipe.spec.ts
  client/src/app/ui/pipes/localized-date-range/localized-date-range.pipe.ts
  client/src/app/worker/http/http-subscription-sse.spec.ts
  client/src/assets/styles/global-components-style.scss
  client/src/assets/styles/theme-styles.scss
  client/src/assets/styles/themes/default-dark.scss
  client/src/assets/styles/themes/default-light.scss
  client/src/assets/styles/themes/typography.scss
  client/src/e2e-imports.module.ts
  client/src/styles.scss
  client/tsconfig.json
Labels: dependencies, staging

#3898 Add missing 's' tag to html to pdf
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
Labels: bug, staging

#3897 Fix committee admin account list
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/ui/directives/perms/cml-perms.directive.spec.ts
  client/src/app/ui/directives/perms/cml-perms.directive.ts
  client/src/app/ui/directives/perms/oml-perms.directive.spec.ts
Labels: bug, staging

#3902 Add availableAdmins and use all account users for it
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, staging

#3879 Cleanup controlflow
  client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.html
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/detail-view/detail-view.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/speaker-button/components/speaker-button/speaker-button.component.html
  client/src/app/site/pages/meetings/modules/poll/components/check-input/check-input.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/action-bar/components/action-bar/action-bar.component.html
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-upload/components/file-upload/file-upload.component.html
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/sidenav/components/image/image.component.html
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.html
Labels: clean up, performance

#3635 Add new dialog options to motion forward dialog
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/motion-forward-dialog.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: feature, Becquerel

#3877 Fix projector buttons not using contrast color for icon
  client/src/assets/styles/themes/var-overwrites.scss
Labels: bug, ui

#3931 Add missing provider
  client/src/app/openslides-main-module/openslides-main.module.ts
Labels: bug, critical, staging

#3935 Change chyron style
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.scss
Labels: enhancement, los-extension

#3939 Fix account list performance
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
Labels: bug, high, staging

#3942 Fix meeting amount on account detail
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
Labels: bug, staging

#3938 Linter fixes
  client/.eslintrc.js
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
  client/src/app/infrastructure/utils/transform-functions.ts
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.html
  client/src/app/site/modules/user-components/components/user-password-form/user-password-form.component.html
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.html
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.html
  client/src/app/site/pages/meetings/modules/projector/projector.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-list/agenda-item-list.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/interaction-container/interaction-container.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
  client/src/app/ui/modules/grid/grid/grid.component.html
  client/src/app/ui/modules/grid/tile/tile.component.ts
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
  client/src/app/ui/modules/openslides-overlay/components/overlay/overlay.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
  client/src/app/ui/modules/sidenav/components/image/image.component.html
  client/src/app/ui/modules/sidenav/components/image/image.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.html
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.ts
Labels: clean up, accessibility

#3933 Fix user info not displayed on autopilot
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.html
Labels: bug

#3936 Change general approval option order
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
Labels: enhancement, Strutt
