Repository OpenSlides/openslides-client, pull requests merged in 2024-05, with the labels that each got.

#3624 FIX Search Dialouge Layout
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
Labels: bug, low, ui

#3606 Add committee selector to motion meta data submitters
  client/src/app/gateways/presenter/get-forwarding-committees-presenter.service.ts
  client/src/app/gateways/presenter/presenter.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: feature, Lorentz

#3637 Fix TypeError in console when deleting active speaker
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
Labels: bug

#3628 Link vote result to poll detail view
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll/assignment-poll.component.html
Labels: feature, low

#3626 Fix list views not switching language
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
Labels: bug, low

#3649 Meeting list csv export
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-export.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-service.module.ts
Labels: feature

#3653 Fix amendment default projector preselection
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: bug

#3652 Fix unexpected present status change on user update
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
Labels: bug

#3648 Fix motion styling around long list of tags
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.scss
Labels: ui

#3644 Cleanup of linter warnings
  client/src/app/gateways/actions/action.ts
  client/src/app/gateways/base-icc-gateway.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/gateways/presenter/history-presenter.service.ts
  client/src/app/gateways/repositories/agenda/agenda-item-repository.service.ts
  client/src/app/gateways/repositories/assignments/assignment-candidate-repository.service/assignment-candidate-repository.service.ts
  client/src/app/gateways/repositories/assignments/assignment-repository.service/assignment-repository.service.ts
  client/src/app/gateways/repositories/base-agenda-item-and-list-of-speakers-content-object-repository.ts
  client/src/app/gateways/repositories/base-agenda-item-content-object-repository.ts
  client/src/app/gateways/repositories/base-list-of-speakers-content-object-repository.ts
  client/src/app/gateways/repositories/base-meeting-related-repository.ts
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.ts
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/check-input/check-input.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/voting.service/voting.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-detail-content/topic-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-dialog/topic-poll-dialog.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-multiselect.service/agenda-item-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/agenda/view-models/view-agenda-item.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/services/motion-block-sort.service/motion-block-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/services/motion-detail-view-originurl.service/motion-detail-view-originurl.service.ts
Labels: clean up

#3643 Remove deprecated method meetingSettingService()
  client/src/app/site/pages/meetings/base/base-meeting-list-view.component.ts
  client/src/app/site/pages/meetings/base/base-meeting.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-form/assignment-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.ts
  client/src/app/site/services/auth-check.service.ts
  client/src/app/ui/modules/search-selector/components/repo-search-selector/repo-search-selector.component.ts
Labels: clean up

#3663 Fix user count not working
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.html
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.scss
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/meeting-info.module.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/services/count-users-statistics.service.ts
Labels: bug, staging

#3647 Fix accesibility linter warnings
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-info-dialog/agenda-item-info-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-list/category-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-create-dialog/components/motion-block-create-dialog/motion-block-create-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-edit-dialog/components/motion-block-edit-dialog/motion-block-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/tags/components/tag-list/tag-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
  client/src/app/ui/modules/openslides-overlay/components/overlay/overlay.component.html
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
Labels: accessibility

#3632 Fix too many updates for meetingSettingsService.get()
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings.service.ts
Labels: bug

#3665 Fix projector dialog choice deselection
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
Labels: bug, staging

#3662 Fix wrong formatting in date export
  client/src/app/site/pages/meetings/services/meeting-controller.service.ts
Labels: bug, staging

#3667 Fix amendment detail view error
  client/src/app/domain/models/motions/motion.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: bug, staging

#3668 Hide committee submitter select field if empty
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.ts
Labels: bug, staging

#3669 Suppress console error on not ready conection cancel
  client/src/app/site/services/autoupdate/autoupdate.service.ts
Labels: bug, low

#3619 Change appearance of several detail views
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.scss
  client/src/assets/styles/mixins/detail-view-appearance.scss
Labels: enhancement

#3638 Improve ModelRequestService
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/pages/organization/organization.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.html
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
  client/src/app/site/services/model-request.service.ts
  client/src/app/ui/modules/search-selector/components/repo-search-selector/repo-search-selector.component.ts
Labels: clean up, performance

#3680 Fix type error in the motion workflow page
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.ts
Labels: bug, high

#3590 Hide empty space if three dot menu is not shown
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/ui/modules/scrolling-table/directives/scrolling-table-cell.directive.ts
Labels: bug

#3690 Fix osPerm directive not updating permissions on group change
  client/src/app/site/services/operator.service.ts
Labels: bug

#3676 Remove history mode
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.scss
  client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.spec.ts
  client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.scss
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
  client/src/app/site/pages/meetings/pages/history/definitions/index.ts
  client/src/app/site/pages/meetings/pages/history/definitions/position.ts
  client/src/app/site/pages/meetings/pages/history/history.module.ts
  client/src/app/site/pages/meetings/pages/history/services/history.service.spec.ts
  client/src/app/site/pages/meetings/pages/history/services/history.service.ts
  client/src/app/site/pages/meetings/services/meeting-active-filters.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/tests/integration/meeting/motion/history.spec.ts
Labels: clean up

#3592 Add spokesperson to motion xlsx export
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: feature

#3683 Guest user meeting access
  client/package-lock.json
  client/package.json
  client/src/app/gateways/base-icc-gateway.service.ts
  client/src/app/gateways/notify.service.ts
  client/src/app/site/guards/auth.guard.ts
  client/src/app/site/guards/permission.guard.ts
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/pages/meetings/meetings-routing.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/components/meetings-navigation-wrapper/meetings-navigation-wrapper.component.ts
  client/src/app/site/pages/meetings/services/active-meeting-id.service.ts
  client/src/app/site/pages/meetings/services/active-meeting.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/services/auth-check.service.ts
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/openslides-router.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/site/services/reroute.service.ts
  client/src/app/site/site-routing.module.ts
  client/tests/integration/login.spec.ts
Labels: feature

#3695 Wait until delegation loaded before setting poll ready
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/services/operator.service.ts
Labels: bug, high

#3708 Fix LoS speaker order
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug, critical

#3654 Add member number
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/domain/models/users/user.export.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/export/participants-export-example.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/export/csv-export-example.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-search/account-list-search.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: feature, Schrödinger

#3692 Improve additional submitters committee select
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, high, staging, Lorentz

#3686 Add new setting to forbid voting if delegated
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/voting.service/voting.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature, staging, Becquerel

#3700 Fix new styling
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.scss
Labels: bug, ui, staging

#3717 Personal info and Organisation specific info UI Adjustments
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
Labels: ui, staging, Zeeman

#3720 Fix missing buttons in LoS
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
Labels: bug, staging
