Repository OpenSlides/openslides-client, pull requests merged in 2024-06, with the labels that each got.

#3718 Fix missing buttons in LoS, motion/amendments create and support button
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-permission.service/motion-permission.service.ts
Labels: bug, staging

#3736 Updated translations
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-import/services/motion-import.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-permission.service/motion-permission.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-export.service.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/import-list.module.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#3691 update chyron, add agenda item and new chyron type
  client/src/app/domain/models/projector/projector.ts
  client/src/app/gateways/repositories/projectors/projector-repository.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/definitions.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/services/projection-dialog.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/components/current-speaker-chyron-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/current-speaker-chyron-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaker-chyron-slide/current-speaker-chyron-slide.module.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/services/current-speaker-chyron-slide.service/current-speaker-chyron-slide.service.ts
  client/src/app/site/pages/meetings/pages/projectors/services/projector-controller.service.ts
Labels: enhancement, los-extension, staging

#3744 Fix chyron with current backend
  client/src/app/gateways/repositories/projectors/projector-repository.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/definitions.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/services/projection-dialog.service.ts
  client/src/app/site/pages/meetings/pages/projectors/services/projector-controller.service.ts
Labels: bug, staging

#3756 Show delegation if delegations are active
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.html
Labels: bug, staging

#3754 Fix language switch
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-filter.service/committee-filter.service.ts
Labels: bug, low

#3762 Remove hard coded background color from motion slide
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.scss
Labels: bug, ui

#3765 Fix meeting reload
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/window-visibility.service.ts
Labels: bug

#3769 Projection dialog display current options
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
Labels: enhancement

#3761 Small fix for use getPollVoteTitle without currentProjection
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
Labels: bug

#3775 Fix missing subscription in scrolling table cell
  client/src/app/ui/modules/scrolling-table/directives/scrolling-table-cell.directive.ts
Labels: bug

#3771 Show additional_submitter in amendment-list
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
Labels: enhancement, Lorentz

#3774 Update typescript to 5.1
  client/package-lock.json
  client/package.json
  client/src/app/domain/fieldsets/misc.ts
  client/src/app/site/base/base-sort.service/base-sort.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import/topic-import.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/directives/import-list-first-tab.directive.spec.ts
  client/src/app/ui/modules/import-list/directives/import-list-first-tab.directive.ts
  client/src/app/ui/modules/import-list/directives/import-list-last-tab.directive.spec.ts
  client/src/app/ui/modules/import-list/directives/import-list-last-tab.directive.ts
  client/src/assets/styles/default-classes.scss
Labels: dependencies

#3782 Update Node version in Dockerfiles
  Dockerfile
  Dockerfile.dev
Labels: dependencies

#3783 Migrate ngx-pwa LocalStorage to StorageMap
  client/src/app/gateways/storage.service.spec.ts
  client/src/app/gateways/storage.service.ts
Labels: dependencies

#3778 Fix missing translation of start/end date in meeting export
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-export.service.ts
Labels: bug

#3788 Fix meeting-list sort/search storage key strs
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-sort/meeting-list-sort.service.ts
Labels: bug

#3786 Fix problem with limited spokespersons in xlsx export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug, Röntgen

#3781 Fix countdown controls layout
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.scss
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/countdown-controls/countdown-controls.component.scss
Labels: bug

#3773 Fix style of the home page
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.scss
Labels: bug, ui

#3770 Change fallback appearence, icon, no banner
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.html
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.scss
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.ts
  client/src/app/site/modules/global-headbar/global-headbar.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
Labels: enhancement

#3763 Fix of the datepicker reopen problem
  client/src/app/ui/modules/datepicker/components/base-datepicker/base-datepicker.component.ts
  client/src/app/ui/modules/datepicker/components/datepicker/datepicker.component.html
  client/src/app/ui/modules/datepicker/components/datepicker/datepicker.component.ts
  client/src/app/ui/modules/datepicker/components/daterangepicker/daterangepicker.component.html
  client/src/app/ui/modules/datepicker/components/daterangepicker/daterangepicker.component.ts
Labels: bug

#3767 Fix wrong active projected button status
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
Labels: bug

#3792 Filter accounts by meeting
  client/src/app/site/pages/organization/pages/accounts/accounts-routing.module.ts
  client/src/app/site/pages/organization/pages/accounts/accounts.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list-main/account-list-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/committees/modules/services/meeting.service.ts
Labels: enhancement, Curie

#3747 Show sort-option for vote weight if vote weight is active
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort/participant-list-sort.service.ts
Labels: bug
