Repository OpenSlides/openslides-client, pull requests merged in 2024-01, with the labels that each got.

#3120 Fix access group setting in mediafiles
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
Labels: bug

#3122 Fix motion block toolbar
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.scss
  client/src/app/ui/modules/head-bar/components/head-bar/head-bar.component.scss
Labels: bug, ui

#3126 Fix preview on submitter edit
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-submitters/motion-manage-submitters.component.html
Labels: bug

#3115 Create structure level buttons in projector
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: feature

#3123 Stop motion list from showing forwarded motions
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
Labels: bug, high

#3132 Fix a problem with navigation back from structure level
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
  client/src/app/site/pages/meetings/pages/participants/participants-routing.module.ts
Labels: bug

#3135 Fix NullInjectorErrors
  client/src/app/site/base/base-import-list.component.ts
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/base/base-via-backend-import-list-meeting.component.ts
  client/src/app/site/base/base-via-backend-import-list.component.ts
  client/src/app/site/pages/meetings/base/base-meeting-filter-list.service.ts
  client/src/app/site/pages/meetings/base/base-meeting.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/services/topic-poll-pdf.service/topic-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import/topic-import.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/services/assignment-poll-pdf.service/assignment-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-pdf.service/motion-poll-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/components/participant-import-list/participant-import-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.ts
Labels: bug, high

#3124 Change group selection field order
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/chat/modules/chat-group-dialog/components/chat-group-dialog/chat-group-dialog.component.html
  client/src/app/site/pages/meetings/pages/chat/modules/chat-group-dialog/components/chat-group-dialog/chat-group-dialog.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: enhancement

#3133 Add a use color checkbox in structure level
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.ts
Labels: feature

#3144 Add Help-Text to settings
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature

#3142 Fix meeting mediafile quickedit
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
Labels: bug

#3138 Fix motion headbar behaviour with long neighbour motion titles
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
Labels: bug, low

#3145 Add Filter, Search and multi-select Options for participant-list
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/services/structure-level-controller.service.ts
Labels: feature

#3121 Fix motion block slide recommendation ellipsis
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
Labels: bug, ui

#3131 Interposed questions
  client/src/app/domain/models/speakers/speaker-state.ts
  client/src/app/domain/models/speakers/speaker.ts
  client/src/app/domain/models/speakers/speech-state.ts
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/gateways/repositories/speakers/speaker.action.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.spec.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/services/speaker-user-select-dialog.service.spec.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/services/speaker-user-select-dialog.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/speaker-user-select-dialog.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/speaker-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.ts
Labels: feature, los-extension

#3159 Fix los detail
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
Labels: bug

#3125 Use user short name in chat messages
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message/chat-group-detail-message.component.ts
Labels: bug

#3113 Add moderator note
  client/src/app/domain/definitions/permission-relations.ts
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/domain/definitions/permission.ts
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/gateways/repositories/agenda/agenda-item-repository.service.ts
  client/src/app/gateways/repositories/agenda/functions.ts
  client/src/app/site/modules/info/components/legal-notice-content/legal-notice-content.component.html
  client/src/app/site/modules/info/components/privacy-policy-content/privacy-policy-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/components/structure-level-list/structure-level-list.component.html
Labels: feature, los-extension

#3162 Add new speaker without structure level (small fix)
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug

#3161 Add structure level slides
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.spec.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/current-speaking-structure-level-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/current-speaking-structure-level-slide.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.spec.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/current-structure-level-list-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/current-structure-level-list-slide.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/definitions/slides.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: feature, los-extension

#3141 Make it possible to set reset-password input field to visible
  client/src/app/site/pages/login/pages/reset-password-confirm/components/reset-password-confirm/reset-password-confirm.component.html
  client/src/app/site/pages/login/pages/reset-password-confirm/components/reset-password-confirm/reset-password-confirm.component.ts
  client/src/app/site/pages/login/pages/reset-password-confirm/reset-password-confirm.module.ts
Labels: feature, ui

#3180 Fix los detail moderator note not loaded
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
Labels: bug, los-extension

#3127 Remove default number from user
  client/src/app/domain/fieldsets/user.ts
  client/src/app/domain/models/users/user.export.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/export/participants-export-example.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/export/csv-export-example.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
Labels: clean up

#3173 Make intervention deselectable
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
Labels: bug, los-extension

#3175 Fix participant multiselect structure levels
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug, los-extension

#3182 Stop speaker with interposed questions warning
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/speaking-times/speaking-times.component.ts
Labels: enhancement, los-extension

#3178 Always display speaking times if enabled
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
Labels: los-extension

#3176 Speaking times added to los detail view
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speakers-time-management/speakers-time-management.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.spec.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/list-of-speakers.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
Labels: los-extension

#3165 Change styling in structure Level projection slides
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.ts
  client/src/assets/styles/utils.scss
Labels: ui, los-extension

#3183 LoS extension UI changes
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/services/user-controller.service.ts
Labels: ui, los-extension

#3197 Clean extra moderator notes from autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: clean up, los-extension

#3179 Allow stopping interposed questions without speaker
  client/src/app/domain/models/speakers/speaker.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/services/speaker-user-select-dialog.service.ts
Labels: los-extension

#3194 Change speaking times card and add functionality
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/services/projection-dialog.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/current-speaking-structure-level-slide.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/current-structure-level-list-slide.service.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: los-extension

#3200 Only pause speaking speakers
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug, los-extension

#3208 Speaking times card
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.scss
Labels: los-extension

#3201 Improve speaking times in autopilot
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/app/site/pages/meetings/pages/participants/export/speaker-csv-export.service/speaker-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: los-extension

#3214 Speaker export add columns and filter
  client/src/app/site/pages/meetings/pages/participants/export/speaker-csv-export.service/speaker-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
  client/src/app/site/services/duration.service.ts
Labels: los-extension

#3216 Moderation note rebuild and swap order with speaking times
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.spec.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
Labels: los-extension
