Repository OpenSlides/openslides-client, pull requests merged in 2024-12, with the labels that each got.

#4425 Fix the appearance from the editor
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
Labels: bug, staging

#4392 Rm search-deleted-models presenter
  client/src/app/gateways/presenter/search-deleted-models-presenter.service.spec.ts
  client/src/app/gateways/presenter/search-deleted-models-presenter.service.ts
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
  client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.ts
Labels: clean up

#4408 Fix perm check for los content addSelf method
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug, high

#4410 Motion poll title change: rm trailing ':'
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
Labels: good first issue, enhancement

#4446 Add additional_submitter field to motion create, enabled by new setting
  client/src/app/domain/models/list-of-speakers/list-of-speakers.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature, Lorentz

#4449 Fix pdf export if a meeting has no description
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: bug

#4412 Update view Timestamp logic to fix setAmendmentState problem
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/amendment-controller.service/amendment-controller.service.ts
Labels: bug

#4385 Fix list election mobile layout
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.scss
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
Labels: bug

#4454 Show Amendments which delete only whole paragraphs
  client/src/app/domain/models/motions/motion.ts
Labels: bug, critical

#4456 Fix delegated vote weight visibility
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug, good first issue

#4461 Fix some diff issues when changes include formatting (#4452)
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
Labels: bug, staging

#4472 Fix show all changes checkbox state persistance
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/base/base-motion-detail-child.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, high, staging

#4464 Update translations
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-settings/autopilot-settings.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4474 Update supported browser versions
  client/src/app/site/pages/login/services/browser-support.service.ts
  client/tests/Dockerfile.test
  client/tests/package-lock.json
  client/tests/package.json
Labels: staging

#4473 Update getPollResult to avoid translate undefined
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-pdf.service/topic-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-pdf.service.ts
Labels: bug, staging

#4379 Add VoteWeight documentation and translated search for detail poll view
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.ts
Labels: bug, good first issue, enhancement

#4428 Update motion submission date label visiblity
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-timestamp/motion-manage-timestamp.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-timestamp/motion-manage-timestamp.component.ts
Labels: bug

#4458 Fix election pdf export (more than 9 candidates)
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-pdf.service.ts
Labels: bug

#4460 Enhance anonymized nominal polls
  client/src/app/domain/models/poll/poll.ts
  client/src/app/gateways/repositories/polls/poll-repository.service/poll-repository.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
Labels: enhancement

#4475 Participant create wizard and presence
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug

#4479 Support MARK tag as inline, fix another diff issue
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
Labels: bug

#4450 Update Meeting Info: change count structure levels
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.ts
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.html
Labels: bug

#4459 Fix public access settings and group visibility
  client/src/app/site/pages/meetings/base/base-meeting.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
Labels: enhancement, Lorentz
