Repository OpenSlides/openslides-client, pull requests merged in 2024-04, with the labels that each got.

#3495 Fix submitter extension display issues
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-catalog.service/motion-pdf-catalog.service.ts
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
Labels: bug, Lorentz

#3496 Fix wrong version number after update
  Dockerfile
Labels: bug, high

#3497 Fix participant structure level layout
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
Labels: ui

#3501 Use docker compose v2 in prod build action
  .github/workflows/build.yml
  Makefile
Labels: critical

#3403 Fix for meeting settings default groups
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
Labels: bug

#3490 Fix blank screen on projection switch
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.ts
  client/src/app/site/pages/meetings/modules/projector/components/slide-container/slide-container.component.ts
Labels: bug, high

#3504 Submitter extension display issues cleanup
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-catalog.service/motion-pdf-catalog.service.ts
Labels: clean up

#3507 Fix os-banner icon not centered
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.html
Labels: bug

#2949 Change Arrow behaviour in motion-detail
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
  client/src/app/ui/modules/icon-container/components/icon-container/icon-container.component.html
  client/src/app/ui/modules/icon-container/components/icon-container/icon-container.component.ts
Labels: enhancement, tablet, phone

#3276 Extend shared worker
  client/package-lock.json
  client/package.json
  client/src/app/gateways/base-icc-gateway.service.ts
  client/src/app/gateways/http-stream/http-stream.service.spec.ts
  client/src/app/gateways/http-stream/http-stream.service.ts
  client/src/app/gateways/http-stream/http-stream.ts
  client/src/app/gateways/http-stream/index.ts
  client/src/app/openslides-main-module/services/shared-worker.service.ts
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/communication-manager.service/communication-manager.service.spec.ts
  client/src/app/site/services/communication-manager.service/communication-manager.service.ts
  client/src/app/site/services/communication-manager.service/index.ts
  client/src/app/site/services/communication-manager.service/stream-handler.ts
  client/src/app/site/services/connection-status.service.spec.ts
  client/src/app/worker/autoupdate/autoupdate-stream-pool.ts
  client/src/app/worker/autoupdate/autoupdate-stream.ts
  client/src/app/worker/autoupdate/interfaces-autoupdate.ts
  client/src/app/worker/default-shared-worker.worker.ts
  client/src/app/worker/http/auth.spec.ts
  client/src/app/worker/http/auth.ts
  client/src/app/worker/http/http-stream-pool.spec.ts
  client/src/app/worker/http/http-stream-pool.ts
  client/src/app/worker/http/http-stream.spec.ts
  client/src/app/worker/http/http-stream.ts
  client/src/app/worker/http/http-subscription-polling.spec.ts
  client/src/app/worker/http/http-subscription-polling.ts
  client/src/app/worker/http/http-subscription-sse.spec.ts
  client/src/app/worker/http/http-subscription-sse.ts
  client/src/app/worker/http/http-subscription.ts
  client/src/app/worker/http/stream-utils.ts
  client/src/app/worker/icc/icc-stream-pool.ts
  client/src/app/worker/icc/icc-stream.ts
  client/src/app/worker/sw-auth.ts
  client/src/app/worker/sw-autoupdate.ts
  client/src/app/worker/sw-control.ts
  client/src/app/worker/sw-icc.ts
Labels: feature, enhancement

#3502 Add additional filter/sort/link for contribution-list
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-sort.service/participant-speaker-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
Labels: high, enhancement, Röntgen

#3488 Add option to customize autopilot content
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.module.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-settings/autopilot-settings.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-settings/autopilot-settings.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-settings/autopilot-settings.component.spec.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-settings/autopilot-settings.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/services/autopilot.service.ts
Labels: feature, high, los-extension

#3509 Some cleanup of linter warnings
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
  client/src/app/ui/modules/vertical-tab-group/components/vertical-tab-group/vertical-tab-group.component.ts
  client/src/app/worker/default-shared-worker.worker.ts
  client/src/app/worker/http/auth.ts
  client/src/app/worker/sw-auth.ts
  client/src/app/worker/sw-autoupdate.ts
  client/src/app/worker/sw-control.ts
  client/src/app/worker/sw-icc.ts
Labels: clean up

#3510 Cleanup of linter warnings
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/site/pages/organization/services/organization-controller.service.ts
  client/src/app/site/services/auth-check.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/color.service.ts
  client/src/app/site/services/global-search/global-search.service.ts
  client/src/app/site/services/model-request.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/ui/base/base-form-field-control.ts
  client/src/app/ui/modules/color-form-field/components/color-form-field/color-form-field.component.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/chess-dialog/components/chess-dialog/chess-dialog.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree.service.ts
  client/src/app/ui/pipes/entries/entries.pipe.ts
  client/src/app/ui/pipes/localized-date-range/localized-date-range.pipe.ts
  client/src/app/worker/http/http-stream-pool.ts
  client/src/app/worker/http/http-stream.ts
  client/src/app/worker/http/http-subscription-polling.ts
  client/src/test.ts
Labels: clean up

#3466 List of speakers UI rework
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.spec.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.html
Labels: feature, high, los-extension

#3533 Fix Meeting dashboard cards white corner in dark mode
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
Labels: bug, ui

#3534 Fix single autoupdate requests in fallback mode
  client/src/app/worker/http/http-stream.ts
Labels: bug

#3532 Fix mat-hint overlapping with following components
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.scss
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/projectors/components/projector-countdown-dialog/components/projector-countdown-dialog/projector-countdown-dialog.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
Labels: bug, ui

#3531 Extend current speaking structure level slide
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/components/current-speaking-structure-level-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/current-speaking-structure-level-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-speaking-structure-level-slide/current-speaking-structure-level-slide.module.ts
Labels: feature, los-extension

#3523 Add subscription for submitter in agenda
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
Labels: bug

#3543 Add missing subscriptions
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
Labels: bug, staging

#3540 Fix too wide global search dialog
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
Labels: bug, ui

#3553 Set http subscriptions inactive after error
  client/src/app/worker/http/http-subscription-polling.spec.ts
  client/src/app/worker/http/http-subscription-polling.ts
  client/src/app/worker/http/http-subscription-sse.spec.ts
  client/src/app/worker/http/http-subscription-sse.ts
Labels: bug, high, staging

#3545 Add a sorting to motion supporters in PDF export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#3550 Move identifier of *.subscription.ts on top
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
  client/src/app/site/pages/meetings/pages/mediafiles/mediafiles.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
  client/src/app/site/pages/meetings/pages/projectors/projectors.subscription.ts
  client/src/app/site/pages/organization/organization.subscription.ts
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
Labels: low, clean up

#3556 Fixed visibility of inactive attribute and hide filters
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
Labels: bug, staging

#3562 Fix structure level not displayed
  client/src/app/domain/fieldsets/misc.ts
  client/src/app/domain/fieldsets/user.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
Labels: bug, staging

#3572 Do not hide filters for users
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
Labels: bug, staging

#3574 Hide three-dot menu on permissions lower than canupdate in participant list
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: enhancement, staging

#3561 Update the perms in singleItemMenu of participant-list
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug, staging

#3541 Fix visibility of participant list singleitem menu
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug

#3584 Remove duble template
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug

#3585 Update permissions for attributes in participant views
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
Labels: bug, staging

#3569 Retrieve vote public key on demand
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/gateways/vote-decrypt-gateway.service.ts
  client/src/app/site/pages/organization/organization.subscription.ts
Labels: enhancement

#3571 Prepend pub key size in cipher text
  client/src/app/gateways/vote-decrypt-gateway.service.ts
Labels: enhancement

#3594 Cleanup of linter warnings 3
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/chat/modules/chat-group-dialog/components/chat-group-dialog/chat-group-dialog.component.ts
  client/src/app/site/pages/meetings/pages/interaction/services/broadcast.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/allocation-list/allocation-list.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-dialog/motion-poll-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/services/workflow-export.service/workflow-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/meetings/services/sequential-number-mapping.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/site/pages/organization/pages/designs/modules/theme-builder-dialog/components/theme-builder-dialog.component.ts
  client/src/app/site/services/global-search/global-search.service.ts
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
  client/src/app/ui/modules/sidenav/components/image/image.component.ts
  client/src/app/worker/autoupdate/autoupdate-stream-pool.ts
Labels: clean up

#3597 Restrict visibility of last email sent to canSeeSensibleData
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: bug

#3476 Fix committee export and example import file
  client/src/app/domain/models/comittees/committee.constants.ts
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/export/committee-csv-export-example.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-export.service/committee-export.service.ts
Labels: bug

#3602 Fix initial data creation in CI
  .github/workflows/build.yml
Labels: bug

#3551 In pdf export of attachment trim trailing '/' of url setting
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#3604 Improve meeting change subscription handling
  client/src/app/site/base/base-model-request-handler.component/base-model-request-handler.component.ts
  client/src/app/site/pages/meetings/base/base-meeting-model-request-handler.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/agenda-content-object-form/components/agenda-content-object-form/agenda-content-object-form.component.ts
  client/src/app/site/pages/meetings/pages/agenda/components/agenda-main/agenda-main.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers-main/list-of-speakers-main.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/components/topic-import-main/topic-import-main.component.ts
  client/src/app/site/pages/meetings/pages/assignments/components/assignment-main/assignment-main.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-main/assignment-poll-main.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot-main/autopilot-main.component.ts
  client/src/app/site/pages/meetings/pages/history/components/history-main/history-main.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/components/mediafile-main/mediafile-main.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-main/meeting-settings-group-detail-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-main/motion-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list-main/amendment-list-main.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-main/motion-poll-main.component.ts
  client/src/app/site/pages/meetings/pages/participants/components/participant-main/participant-main.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail/participant-detail.component.ts
  client/src/app/site/pages/meetings/pages/polls/components/poll-main/poll-main.component.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-main/projector-main.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/fullscreen-projector/components/fullscreen-projector-main/fullscreen-projector-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail-main/account-detail-main.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/components/committee-detail/committee-detail.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/committee-detail-meeting-main/committee-detail-meeting-main.component.ts
Labels: bug, clean up

#3559 FIX Navigation Between Motions and Amendments
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/services/motion-detail-view-originurl.service/index.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/services/motion-detail-view-originurl.service/motion-detail-view-originurl.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/amendment-controller.service/amendment-controller.service.ts
Labels: bug

#3573 Improve meeting user relation handling
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/assignments/assignments.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/worker/sw-autoupdate.ts
Labels: clean up, enhancement, performance

#3623 Fix election projection user names not displayed
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
Labels: bug, critical

#3621 Fix editorial final version in a motion
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-highlight-form/motion-highlight-form.component.ts
Labels: bug, critical, staging

#3634 Add option to disable connection closing on inactivity
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
Labels: feature, staging
