Repository OpenSlides/openslides-client, pull requests merged in 2024-08, with the labels that each got.

#3959 Fix account list sort
  client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
Labels: bug, high

#3957 Redirect to last accessed page after login
  client/src/app/site/guards/auth.guard.ts
  client/src/app/site/guards/permission.guard.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/openslides-router.service.ts
  client/src/app/site/services/reroute.service.ts
Labels: feature

#3967 Fix too big attachment texts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
Labels: bug, ui

#3960 Read servertime from headers
  client/src/app/gateways/presenter/server-time-presenter.service.spec.ts
  client/src/app/gateways/repositories/projector-countdowns/projector-countdown-repository.service.ts
  client/src/app/gateways/server-time.service.spec.ts
  client/src/app/gateways/server-time.service.ts
  client/src/app/site/pages/meetings/modules/projector/components/projector-clock/projector-clock.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.ts
  client/src/assets/time.txt
Labels: enhancement

#3937 Improve projector timers
  client/src/app/gateways/repositories/projectors/projector-repository.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/components/projection-dialog/projection-dialog.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projection-dialog/services/projection-dialog.service.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projector-button/components/projector-button/projector-button.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/projector-countdown-slide/components/projector-countdown-slide.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/countdown-controls/countdown-controls.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/countdown-controls/countdown-controls.component.ts
  client/src/app/site/pages/meetings/pages/projectors/view-models/view-projection.ts
  client/src/app/site/pages/meetings/pages/projectors/view-models/view-projector-countdown.ts
  client/src/app/site/pages/meetings/view-models/projection-build-descriptor.ts
Labels: needs discussion, enhancement

#3963 Autopilot > LoS: UI issues
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
Labels: bug, ui

#3991 Fix new file dialog
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
  client/src/app/ui/modules/media-upload-content/components/media-upload-content/media-upload-content.component.html
Labels: bug, ui

#4006 Fix missing account list meeting `user_ids` subscription
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list-main/account-list-main.component.ts
Labels: bug, staging

#4007 Updated translations
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-sort/components/agenda-sort/agenda-sort.component.html
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-merge-dialog/account-merge-dialog.component.html
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-filter.service/committee-filter.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/ui/modules/editor/components/editor-image-dialog/editor-image-dialog.component.html
  client/src/app/ui/modules/editor/components/editor-link-dialog/editor-link-dialog.component.html
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
  client/src/assets/styles/global-components-style.scss
  client/src/styles.scss
Labels: staging

#4013 Updated translations
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: staging

#3979 Allow `YN` votes for motions
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-dialog/motion-poll-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-dialog/motion-poll-dialog.component.ts
Labels: feature, Dunant

#4021 Fix new file dialog component
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/attachment-control.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/components/attachment-control/attachment-control.component.html
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/components/attachment-control/attachment-control.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.scss
  client/src/app/ui/modules/media-upload-content/components/media-upload-content/media-upload-content.component.scss
  client/src/styles.scss
Labels: bug, ui

#4029 Fix for the progress snackbar of pdf exports
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: bug, low

#4025 Fix poll progress number
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/base/base-view-model.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: bug

#4044 Fix linter missing content
  client/.eslintrc.js
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message/chat-group-detail-message.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail/category-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-detail/motion-block-detail.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
Labels: clean up

#3693 Adjust projected motion/topic/election to new detail view
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/assignment-slide/components/assignment-slide/assignment-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/assignment-slide/components/assignment-slide/assignment-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/topic-slide/components/topic-slide/topic-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/topic-slide/components/topic-slide/topic-slide.component.scss
  client/src/app/site/pages/meetings/pages/motions/styles/motion-common-styles.scss
  client/src/assets/styles/mixins/detail-view-appearance.scss
Labels: bug

#4046 Fix projector: stopwatch linked to countdown setting
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.html
Labels: bug

#3977 Add new forward parameter for CRs
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: feature, Becquerel

#4060 Fix voting banner presence change not detected
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
Labels: bug, high

#3978 Add filters to poll single votes
  client/src/app/site/pages/meetings/modules/poll/components/poll-filtered-votes-chart/poll-filtered-votes-chart.component.html
  client/src/app/site/pages/meetings/modules/poll/components/poll-filtered-votes-chart/poll-filtered-votes-chart.component.scss
  client/src/app/site/pages/meetings/modules/poll/components/poll-filtered-votes-chart/poll-filtered-votes-chart.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/votes-table/votes-table.component.html
  client/src/app/site/pages/meetings/modules/poll/components/votes-table/votes-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/modules/poll/services/votes-filter.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-vote.ts
Labels: Hofstadter

#4063 Fix wrong value in user form if `is_active` empty
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: bug

#4068 Disable shift + enter save
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/modules/user-components/components/user-password-form/user-password-form.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/components/agenda-item-info-dialog/agenda-item-info-dialog.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/components/comment-section-list/comment-section-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-create-dialog/components/motion-block-create-dialog/motion-block-create-dialog.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
Labels: bug, high
