Repository OpenSlides/openslides-client, pull requests merged in 2024-09, with the labels that each got.

#4073 Add parsed data cleanup rule
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
Labels: enhancement, Schrödinger

#4081 Show read/write groups only with canManageChat permission
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail/chat-group-detail.component.html
Labels: bug

#4080 Use isSameProperty in hasSortOptionSelected
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
Labels: bug

#4079 Handle floatLabel for admin_ids
  client/src/app/ui/base/base-form-field-control.ts
Labels: bug

#4062 Handle chat messages with `meeting_user_id` set to `null`
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message/chat-group-detail-message.component.ts
Labels: enhancement

#4089 Fix vote for delegation buttons
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
Labels: bug, high, staging

#4064 Remove max votes from form data when not available
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
Labels: bug

#4103 Change pdf worker file extension
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/assets/pdfworker/pdf.worker.min.js
Labels: bug, staging

#4106 Send mediafile title only if not published
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts
Labels: bug, staging

#4109 Import pdfjs via node module
  client/angular.json
  client/ngsw-config.json
  client/package-lock.json
  client/package.json
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/services/slide-mediafile.service.ts
  client/src/assets/pdfworker/pdf.worker.min.js
  client/src/styles.scss
  nginx/nginx.conf
Labels: bug, staging

#4115 Fix nomination-list in assignment poll track usage
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-meta-info/assignment-poll-meta-info.component.html
Labels: bug

#4066 Reduce data sent by shared worker
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/worker/autoupdate/autoupdate-stream.ts
  client/src/app/worker/autoupdate/autoupdate-subscription.ts
  client/src/app/worker/autoupdate/interfaces-autoupdate.ts
Labels: performance

#4129 Rename shared worker
  client/src/app/openslides-main-module/services/shared-worker.service.ts
Labels: bug, staging

#4132 Change submitternames in export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug, staging

#4138 Rename orga mediafiles fix
  client/src/app/gateways/repositories/mediafiles/mediafile-repository.service.ts
Labels: bug, staging

#4141 Fix follow generic relation subset
  client/src/app/site/services/autoupdate/autoupdate.service.ts
  client/src/app/site/services/model-request-builder/model-request-builder.service.ts
Labels: bug, staging

#4134 Replace span with the relevant os-class
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
Labels: bug

#4136 Change default motion poll title
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
Labels: enhancement

#4128 Fix a none item id 0 in selector for motion block
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/components/motion-block-list/motion-block-list.component.ts
Labels: bug

#4100 Align editor styles with displayed content stylings
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
Labels: enhancement

#4139 Change poll title in Autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
Labels: enhancement

#3969 Fix amendment list performance
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
Labels: enhancement, performance

#4082 dashboard: reposition closed meeting icon
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/dashboard-detail.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.scss
Labels: enhancement, Curie, Onnes

#4160 Hide group/external_id for non meeting admins
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
Labels: bug, high

#4161 File-list: Hide edit/group button in multiselect
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
Labels: bug

#4169 Add default_password to account_list subscription
  client/src/app/gateways/repositories/users/user-repository.service.ts
Labels: bug

#4162 Update layout of pw reset/pw reset confirm pages
  client/src/app/site/pages/login/pages/reset-password/components/reset-password/reset-password.component.html
  client/src/app/site/pages/login/pages/reset-password/components/reset-password/reset-password.component.scss
Labels: bug, ui

#4180 Adjust motion poll appearance to YN motion poll method layout
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.scss
Labels: enhancement

#4177 Fix Motion-list CSV export and add new Version to export
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
Labels: bug, high

#4173 Add default poll method to motion settings
  client/src/app/domain/definitions/meeting-settings-defaults.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/definitions/index.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: enhancement

#4027 Customizable gender field
  client/src/app/domain/fieldsets/user.ts
  client/src/app/domain/models/gender/gender.ts
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/domain/models/users/user.constants.ts
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/gender/gender-repository.service.spec.ts
  client/src/app/gateways/repositories/gender/gender-repository.service.ts
  client/src/app/gateways/repositories/gender/gender.action.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/openslides-main-module/services/app-load.service.ts
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/modules/user-components/user-components.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/accounts-routing.module.ts
  client/src/app/site/pages/organization/pages/accounts/accounts.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/components/account-main/account-main.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/components/account-import-list/account-import-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/gender.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/genders.config.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.spec.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/gender-list-routing.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/gender-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/services/gender-controller.service.spec.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/services/gender-controller.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/view-models/view-gender.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/view-models/view-organization.ts
Labels: feature
