Repository OpenSlides/openslides-client, pull requests merged in 2024-10, with the labels that each got.

#4188 Render all pdf pages
  client/src/app/site/pages/meetings/modules/projector/modules/slides/base/base-slide-component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
Labels: bug, critical

#4175 Add a meeting setting for motion-metadata background color in projector
  client/src/app/domain/definitions/meeting-settings-defaults.ts
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: bug, high

#4202 Motion refactoring fixes
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-highlight-form/motion-highlight-form.component.ts
Labels: bug, high

#4207 Update translations
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort/participant-list-sort.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4215 Fix error msgs when isCommitteeManager is called as anon
  client/src/app/site/services/operator.service.ts
Labels: bug, staging

#4230 Fix list of speakers error on vote delegation activated
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug, staging

#4229 Add public access orga setting
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/organizations/organization.ts
  client/src/app/domain/models/users/group.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/gateways/repositories/organization-repository.service.ts
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
  client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.ts
Labels: enhancement, staging

#4233 Allow to save jitsi infos for closed meetings
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug

#4231 Prevent translation of repo filter options
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
  client/src/app/site/base/base-filter.service/os-filter.ts
  client/src/app/ui/modules/list/components/filter-menu/filter-menu.component.html
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
Labels: bug

#4223 Don't show poll at wifi access in autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug

#4243 Fix public access button not displayed
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.html
  client/src/app/site/pages/login/pages/login-mask/components/login-mask/login-mask.component.ts
Labels: staging

#4189 Get meeting-mediafile url with url property in motion pdf export
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-meeting-mediafile.ts
Labels: bug

#4258 Fix a problem with update of presence in account-button
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
Labels: bug, critical

#4261 Reason projected twice
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.html
Labels: bug, staging

#4262 Make motion content titles bold
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.scss
Labels: enhancement, staging

#4265 Add 'no-debugger' to linter rules
  client/.eslintrc.js
Labels: enhancement

#4269 Set `lang` attribute to user language
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
Labels: bug

#4245 Try to fix model request subscribeTo: missing unusedSubscriptions
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.ts
  client/src/app/site/services/model-request.service.ts
Labels: bug

#4157 Activate moderation note for every LoS
  client/src/app/domain/definitions/permission-relations.ts
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/domain/definitions/permission.ts
  client/src/app/domain/models/agenda/agenda-item.ts
  client/src/app/domain/models/list-of-speakers/list-of-speakers.ts
  client/src/app/gateways/repositories/list-of-speakers/list-of-speakers-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.ts
  client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
Labels: enhancement

#4284 Fix amendment wizard routing
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/motion-form-routing.module.ts
Labels: bug, high

#4286 Fix motion create form
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-permission.service/motion-permission.service.ts
Labels: bug

#4270 Add word-break style to keep width in account-detail view
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.scss
Labels: bug, low

#4199 Motion with amendments add icon and amendment number
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/amendment-paragraph-unified-change.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
  client/src/app/ui/modules/editor/components/editor/extensions/office.ts
Labels: high, enhancement, Schrödinger

#4304 Remove margin from amendment-nr to parargraph below
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: enhancement, staging
