Repository OpenSlides/openslides-client, pull requests merged in 2024-03, with the labels that each got.

#3379 Ensure that general abstain is listed in single votes
  client/src/app/domain/models/poll/option.ts
  client/src/app/infrastructure/definitions/relations/relations.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-main/assignment-poll-main.component.ts
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
  client/src/app/site/pages/meetings/pages/polls/view-models/view-option.ts
Labels: bug

#3371 Prevent second scrollbar by rm wrong style
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.html
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.scss
Labels: enhancement, ui, staging

#3376 Remove speakingTime errors when toggling los_can_see
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
Labels: bug, los-extension

#3335 Update committee export (username, labels, timestamp)
  client/src/app/site/pages/meetings/services/meeting-controller.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-export.service/committee-export.service.ts
Labels: bug

#3386 Center finished speakers
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
Labels: low, ui

#3377 Add free text submitter field
  client/src/app/domain/models/motions/motion.ts
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/motion-slide-data.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/amendment-list-pdf.service/amendment-list-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-base-sort.service/motion-list-base-sort.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
Labels: feature, high

#3368 Improve service worker update flow
  client/angular.json
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/site/modules/global-spinner/components/global-spinner/global-spinner.component.ts
  client/src/app/site/modules/global-spinner/services/spinner.service.ts
  client/src/app/site/modules/site-wrapper/services/update.service.ts
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/ngsw-safety.json
  client/src/sw.js
  nginx/nginx.conf
Labels: staging

#3245 Fix reset default settings
  client/src/app/domain/definitions/meeting-settings-defaults.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: bug

#3394 Update edit total time to format min:sec
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
Labels: enhancement

#3399 Change label color of focused form field in dark mode
  client/src/assets/styles/theme-styles.scss
Labels: bug, staging

#3395 Prevent certain speech state changes
  client/src/app/domain/models/speakers/speech-state.ts
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level-list-of-speakers.ts
Labels: bug, los-extension, staging

#3402 Change visibility of projection icon
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/services/projectable-list.service.ts
Labels: enhancement

#3415 Fix interposed questions with structure level
  client/src/app/domain/models/speakers/speech-state.ts
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level-list-of-speakers.ts
Labels: bug, los-extension

#3404 Ellipse motion category
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
Labels: enhancement

#3411 Add editors and working group speakers to pdf export
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: enhancement

#3421 Add translation markers
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
Labels: bug

#3097 Update mdc snackbar, progress bar, spinner
  client/src/app/gateways/export/progress-snack-bar/components/progress-snack-bar/progress-snack-bar.component.ts
  client/src/app/gateways/export/progress-snack-bar/progress-snack-bar.module.ts
  client/src/app/gateways/export/progress-snack-bar/services/progress-snack-bar-control.service.ts
  client/src/app/gateways/export/progress-snack-bar/services/progress-snack-bar.service.ts
  client/src/app/gateways/http.service.ts
  client/src/app/infrastructure/utils/import/json-import-file-utils.ts
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/site/base/base-import.service/base-backend-import.service.ts
  client/src/app/site/base/base-import.service/base-import.service.ts
  client/src/app/site/base/base.component.ts
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/modules/global-headbar/global-headbar.module.ts
  client/src/app/site/modules/info/components/info-actions/info-actions.component.ts
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/detail-view.module.ts
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/poll-progress/poll-progress.component.html
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/topic-poll.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/assignment-poll.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/history/services/history.service.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/interaction-container.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.scss
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/motion-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/services/meeting-component-service-collector.service.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/account-detail.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-password/account-password.component.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/dashboard-detail.module.ts
  client/src/app/site/pages/organization/pages/organization-info/organization-info.module.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
  client/src/app/site/services/component-service-collector.service.ts
  client/src/app/site/services/import-service-collector.service.ts
  client/src/app/ui/modules/file-upload/file-upload.module.ts
  client/src/app/ui/modules/sidenav/sidenav.module.ts
  client/src/assets/styles/theme-styles.scss
Labels: dependencies

#3436 Fix unreadable ActionWorkerBar link
  client/src/app/site/modules/wait-for-action-dialog/components/wait-for-action-banner/wait-for-action-banner.component.scss
Labels: bug, ui

#3380 Activate re-add button only if active speaker is true
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.ts
Labels: bug, los-extension

#3434 Add username sort option to account list
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
Labels: enhancement

#3443 Test TreeSortService
  client/src/app/site/base/base-sort.service/base-sort.service.ts
  client/src/app/ui/modules/sorting/modules/sorting-tree/services/tree-sort.service.spec.ts
Labels: tests

#3437 Test MeetingSettingDirective
  client/src/app/ui/directives/meeting-setting/meeting-setting.directive.spec.ts
Labels: tests

#3440 Hide statute amendments checkbox
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: clean up

#3425 Change display of identical motions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.html
  client/src/app/ui/modules/comma-separated-listing/components/comma-separated-listing/comma-separated-listing.component.ts
Labels: enhancement

#3103 Prevent some linter warnings and make OS4 more accessiblle
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-personal-note/motion-personal-note.component.html
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-list/components/organization-mediafile-list/organization-mediafile-list.component.html
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.html
  client/src/app/ui/modules/expandable-content-wrapper/components/expandable-content-wrapper/expandable-content-wrapper.component.scss
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.html
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.scss
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/app/ui/modules/file-list/file-list.module.ts
  client/src/app/ui/modules/grid/definitions.ts
  client/src/app/ui/modules/grid/grid/grid.component.html
  client/src/app/ui/modules/sidenav/components/copyright-sign/copyright-sign.component.html
  client/src/app/ui/modules/sidenav/modules/easter-egg/modules/c4-dialog/components/c4-dialog/c4-dialog.component.html
  client/src/app/ui/modules/vertical-tab-group/components/vertical-tab-group/vertical-tab-group.component.html
  client/src/app/ui/modules/vertical-tab-group/components/vertical-tab-group/vertical-tab-group.component.scss
Labels: accessibility

#3419 Add new options for editing speaking time
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
Labels: feature, los-extension

#3451 Update translations
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-filter.service/committee-filter.service.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-filter/meeting-list-filter.service.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#3357 Enhance meeting settings
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/allocation-list/allocation-list.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/allocation-list/allocation-list.component.scss
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/allocation-list/allocation-list.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.html
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.scss
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definition.service.spec.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definition.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature

#3467 Fix motions list without projector permission
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/services/projectable-list.service.ts
Labels: bug, critical, staging

#3449 Hide unneeded scrollbar
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.scss
Labels: bug

#3458 Fix style of submission date icons
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-timestamp/motion-manage-timestamp.component.scss
Labels: bug, ui

#3468 PDF export: Add option 'Show only changed paragraph'
  client/src/app/domain/models/motions/motions.constants.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-catalog.service/motion-pdf-catalog.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: feature, staging

#3439 Fix projection of LoS
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/common-list-of-speakers-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/common-list-of-speakers-slide/components/common-list-of-speakers-slide.component.ts
Labels: bug, los-extension

#3473 Fix projection for users without structure level
  client/src/app/gateways/repositories/users/user-repository.service.ts
Labels: bug, high

#3482 Add motion list has identical motion filter
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: feature, staging

#3492 Internal state indicator for change recommendations
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff-summary/motion-detail-diff-summary.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/paragraph-based-amendment/paragraph-based-amendment.component.html
Labels: enhancement, Röntgen

#3489 Change user name fallback
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/infrastructure/utils/import/users/user-import-helper.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/site/services/user-controller.service.ts
Labels: high, enhancement, Röntgen
