Repository OpenSlides/openslides-client, pull requests merged in 2024-02, with the labels that each got.

#3224 Structure level selection for interposed questions
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/components/speaker-user-select-dialog/speaker-user-select-dialog.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/speaker-user-select-dialog/services/speaker-user-select-dialog.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/speaker-controller.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
Labels: feature, los-extension

#3240 Add `getID()` debug function
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
Labels: feature

#3228 Fix navigation of reset password confirm in no data case
  client/src/app/site/pages/login/pages/reset-password-confirm/components/reset-password-confirm/reset-password-confirm.component.ts
Labels: bug, low

#3229 Hide inactive SLLOS
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level-list-of-speakers.ts
Labels: feature, los-extension

#3140 Add preamble to motion edit view
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
Labels: enhancement

#3222 Limit distance between columns in autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
Labels: enhancement, los-extension

#3237 Change gender filter string
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter.service/participant-list-filter.service.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
Labels: enhancement

#3261 Fix participant structure level not displayed in autopilot
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
Labels: bug, los-extension

#3223 Export speaker agenda item number
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-list-of-speakers.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.html
  client/src/app/site/pages/meetings/pages/participants/participants.subscription.ts
Labels: feature, los-extension

#3256 Pull motion.import base-import-ui fixes into separate PR
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.scss
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.ts
  client/src/app/ui/modules/import-list/definitions/backend-import-preview.ts
Labels: bug, ui

#3246 Fix the glaring vote decrypt rebase bugs
  client/src/app/site/pages/meetings/modules/poll/components/check-vote-validity-dialog/check-vote-validity-dialog.component.ts
  client/src/app/site/pages/meetings/modules/poll/modules/voting-cryptography-info-dialog/components/voting-cryptography-info-dialog/voting-cryptography-info-dialog.component.ts
  client/src/app/site/pages/meetings/modules/poll/modules/voting-cryptography-info-dialog/services/voting-cryptography-info-dialog.service.ts
Labels: bug

#3264 Fix CI with meta repo
  .github/workflows/build.yml
Labels: bug, high

#3265 Fix autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug

#3254 Fix user edit for illegal legacy username
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: bug, critical

#3244 Warn if motions with amendments are deleted
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
Labels: enhancement

#3210 Update motion detail reset button and creation date
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-meta-data/motion-meta-data.component.html
Labels: enhancement

#3271 Change border color of user statistics
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.html
Labels: bug, low, ui

#3219 Create user from string with username generated in backend
  client/src/app/site/pages/meetings/modules/participant-search-selector/components/participant-search-selector/participant-search-selector.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
Labels: bug, high

#3260 Use backend import for committee import
  client/src/app/gateways/repositories/committee-repository.service.ts
  client/src/app/gateways/repositories/committees/committee.action.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/committee-import.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/components/committee-import-list/committee-import-list.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/components/committee-import-list/committee-import-list.component.scss
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/components/committee-import-list/committee-import-list.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/services/committee-import-service.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-import/services/committee-import.service/committee-import.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/services/committee-list-export.service/committee-export.service.ts
  client/src/app/site/pages/organization/pages/committees/services/committee-controller.service.ts
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
  client/src/app/ui/modules/import-list/definitions/import-list-header-definition.ts
Labels: feature

#3263 Fix to stop overwrite given workflow_id by repo selector
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
Labels: bug, high

#3251 inject version.txt via docker build
  Dockerfile
  client/src/assets/version.txt
Labels: enhancement

#3275 Fix motion multiselect forwarding error
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: bug

#3279 Add contributions list content type filter
  client/src/app/domain/definitions/model-icons.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
Labels: feature, high

#3290 Display amendment name if amendment has no number
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
Labels: bug

#3308 Update moderation notes visibility if no projection
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug, los-extension

#3309 Handle projection options visibility in speaking times
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
Labels: bug, los-extension

#3312 Remove disabled state from edit "total time"
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/speaking-times/speaking-times.component.ts
Labels: feature, high, los-extension

#3278 Add min distance between speaking card and left autopilot side
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.scss
Labels: ui, los-extension

#3282 Update structure level list slide to three columns
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/current-structure-level-list-slide/components/current-structure-level-list-slide.component.ts
Labels: enhancement, los-extension

#3321 Update moderation note visibility in los view
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/components/list-of-speakers/list-of-speakers.component.html
Labels: bug, los-extension

#3320 Improve service worker app updates
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/services/autoupdate/autoupdate-communication.service.ts
Labels: bug

#3281 Fix agenda list subscription opening twice
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
  client/src/app/site/services/model-request.service.ts
Labels: bug

#3326 Add structure_level to participant export
  client/src/app/site/pages/meetings/pages/participants/export/participant-csv-export.service/participant-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
Labels: feature, high

#3327 Remove default structure level the from account detail view
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
Labels: bug, high

#3329 Fix motion default workflow selection
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts
Labels: bug

#3332 Hide moderation note if no agenda item assigned
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.html
Labels: bug

#3349 Make speaker list display speaker names in the same way as LoS
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/components/participant-speaker-list/participant-speaker-list.component.ts
Labels: bug, high, los-extension

#3348 Fix PoO creation for others
  client/src/app/gateways/repositories/speakers/speaker-repository.service.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/components/point-of-order-dialog/point-of-order-dialog.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/components/point-of-order-dialog/point-of-order-dialog.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/point-of-order-dialog.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/services/point-of-order-dialog.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/speaker-controller.service.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: feature, high

#3354 Fix countdows with PoO updates
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/view-models/view-structure-level-list-of-speakers.ts
Labels: bug

#3355 Fix meeting edit, start_time/end_time at disabled daterange
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: bug, high

#3351 Reordered columns in participant export
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
Labels: enhancement

#3270 Small improvement to the get-forwarding-meetings presenter call
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: bug

#3365 Fix moderation note permission updates
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.ts
Labels: bug, staging

#3374 Make own structure_level changeable
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
Labels: bug, los-extension, staging
