Repository OpenSlides/openslides-client, pull requests merged in 2025-01, with the labels that each got.

#4501 Add edit user option in participant list
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
Labels: good first issue, enhancement, Schrödinger

#4521 Improve translation functionality
  client/src/app/domain/definitions/languages.ts
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/infrastructure/utils/lang-to-locale.ts
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.html
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/modules/translations/translation-pruning-loader.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
Labels: translation

#4522 Cleanup language functionality
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/base/base-sort.service/base-sort.service.ts
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
  client/src/app/site/modules/translations/translation-pruning-loader.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-block-slide/components/motion-block-slide/motion-block-slide.component.ts
  client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.html
Labels: bug, clean up

#4493 Add pdf export of visible amendments in motion detail view
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-export.service/motion-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#4492 Add max per option validator and onkeyon for votes input fields
  client/src/app/infrastructure/utils/validators/is-number-range.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
Labels: bug

#4484 Hide submitters dropbox in motion create if cannot see users
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
Labels: bug

#4540 Forbid changing the motion state if backend doesn't allow it
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug

#4534 Cleanup remove surplus meeting active filters service
  client/src/app/site/pages/meetings/base/base-meeting-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/services/agenda-item-filter.service/agenda-item-filter.service.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-list/services/assignment-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/services/motion-block-detail-filter-list.service/motion-block-detail-filter-list.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/amendment-list-filter.service/amendment-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-filter/participant-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/services/participant-speaker-list-filter.service/participant-speaker-list-filter.service.ts
  client/src/app/site/pages/meetings/pages/polls/modules/poll-list/services/poll-list-filter.service/poll-list-filter.service.ts
  client/src/app/site/pages/meetings/services/meeting-active-filters.service.spec.ts
  client/src/app/site/pages/meetings/services/meeting-active-filters.service.ts
Labels: clean up

#4533 Fix general meeting settings problem
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
Labels: bug

#4542 Redirect to main login after logout
  client/src/app/site/services/openslides-router.service.ts
  client/tests/integration/login.spec.ts
Labels: bug

#4529 Fix creation of amendments that have no changes
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/amendment-create-wizard/amendment-create-wizard.component.ts
Labels: enhancement

#4543 Fix motion diff projection if start line set
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
Labels: bug, high, staging

#4516 Add allow_to_edit_own_delegation
  client/src/app/domain/definitions/permission-relations.ts
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/domain/definitions/permission.ts
  client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/modules/participant-list-info-dialog/components/participant-list-info-dialog/participant-list-info-dialog.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/modules/participant-list-info-dialog/components/participant-list-info-dialog/participant-list-info-dialog.component.ts
  client/src/app/site/pages/meetings/pages/participants/services/common/participant-controller.service/participant-controller.service.ts
  client/src/app/ui/modules/search-selector/components/list-search-selector/list-search-selector.component.ts
Labels: feature, low

#4491 Improve view model list equality checks
  client/src/app/gateways/repositories/base-repository.ts
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll-controller.service/poll-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-change-recommendation-controller.service/motion-change-recommendation-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/amendment-controller.service/amendment-controller.service.ts
  client/src/app/site/pages/meetings/services/active-polls.service.ts
Labels: bug, clean up

#4489 Fix wrong language after login
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
  client/src/app/openslides-main-module/openslides-main.module.ts
  client/src/app/site/modules/translations/openslides-translation.module.ts
  client/src/app/site/modules/translations/translation-parser.ts
  client/src/app/site/modules/translations/translation-pruning-loader.ts
  client/src/app/site/pages/meetings/meetings-routing.module.ts
  client/src/app/site/pages/meetings/meetings.module.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/index.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/meetings-navigation-wrapper.component.html
  client/src/app/site/pages/meetings/modules/meetings-navigation/meetings-navigation-wrapper.component.scss
  client/src/app/site/pages/meetings/modules/meetings-navigation/meetings-navigation-wrapper.component.spec.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/meetings-navigation-wrapper.component.ts
  client/src/app/site/pages/meetings/modules/meetings-navigation/meetings-navigation.module.ts
Labels: bug, high, staging

#4547 Fix visual warning for deletion of a meeting
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/components/meeting-list/meeting-list.component.ts
  client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.html
  client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.scss
  client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.ts
  client/src/app/ui/modules/prompt-dialog/services/prompt.service.ts
Labels: feature, low

#4551 Use accent color for update snackbar button
  client/src/app/site/modules/site-wrapper/components/site-wrapper/site-wrapper.component.html
Labels: bug, low

#4549 Fix repo filters with none option not saved
  client/src/app/site/base/base-filter.service/base-filter-list.service.ts
Labels: bug, high

#4553 base-poll: Remove keyup handling because of twice confirm dialogs
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
Labels: bug, staging

#4443 Add svg files as header option in pdf export
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: feature, low, good first issue

#4485 Add notice about running votes for public access users
  client/src/app/site/pages/meetings/modules/poll/services/vote-controller.service/vote-controller.service.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll/assignment-poll.component.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll/motion-poll.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll/motion-poll.component.ts
Labels: enhancement, Lorentz

#4502 Add new filter Status for meetings list
  client/src/app/site/pages/meetings/view-models/view-meeting.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-filter/meeting-list-filter.service.ts
Labels: enhancement

#4562 Fix too long name in mat-chip
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-motion-meeting-users/motion-manage-motion-meeting-users.component.html
  client/src/styles.scss
Labels: bug, ui

#4555 Fix visible error message in base poll form
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.scss
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
Labels: bug, low

#4556 Add svg files as footer in pdf export
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: feature, low

#4550 Fix error on first login after password change
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/modules/user-components/components/password-form/password-form.component.html
  client/src/app/site/services/auth.service.ts
  client/src/app/site/services/user-controller.service.ts
Labels: bug

#4570 Add jasmine tests for the theme service
  client/src/app/site/services/theme.service.spec.ts
Labels: tests
