Repository OpenSlides/openslides-client, pull requests merged in 2025-05, with the labels that each got.

#4937 Fix change reco edit on custom start line number
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts
Labels: bug, critical

#4905 Localize poll result numbers
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.ts
Labels: enhancement, Schrödinger

#4953 Display poll progress on autopilot
  client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.html
Labels: bug, critical

#4955 Fix motion export not sorted on multiselect
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/components/motion-multiselect-actions/motion-multiselect-actions.component.ts
Labels: bug

#4933 Change layout if editorial version is edited
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.ts
Labels: bug

#4949 Simplify base-search-selector
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.html
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.scss
  client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts
Labels: bug

#4935 Hide forward menu entry same as forward button
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts
Labels: bug

#4982 Updated translations
  client/src/app/domain/models/poll/poll-constants.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/components/attachment-control/attachment-control.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-form/assignment-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-meta-info/assignment-poll-meta-info.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/components/mediafile-upload/mediafile-upload.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-form/motion-poll-form.component.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4967 Translate gender in the user detail edit view
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: bug

#4981 Add apply button feedback to topic and motion-final-version
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.ts
Labels: enhancement, ui

#4959 Fix linter warnings
  client/eslint.config.mjs
  client/src/app/gateways/error-mapping/error-map.service.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/infrastructure/utils/functions.ts
  client/src/app/site/base/base-sort.service/base-sort.service.ts
  client/src/app/site/guards/permission.guard.ts
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/components/wifi-access-data-slide/wifi-access-data-slide.component.spec.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-import/services/topic-import.service/topic-import.service.ts
  client/src/app/site/pages/meetings/pages/interaction/modules/interaction-container/components/video-player/video-player.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts
  client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/site/services/openslides-router.service.ts
  client/src/app/site/services/user-controller.service.ts
  client/src/app/ui/directives/only-number/only-number.directive.ts
  client/src/app/ui/modules/editor/components/editor-html-dialog/editor-html-dialog.component.ts
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts
  client/src/app/worker/autoupdate/autoupdate-stream.ts
  client/tsconfig.json
Labels: clean up

#5001 Fix autopilot mediafile title link
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: bug

#4950 Fix innerHTML images escaping box
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
  client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.scss
  client/src/styles.scss
Labels: bug

#4951 Allow super/orgaadmins to see published orga mediafiles in meetings
  client/src/app/site/pages/meetings/pages/mediafiles/services/mediafile-controller.service.ts
Labels: bug

#5005 Motion-diff service cleanup
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-line-numbering.service/motion-line-numbering.service.ts
  client/src/assets/i18n/cs.po
  client/src/assets/i18n/de.po
  client/src/assets/i18n/es.po
  client/src/assets/i18n/fr.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/ru.po
  client/src/assets/i18n/template-en.pot
Labels: clean up

#4948 Fix forward dialog
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: enhancement, Becquerel

#5007 Ensure motion back navigation doesn't go to edit mode
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-form/components/motion-form/motion-form.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.html
Labels: bug

#5011 Ensure meeting startpage pictures are set
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
Labels: bug, high

#5014 Fix search term permanence in lists
  client/src/app/ui/modules/list/base/base-list.component.ts
Labels: bug
