Repository OpenSlides/openslides-client, pull requests merged in 2025-08, with the labels that each got.

#5262 Disable correct committees in edit mask
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-edit/components/committee-detail-edit/committee-detail-edit.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.scss
  client/src/app/site/services/operator.service.ts
Labels: bug

#5279 Fix live voting enabled default setting
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
Labels: bug

#5292 Use correct version of @types/node
  client/package-lock.json
  client/package.json
Labels: dependencies, javascript

#5242 Move motion diff service into npm package
  .github/workflows/ci-package-motion-diff.yml
  .github/workflows/continuous-integration.yml
  Dockerfile
  client/package-lock.json
  client/package.json
  client/src/app/infrastructure/utils/dom-helpers.spec.ts
  client/src/app/infrastructure/utils/dom-helpers.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/definitions/index.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
  packages/openslides-motion-diff/.dockerignore
  packages/openslides-motion-diff/.gitignore
  packages/openslides-motion-diff/package-lock.json
  packages/openslides-motion-diff/package.json
  packages/openslides-motion-diff/src/diff/definitions.ts
  packages/openslides-motion-diff/src/diff/index.spec.ts
  packages/openslides-motion-diff/src/diff/index.ts
  packages/openslides-motion-diff/src/diff/internal-diff-transform.ts
  packages/openslides-motion-diff/src/diff/internal-diff.ts
  packages/openslides-motion-diff/src/diff/internal.ts
  packages/openslides-motion-diff/src/diff/utils.ts
  packages/openslides-motion-diff/src/index.ts
  packages/openslides-motion-diff/src/line-numbering/definitions.ts
  packages/openslides-motion-diff/src/line-numbering/index.spec.ts
  packages/openslides-motion-diff/src/line-numbering/index.ts
  packages/openslides-motion-diff/src/line-numbering/internal.ts
  packages/openslides-motion-diff/src/line-numbering/line-numbering.ts
  packages/openslides-motion-diff/src/line-numbering/utils.ts
  packages/openslides-motion-diff/src/utils/definitions.ts
  packages/openslides-motion-diff/src/utils/dom-helpers.spec.ts
  packages/openslides-motion-diff/src/utils/dom-helpers.ts
  packages/openslides-motion-diff/src/utils/tests.ts
  packages/openslides-motion-diff/src/utils/utils.spec.ts
  packages/openslides-motion-diff/src/utils/utils.ts
  packages/openslides-motion-diff/tsconfig.json
  packages/openslides-motion-diff/vite.config.ts
Labels: enhancement

#5318 Add SL-separation in single votes result projection and fix layout
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/poll-slide-data.ts
Labels: bug, feature, Bohr

#5332 Very important bugfix
  client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts
Labels: bug, high

#5321 Fix ol wrong diff on default start value
  packages/openslides-motion-diff/src/diff/internal.ts
  packages/openslides-motion-diff/src/utils/dom-helpers.spec.ts
  packages/openslides-motion-diff/src/utils/dom-helpers.ts
Labels: bug, high
