Repository OpenSlides/openslides-client, pull requests merged in 2025-02, with the labels that each got.

#4589 Switch translation marker
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/count-users/count-users.component.html
Labels: bug, translation

#4602 Fix line numbering layout in motion export with default font
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#4601 Add warning icon as svg to pdf export
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-worker.worker.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
Labels: bug

#4606 Standalone components UI base
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/topic-poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/agenda-item-list.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/assignment-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/motion-multiselect.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/categories/categories.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/participant-speaker-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/structure-level.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/projector-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/account-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/gender-list.module.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-components.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/committee-list.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/meeting-list.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/modules/organization-tag-dialog/organization-tag-dialog.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/organization-tags.module.ts
  client/src/app/site/pages/organization/pages/organization-tags/pages/organization-tag-list/organization-tag-list.module.ts
  client/src/app/ui/modules/action-card/action-card.component.html
  client/src/app/ui/modules/action-card/action-card.component.scss
  client/src/app/ui/modules/action-card/action-card.component.spec.ts
  client/src/app/ui/modules/action-card/action-card.component.ts
  client/src/app/ui/modules/action-card/action-card.module.ts
  client/src/app/ui/modules/action-card/index.ts
  client/src/app/ui/modules/chip/chip.component.html
  client/src/app/ui/modules/chip/chip.component.scss
  client/src/app/ui/modules/chip/chip.component.spec.ts
  client/src/app/ui/modules/chip/chip.component.ts
  client/src/app/ui/modules/chip/chip.module.ts
  client/src/app/ui/modules/chip/index.ts
  client/src/app/ui/modules/choice-dialog/choice-dialog.component.html
  client/src/app/ui/modules/choice-dialog/choice-dialog.component.scss
  client/src/app/ui/modules/choice-dialog/choice-dialog.component.spec.ts
  client/src/app/ui/modules/choice-dialog/choice-dialog.component.ts
  client/src/app/ui/modules/choice-dialog/choice-dialog.module.ts
  client/src/app/ui/modules/choice-dialog/index.ts
  client/src/app/ui/modules/choice-dialog/services/choice.service.ts
Labels: dependencies

#4614 Fix LineNumbering font in virtual file system
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
  client/src/app/site/pages/meetings/services/media-manage.service.ts
Labels: bug, staging

#4617 Make icon-container standalone
  client/src/app/site/modules/info/info.module.ts
  client/src/app/site/modules/user-components/user-components.module.ts
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/topic-poll.module.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/topic-detail.module.ts
  client/src/app/site/pages/meetings/pages/agenda/pages/agenda-item-list/agenda-item-list.module.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/assignment-poll.module.ts
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/chat-group-list.module.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/mediafile-list.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/motion-forward-dialog.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/motion-poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/comments/comments.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-blocks/motion-blocks.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/motion-detail.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/motion-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/participant-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-speaker-list/participant-speaker-list.module.ts
  client/src/app/site/pages/meetings/pages/participants/pages/structure-levels/structure-level.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/projector-detail.module.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-list/projector-list.module.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/account-list.module.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-components.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/committee-list.module.ts
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/dashboard-detail.module.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/meeting-list.module.ts
  client/src/app/ui/modules/file-list/file-list.module.ts
  client/src/app/ui/modules/icon-container/icon-container.component.html
  client/src/app/ui/modules/icon-container/icon-container.component.scss
  client/src/app/ui/modules/icon-container/icon-container.component.spec.ts
  client/src/app/ui/modules/icon-container/icon-container.component.ts
  client/src/app/ui/modules/icon-container/icon-container.module.ts
  client/src/app/ui/modules/icon-container/index.ts
  client/src/app/ui/modules/list/list.module.ts
Labels: dependencies

#4628 Implement page-based scrolling for PDFs
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: feature

#4585 Add fields
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/organization-tags/organization-tags.subscription.ts
Labels: clean up

#4630 Translations
  client/src/app/domain/definitions/permission.config.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/assets/i18n/de.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4610 Add moderation note pdf export
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/moderation-note/moderation-note.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/list-of-speakers-content.module.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/services/moderation-note-pdf.service/moderation-note-pdf.service.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.html
Labels: enhancement

#4635 Translations
  client/src/assets/i18n/de.po
Labels: staging

#4565 Add live vote register to motion/assignment-poll-detail
  client/src/app/domain/models/poll/poll.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
  client/src/app/site/pages/meetings/modules/poll/components/poll-progress/poll-progress.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.scss
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.scss
  client/src/app/site/pages/meetings/pages/polls/polls.subscription.ts
  client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.html
Labels: feature, Onnes

#4519 Fix alignment of microphone in speakers list
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.scss
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.scss
Labels: enhancement

#4641 Switch mandate empty number case
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug

#4634 Sort the attachments by title
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.ts
Labels: enhancement

#4652 Add set_as_template to the meeting create form
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/committee-detail-meeting.module.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
Labels: enhancement

#4639 Fix insertions in empty paragraph of amendment with two words
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
Labels: bug

#4655 Fix participant list menu entries
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
Labels: bug, ui

#4660 Fix motion export with headings
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug, critical, staging

#4619 Make some components standalone (part 4)
  client/src/app/site/modules/global-spinner/global-spinner.module.ts
  client/src/app/site/pages/meetings/modules/meetings-component-collector/attachment-control/attachment-control.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/wifi-access-data-slide/wifi-access-data-slide.module.ts
  client/src/app/site/pages/meetings/pages/interaction/services/interaction-service.module.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-upload/mediafile-upload.module.ts
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-upload/components/organization-mediafile-upload/organization-mediafile-upload.component.ts
  client/src/app/site/pages/organization/pages/mediafiles/modules/organization-mediafile-upload/organization-mediafile-upload.module.ts
  client/src/app/ui/modules/media-upload-content/media-upload-content.component.html
  client/src/app/ui/modules/media-upload-content/media-upload-content.component.scss
  client/src/app/ui/modules/media-upload-content/media-upload-content.component.spec.ts
  client/src/app/ui/modules/media-upload-content/media-upload-content.component.ts
  client/src/app/ui/modules/media-upload-content/media-upload-content.module.ts
  client/src/app/ui/modules/openslides-overlay/index.ts
  client/src/app/ui/modules/openslides-overlay/openslides-overlay.module.ts
  client/src/app/ui/modules/openslides-overlay/overlay.component.html
  client/src/app/ui/modules/openslides-overlay/overlay.component.scss
  client/src/app/ui/modules/openslides-overlay/overlay.component.spec.ts
  client/src/app/ui/modules/openslides-overlay/overlay.component.ts
  client/src/app/ui/modules/openslides-overlay/services/overlay.service.ts
  client/src/app/ui/modules/qr-code/index.ts
  client/src/app/ui/modules/qr-code/qr-code.component.html
  client/src/app/ui/modules/qr-code/qr-code.component.scss
  client/src/app/ui/modules/qr-code/qr-code.component.spec.ts
  client/src/app/ui/modules/qr-code/qr-code.component.ts
  client/src/app/ui/modules/qr-code/qr-code.module.ts
Labels: dependencies

#4654 Add not amendment filter to motion-list
  client/src/app/site/pages/meetings/pages/motions/services/list/motion-list-filter.service/motion-list-filter.service.ts
Labels: enhancement, Schrödinger

#4680 Fix icon place of reset filters in motion call list
  client/src/app/site/pages/meetings/pages/motions/pages/motion-call-list/components/motion-call-list/motion-call-list.component.html
Labels: bug, ui

#4681 Use default behaviour for motion-workflow multiselect
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-list/workflow-list.component.html
Labels: bug

#4683 Fix alignment of line numbering in pdf export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#4682 Add message for superadmin self-adding on los and not in meeting
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
Labels: bug
