Repository OpenSlides/openslides-client, pull requests merged in 2025-07, with the labels that each got.

#5114 Add line numbers to empty `li` elements
  client/eslint.config.mjs
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug

#5126 Fix filterObject function
  client/src/app/infrastructure/utils/functions.spec.ts
  client/src/app/infrastructure/utils/functions.ts
Labels: bug, low

#5155 Fix navigation between motions with identical sequential number
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/detail-view/detail-view.component.ts
Labels: bug, high

#4852 Add checkbox to motion forward dialog
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
Labels: feature, waiting, Onnes

#5205 Clear searchfield after committee change
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
  client/src/app/ui/modules/list/base/base-list.component.ts
  client/src/app/ui/modules/list/components/sort-filter-bar/sort-filter-bar.component.ts
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
Labels: bug

#5216 Fix vote amount validators
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
Labels: bug, staging

#5200 Replace guest with external
  client/src/app/domain/models/users/user.ts
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-edit/participant-detail-edit.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-import/definitions/index.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/services/common/account-filter.service.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
Labels: enhancement, waiting

#5197 Fix category multi sorting
  client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
  client/src/app/ui/modules/sorting/modules/sorting-list/components/sorting-list/sorting-list.component.ts
Labels: bug

#5196 Update motion export pdf defaults
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.ts
Labels: bug

#5219 When projection los, the projected los is displayed, too
  client/src/app/site/pages/meetings/pages/autopilot/autopilot.subscription.ts
  client/src/app/site/pages/meetings/pages/autopilot/components/autopilot/autopilot.component.ts
Labels: enhancement

#5228 Allow to search for external and home committee in account list
  client/src/app/gateways/repositories/users/user-repository.service.ts
  client/src/app/site/pages/meetings/view-models/view-user.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-search/account-list-search.service.ts
Labels: enhancement

#5252 Translations
  client/src/assets/i18n/template-en.pot
Labels: staging

#5248 Add filetype icons to attachments
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/pages/meetings/pages/mediafiles/view-models/view-meeting-mediafile.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.scss
Labels: enhancement

#5102 Fix account edit for committee admin and fix permission handling
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.html
  client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-edit/meeting-edit.component.ts
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.ts
  client/src/app/site/pages/organization/pages/orga-meetings/pages/meeting-list/services/meeting-list-filter/meeting-list-filter.service.ts
  client/src/app/site/services/auth-check.service.ts
  client/src/app/site/services/operator.service.ts
  client/src/app/site/services/reroute.service.ts
  client/src/app/site/services/user.service.ts
  client/src/app/ui/directives/perms/oml-perms.directive.spec.ts
  client/src/app/ui/directives/perms/oml-perms.directive.ts
Labels: bug
