Repository OpenSlides/openslides-client, pull requests merged in 2025-03, with the labels that each got.

#4666 Add external_id meeting clone dialog
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.html
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.scss
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.spec.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.ts
Labels: enhancement

#4687 Fix wrong sub settings updates
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail-field/meeting-settings-group-detail-field.component.ts
  client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts
Labels: bug

#4703 Fix long urls in motion view and pdf export
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.scss
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/assets/styles/mixins/detail-view-appearance.scss
Labels: bug

#4704 Remove surplus os-import-list component
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.scss
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.spec.ts
  client/src/app/ui/modules/import-list/components/import-list/import-list.component.ts
  client/src/app/ui/modules/import-list/import-list.module.ts
Labels: clean up

#4689 Make some conformity changes for backend issue 2866
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/domain/models/projector/projection-default.ts
  client/src/app/gateways/repositories/meeting-repository.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/list-of-speakers/modules/current-los-slide/current-los-slide.module.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/definitions/slides.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: bug, high

#4705 Italien translations
  client/src/assets/i18n/it.po
Labels: translation

#4716 Remove external-id in the meeting clone prompt again
  client/src/app/site/pages/organization/pages/committees/committees.subscription.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.html
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.scss
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.spec.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/components/meeting-clone-dialog/meeting-clone-dialog.component.ts
Labels: enhancement, staging

#4720 Fix access to livestream
  client/src/app/site/pages/meetings/pages/interaction/services/interaction-receive.service.ts
Labels: enhancement

#4719 Fix approximation for pdf scrolling
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: bug, staging

#4640 Update meetings add dialog
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.scss
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
Labels: feature, ui

#4706 Update scss mixed declation because deprecated
  client/src/app/site/modules/global-headbar/components/global-search/global-search.component.scss
  client/src/app/site/modules/site-wrapper/components/banner/banner.component.scss
  client/src/app/site/modules/user-components/components/user-delete-dialog/user-delete-dialog.component.scss
  client/src/app/site/pages/meetings/modules/meetings-component-collector/detail-view/components/projectable-title/projectable-title.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/countdown-time/countdown-time.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/projector-countdown-slide/components/projector-countdown-slide.component.scss
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-list/chat-group-list.component.scss
  client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/user-statistics/user-statistics.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.scss
  client/src/app/site/pages/meetings/pages/motions/styles/motion-common-styles.scss
  client/src/app/site/pages/organization/pages/dashboard/pages/dashboard-detail/components/dashboard/dashboard.component.scss
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
  client/src/app/ui/modules/input/components/rounded-input/rounded-input.component.scss
  client/src/app/ui/modules/sidenav/components/sidenav/sidenav.component.scss
  client/src/app/ui/modules/spinner/components/spinner/spinner.component.scss
  client/src/assets/styles/global-components-style.scss
  client/src/assets/styles/tiptap.scss
Labels: dependencies, good first issue

#4701 Improve editor controls tab navigation via directive
  client/src/app/ui/modules/editor/components/editor/editor.component.html
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
  client/src/app/ui/modules/editor/components/editor/editor.component.ts
  client/src/app/ui/modules/editor/directives/tab-navigation.directive.ts
  client/src/app/ui/modules/editor/editor.module.ts
Labels: low, enhancement, accessibility

#4603 Implement single votes poll slide
  client/src/app/domain/models/meetings/meeting.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.html
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.scss
  client/src/app/site/pages/meetings/modules/poll/components/single-option-chart-table/single-option-chart-table.component.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.html
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.scss
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/poll-slide-data.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/poll-slide.module.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.scss
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll/motion-poll.component.html
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/app/ui/modules/icon-container/icon-container.component.html
  client/src/app/ui/modules/icon-container/icon-container.component.scss
  client/src/app/ui/modules/icon-container/icon-container.component.ts
  client/src/assets/styles/poll-styles-common.scss
  client/src/styles.scss
Labels: feature, Dunant

#4729 Close the reco menu after opening the edit dialog
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts
Labels: bug

#4752 Fix pdf export for live voting polls
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
Labels: bug, Onnes

#4748 Allow YNA to set min/max vote amount
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-dialog/assignment-poll-dialog.component.html
Labels: high, enhancement, Arrhenius

#4744 Add pdf pagewise scrolling in the projector
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.html
  client/src/app/site/pages/meetings/modules/projector/components/projector/projector.component.ts
  client/src/app/site/pages/meetings/modules/projector/components/slide-container/slide-container.component.ts
  client/src/app/site/pages/meetings/modules/projector/modules/slides/components/mediafile-slide/components/mediafile-slide.component.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
Labels: enhancement

#4757 Allow Committee admin to change passwords
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-password/account-password.component.ts
Labels: bug

#4750 Fix cursor for live voting
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.scss
Labels: bug, Onnes

#4749 Remove 'Disable connection closing on inactivity' account setting
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.ts
  client/src/app/site/services/autoupdate/autoupdate.service.ts
Labels: enhancement

#4769 Update translations
  client/src/app/domain/models/poll/poll-constants.ts
  client/src/app/gateways/error-mapping/error-map-utils.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/modules/poll/components/entitled-users-table/entitled-users-table.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-detail-content/assignment-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/definitions/index.ts
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-polls/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-detail-content/motion-poll-detail-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-polls/components/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/pages/meetings/pages/polls/view-models/view-poll.ts
  client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/assets/i18n/cs.po
  client/src/assets/i18n/de.po
  client/src/assets/i18n/es.po
  client/src/assets/i18n/fr.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/ru.po
  client/src/assets/i18n/template-en.pot
Labels: translation, staging

#4773 Fix committee admin's ability to add user on account level
  client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/services/operator.service.ts
Labels: bug, staging

#4753 Fix renderDiffLines in amendment-list-pdf service
  client/src/app/site/pages/meetings/pages/motions/services/export/amendment-list-pdf.service/amendment-list-pdf.service.ts
Labels: bug

#4775 Strip slashes from mediafile names on zip export
  client/src/app/gateways/export/file-export.service/file-export.service.ts
  client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/services/mediafile-list-export.service/mediafile-list-export.service.ts
Labels: bug, high, staging

#4764 Fix forward dialog
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
Labels: enhancement

#4774 Disallow html usage in PromptService by default
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/components/mediafile-delete-dialog/mediafile-delete-dialog.component.html
  client/src/app/site/pages/meetings/pages/mediafiles/components/mediafile-delete-dialog/mediafile-delete-dialog.component.scss
  client/src/app/site/pages/meetings/pages/mediafiles/components/mediafile-delete-dialog/mediafile-delete-dialog.component.ts
  client/src/app/site/pages/meetings/pages/mediafiles/services/mediafile-common.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-delete-dialog/motion-delete-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-delete-dialog/motion-delete-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-delete-dialog/motion-delete-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts
  client/src/app/site/pages/organization/pages/committees/modules/committee-meeting-preview/committee-meeting-preview.component.ts
  client/src/app/ui/modules/prompt-dialog/prompt-dialog.component.html
  client/src/app/ui/modules/prompt-dialog/prompt-dialog.component.ts
  client/src/app/ui/modules/prompt-dialog/services/prompt.service.ts
Labels: bug, high, staging

#4765 Cleanup user-detail-view and pt create wizard
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.html
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: clean up

#4766 Fix pdf export heading styles
  client/src/app/domain/models/meetings/meeting.constants.ts
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
Labels: bug

#4789 Fix different issues around vote
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.ts
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-dialog/assignment-poll-dialog.component.html
  client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/ui/modules/prompt-dialog/prompt-dialog.component.html
Labels: bug, critical

#4807 Update translations (DE,IT)
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
  client/src/assets/i18n/de.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4808 Fix origin motion toggle not displayed if setting not set
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, staging

#4812 Hide internal motions from list
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: bug, staging

#4815 Fix scaling of poll results in forwarded motions
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.scss
Labels: bug, staging

#4796 Add subscription fields
  client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
Labels: clean up

#4709 Add multiselect drag/drop for sorting tree
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.html
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.scss
  client/src/app/ui/modules/sorting/modules/sorting-tree/components/sorting-tree/sorting-tree.component.ts
Labels: bug, low

#4809 Fix unusable input fields from account dialog
  client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.html
  client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
Labels: enhancement

#4818 Disable forwarding of single amendments
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.html
Labels: bug

#4819 Fix motion backtracking for amendments
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
Labels: bug
