Repository OpenSlides/openslides-client, pull requests merged in 2025-04, with the labels that each got.

#4817 Fix errors in participant add search
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug

#4837 gender list: add missing back arrow
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.html
Labels: bug

#4821 Add a max validator to max_votes_amount in same cases
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.html
  client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts
Labels: enhancement

#4841 Fix edit chat msg prefix part
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message-form/chat-group-detail-message-form.component.html
  client/src/app/site/pages/meetings/pages/chat/pages/chat-group-list/components/chat-group-detail-message-form/chat-group-detail-message-form.component.scss
Labels: bug

#4847 Fix formating in motion xlsx export at empty personal notes
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug

#4854 Fix meeting admin if user.update
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug, high

#4874 Filter empty forwarded motions from motion list
  client/src/app/site/pages/meetings/pages/motions/services/common/motion-controller.service/motion-controller.service.ts
Labels: bug, staging

#4866 Add the missing summary title and allow translation
  client/src/app/site/pages/meetings/pages/participants/pages/participant-import/services/participant-import.service/participant-import.service.ts
Labels: bug

#4820 Add mark of invalid motion supporters
  client/src/app/site/base/base-sort.service/base-sort-list.service.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
Labels: feature

#4637 Rework Motion Export View
  client/src/app/gateways/export/csv-export.service/csv-export.service.ts
  client/src/app/gateways/export/file-export.service/file-export.service.ts
  client/src/app/gateways/export/html-to-pdf.service/html-to-pdf.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
  client/src/app/gateways/export/pdf-document.service/pdf-images.service.ts
  client/src/app/gateways/export/progress-snack-bar/services/progress-snack-bar-control.service.ts
  client/src/app/gateways/export/progress-snack-bar/services/progress-snack-bar.service.ts
  client/src/app/gateways/export/xlsx-export.service/xlsx-export.service.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-key-verbose/poll-key-verbose.pipe.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-parse-number/poll-parse-number.pipe.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-percent-base/poll-percent-base.pipe.ts
  client/src/app/site/pages/meetings/modules/poll/poll.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/motion-export-dialog.module.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/services/motion-export-dialog.service.spec.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/services/motion-export-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/components/motion-multiselect-actions/motion-multiselect-actions.component.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll-controller.service/motion-poll-controller.service.ts
  client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/services/motion-poll.service/motion-poll.service.ts
  client/src/app/site/pages/meetings/pages/motions/motions-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/amendments-routing.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/amendments.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/amendments/components/amendment-list/amendment-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.spec.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-list/motion-list.module.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/amendment-list-pdf.service/amendment-list-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/definitions.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-export.service/motion-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-catalog.service/motion-pdf-catalog.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf-export.service/motion-pdf-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-csv-export.service.ts
  client/src/app/site/pages/meetings/services/export/meeting-pdf-export.service.ts
  client/src/assets/styles/theme-styles.scss
Labels: enhancement, ui

#4838 Add apply button for editorial final version and topic edit form
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/topic-detail.module.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-final-version/motion-final-version.component.ts
Labels: enhancement

#4879 Fix line breaks in editor
  client/src/app/ui/modules/editor/components/editor/editor.component.scss
  client/src/assets/styles/tiptap.scss
Labels: bug

#4877 Clean up group call
  client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
Labels: bug

#4900 Fix display of deleted user for LoS
  client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.html
Labels: bug, high

#4901 Move poll provided pipe methods into other services
  client/src/app/domain/models/poll/poll-constants.ts
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-key-verbose/poll-key-verbose.pipe.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-parse-number/poll-parse-number.pipe.spec.ts
  client/src/app/site/pages/meetings/modules/poll/pipes/poll-parse-number/poll-parse-number.pipe.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.spec.ts
  client/src/app/site/pages/meetings/modules/poll/services/poll.service/poll.service.ts
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-pdf.service/topic-pdf.service.ts
  client/src/app/site/pages/meetings/pages/assignments/services/assignment-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
Labels: bug, critical

#4888 Add new motion state setting for amendment forwarding
  client/src/app/domain/models/motions/motion-state.ts
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
Labels: high, enhancement

#4902 Disable sse tests completely
  client/src/app/worker/http/http-subscription-sse.spec.ts
Labels: bug, tests

#4686 Fix line breaks in lists of pdf export
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-html-to-pdf.service/motion-html-to-pdf.service.ts
Labels: bug, waiting

#4906 Fix complete change reco content deletion inside list item
  client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts
Labels: bug, high

#4910 Update translations
  client/src/app/site/pages/login/pages/reset-password/components/reset-password/reset-password.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-export/components/motion-export/motion-export.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-csv-export.service/motion-csv-export.service.ts
  client/src/app/site/pages/meetings/pages/motions/services/export/motion-xlsx-export.service/motion-xlsx-export.service.ts
  client/src/assets/i18n/cs.po
  client/src/assets/i18n/de.po
  client/src/assets/i18n/it.po
  client/src/assets/i18n/template-en.pot
Labels: staging

#4918 Fix display of invalid supporters
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.ts
Labels: bug, staging

#4921 Custom translation change live update
  client/src/app/openslides-main-module/components/openslides-main/openslides-main.component.ts
Labels: enhancement, staging

#4913 Use PDF/A-3a for exports
  client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
Labels: enhancement
