Repository OpenSlides/openslides-client, pull requests merged in 2025-06, with the labels that each got.

#5032 Translate the default genders in the gender list
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/gender/pages/gender-list/components/gender-list/gender-list.component.ts
  client/src/app/site/pages/organization/pages/accounts/pages/gender/view-models/view-gender.ts
Labels: bug

#5059 Small layout fix to committee view
  client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.scss
  client/src/app/ui/modules/head-toolbar/head-toolbar.component.scss
Labels: bug, staging

#5002 Fix poll detail performance
  client/src/app/site/pages/meetings/modules/poll/base/base-poll-detail.component.ts
Labels: bug, high, staging

#5072 Add netherlands
  client/src/app/domain/definitions/languages.ts
  client/src/assets/i18n/nl.po
Labels: translation, staging

#5086 Committee-list add missing icons
  client/src/app/site/pages/organization/pages/committees/pages/committee-list/components/committee-list/committee-list.component.html
Labels: bug, staging

#5087 Sort committee list
  client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.ts
Labels: bug, staging

#5101 Clean-up
  client/src/app/site/pages/meetings/modules/meetings-component-collector/projectable-list/components/projectable-list/projectable-list.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-extension-field/motion-extension-field.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-meta-data/motion-meta-data.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/origin-motion-meta-data/origin-motion-meta-data.component.html
  client/src/app/ui/modules/list/base/base-list.component.ts
  client/src/app/ui/modules/list/components/list/list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.html
  client/src/app/ui/modules/list/components/view-list/view-list.component.ts
Labels: clean up

#5096 Change order of target meetings
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
Labels: enhancement, Schrödinger

#5056 Add text wrap to attachments in motions, topics and assignments
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
  client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.scss
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/pages/meetings/pages/assignments/pages/assignment-detail/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-content/motion-content.component.scss
Labels: bug

#5098 Add multi select home committee and guest
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
  client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.ts
Labels: high, enhancement

#4958 Show marker for amendment if forwarded
  client/src/app/gateways/repositories/motions/motion-repository.service/motion-repository.service.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.scss
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
  client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/services/motion-forward-dialog.service.ts
  client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff-summary/motion-detail-diff-summary.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff-summary/motion-detail-diff-summary.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion.ts
Labels: feature, Becquerel

#5116 Fix home and redirect
  client/src/app/site/pages/meetings/pages/home/home.config.ts
  client/src/app/site/services/fallback-routes.service.ts
Labels: bug

#5125 Let preview show the correct cell value
  client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
Labels: bug

#5129 Fix visiblity of accepted amendments
  client/eslint.config.mjs
  client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts
Labels: bug, staging
